### ISSUE TITLE
September Editorial Agenda - 28 September 2018

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1011]
Friday, 28 September 2018, Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - French time. I (@amsichani) will be facilitating, succeeding @walshbr as Skype call coordinator.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] -  #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] - #878  Getting a budget line for PH
- [ ] - ~~#915 Support Us wording (Policy, deadline 1 October) For discussion at September meeting: please take a look by then~~ Insufficient progress on #878 so on hold until next meeting.
- [ ] - ~~#948 New positions: Treasurer + Sponsorship Coordinator.~~ Insufficient progress on #878 so on hold until next meeting.
- [ ] -  #836 - update on French Translation of infrastructure pages
- [x] - ~~#991 & #992 - shorten editorial guidelines and introduce a md template for authors - @acrymble~~ 
- [ ] -  #994 Editorial retention strategy
- [x] - #961 - Move Sample Datasets for Creating Network Diagrams lesson (@mariajoafana)
- [ ] - update on recruitment sub committee searches
- [ ] - #979 - Approve or modify proposed revision on the contribute page; and adapt EN and ES pages accordingly
- [ ] - #1018 #1019  #1020   #1021  #1022 #1023 Community Survey Issues

**Comment by spapastamkou** [comment]
Please consider #979 for the agenda as well: I have translated the FR contribute page accordingly. If validated during the meeting, then EN and ES pages should be modified in the same way. If the proposal is further modified, I will make corrections accordingly. (Just in case I won't be able to attend to the meeting, as I will attend a summer school during the last week of September.) I will then be able to close this ticket after the meeting.

**Comment by drjwbaker** [comment]
For info, I'll need to leave early as I'm teaching at 16:00.

**Comment by acrymble** [comment]
@spapastamkou you can add any item you want to the agenda by editing @amsichani 's original post. Click on the ... in the top right corner.

**Comment by alsalin** [comment]
Sorry I can't be there! This may happen a lot as 10am is prime time for meetings in my office :\

**Comment by mariajoafana** [comment]
Sorry too, I won't be able to join the meeting, I will be traveling to a conference

**Comment by spapastamkou** [comment]
I can't be present, sorry: I am at Corsica for a SNA summer school and will very probably be in a bus at the time of the meeting.

**Comment by vgayolrs** [comment]
Hello, I just connected because the meeting was scheduled for 10:00 am in Mexico and it's 9:50 ... but I see that the meeting is over!

**Comment by amsichani** [comment]
oops! we have the wrong Mexican time? Sorry for missing the Skype , @vgayolrs , and thanks for pointing this out for next time!

**Comment by walshbr** [comment]
Oof sorry @vgayolrs - my mistake! Good thing you're in good hands with @amsichani now.

**Comment by vgayolrs** [comment]
Oh, do not worry @walshbr @amsichani , I should have noticed the error in the call that equates the time of Mexico with the time of the East when it is central time (UTC-6). My fault.

**Comment by spapastamkou** [comment]
Hi there! Are there any news on #979 after the meeting? Should I close the ticket? Thanks!

**Comment by amsichani** [comment]
@vgayolrs could you plz confirm that we have the correct Mexican time for our Skype call  **9:00 AM - Mexico time;** 10:00 AM - EST; 3:00 PM - British time; ? cheers!

> Oh, do not worry @walshbr @amsichani , I should have noticed the error in the call that equates the time of Mexico with the time of the East when it is central time (UTC-6). My fault.

**Comment by vgayolrs** [comment]
Hi @amsichani 1 The correct Mexican time is 9:00 AM MxTime (Central, the same as Chicago) = 3:00 PM British time. Thanks!

**Comment by amsichani** [comment]
fab -- thanks @vgayolrs !
