### ISSUE TITLE
November Editorial Agenda - 29 November 2018

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1068]
Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #1070 French Integration (incl  #1096)
    - [ ] #1072 Sample French lessons
- [ ] #878 Getting a budget line for PH + progress on  #915 #918 #948 
- [ ] update on recruitment sub committee searches
- [ ] #1056 editor training idea (@acrymble)
 - [ ] #1037  workflow for ad-hoc translation and draft blogpost #1098(@amsichani )
 - [ ] #1089 "PH in English"? 
- [ ] #936 #1095 Standarization of new proposals? 
- [ ] #1022  Community Survey Issue: Audience and Learning Paths

**Comment by mdlincoln** [comment]
Just a note that I will definitely want to talk about #1070 and the roadmap for French integration (which will touch on #918 and sponsorships)

**Comment by acrymble** [comment]
Can we please get in the habit of leaving minutes on these so that people who didn't attend have some context for what happened? Or that we can come back to them in future if needed?

**Comment by amsichani** [comment]
good point @acrymble --

- [ ] #721 : @arojascastro  @amsichani @jenniferisasi presenting a paper at EADH2018 next week.
- [ ] #1070 :  @mdlincoln to update the submissions site preview pages (now #1101)
@mpuren and @spapastamkou to add 2-3 translated lessons  #1072
separate meeting with @fdlaramee - keep an eye on his boarding process #1096
@programminghistorian/spanish-team to assist FR team on setting up the reviewing process
- [ ] #878: no update
- [ ] update on recruitment sub committee searches: @jenniferisasi proposed a 15days extension for the ES team recruitment process in order to secure more candidates. Agreed.
- [ ] #1056 : Overall we liked the idea esp  the online/remote version of it - @mariajoafana @amsichani would like to attend or test its first iteration!
- [ ] #1037 : blogpost updated #1098 by @amsichani - open for suggestions, comments - wiki page needs to be created? -  list of ad hoc translations to be created by @amsichani 
- [ ]  #1089 : @drjwbaker to create a ticket for history of the PH (now #1102) // @mdlincoln to change the  EN main page header ? (not sure if we all agreed on this)
- [ ]  #1095: @mdlincoln to update task list on this
 - [ ]  #1022 : open
 - [ ]  AOB:  willingness to try to arrange next Skype meeting before the 22nd Dec. @amsichani will update through usual Skype call doodle/reminders.

**Comment by drjwbaker** [comment]
By minutes, I presume you don't want full minutes (she said, they said, he said) but rather a list of..

- action points
- decisions made
- major discussion points

..with each attached to Issues?

**Comment by drjwbaker** [comment]
(@amsichani: sorry, missed your reply before I posted!)

**Comment by acrymble** [comment]
@drjwbaker yes, sorry. Not full minutes. Just a bit of context as we now have. Thanks @amsichani
