### ISSUE TITLE
Onboarding EN Editor Checklist - LeBlanc

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1079]
Welcoming @zoeleblanc to the project! 🎊 This ticket tracks the onboarding process and all of the associated things that need to be done. Check things off as you get to them. We'll do the same, and let us know if you have any concerns?

What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x]  Our Google Group email so you can communicate with other editors (@acrymble)
- [x]  Our Google Analytics account for monitoring web traffic (@acrymble)
- [x]  Our Twitter team (@acrymble)
- [x]  Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x]  Our Skype group so that you can participate in our monthly calls (@walshbr)
- [x]  We will also write a blog post welcoming you publicly to the team.
- [x]  partner you with an existing editor to 'shadow' the editing process so you can get a feel for it.

What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

communication

- [x]  set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x]  set up a twitter account (optional)
- [x]  set up a Skype account and inform @walshbr (mandatory)
- [x]  inform @acrymble of your Google-activated email (mandatory)
- [x]  write an email to the other editors using the Google group (say hello!) (mandatory)

technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x]  contribute to one open ticket on our github repository (mandatory)
- [x]  create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x]  make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x]  Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x]  Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x]  Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by acrymble** [comment]
@zoeleblanc can you please email me your google enabled email address so I can add you to the google group.

**Comment by walshbr** [comment]
I added her to the twitter team @acrymble

**Comment by walshbr** [comment]
#1086 will add a post for Zoe as well as the info needed for her bio and avatar. Besides all the other documentation for you to read @ZoeLeBlanc, we'll need to get you shadowing someone through the editorial process. Anyone got a lesson early in the pipeline who would be willing to volunteer?

**Comment by ZoeLeBlanc** [comment]
@walshbr I can email you my bio and avatar, and thanks for writing the post. I'll take care of some of the technical to-dos today, but no worries if there isn't a good lesson for me to jump on to right away for shadowing. We could also talk about contributing to the main site repo instead if that's easier right now.

**Comment by walshbr** [comment]
@ZoeLeBlanc - there is an open PR where I took a run at your bio and photo - https://github.com/programminghistorian/jekyll/pull/1086. Feel free to edit those directly if you'd like or leave em if you want. They're pulled directly from your site and lightly edited for formatting/color/length is all.

**Comment by acrymble** [comment]
@ZoeLeBlanc I've added you to the Google Analytics account so you can see the traffic stats. If you could try that out and let me know if it's working that would be helpful.

**Comment by ZoeLeBlanc** [comment]
@acrymble I'm all set with the Analytics account. Very cool to see where all the traffic is coming from! I just crossed off most of the remaining todos. Now I just have contributing to an open ticket and shadowing someone. Let me know if there's anything I can do to move those issues forward!
