### ISSUE TITLE
Onboarding FR Editor Checklist - Laramée

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1096]
This is the onboarding editor checklist for @fdlaramee. Welcome to the project,François Dominic, you will find below the onboarding process. Please tick the boxes once done and we'll do the same. 

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x]  Our Google Group email so you can communicate with other editors (@acrymble)
- [x]  Our Google Analytics account for monitoring web traffic (@acrymble)
- [x]  Our Twitter team (@acrymble)
- [x]  Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x]  Our Skype group so that you can participate in our monthly calls (@amsichani )
- [x]  We will also write a blog post welcoming you publicly to the team.
- [x]  partner you with an existing editor to 'shadow' the editing process so you can get a feel for it.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x]  set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x]  set up a twitter account (optional)
- [x]  set up a Skype account and inform @walshbr (mandatory)
- [x]  inform @acrymble of your Google-activated email (mandatory)
- [x]  write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x]  contribute to one open ticket on our github repository (mandatory)
- [x]  create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x]  make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x]  Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x]  Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x]  Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

## The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by fdlaramee** [comment]
Thanks everyone. Will do!

**Comment by acrymble** [comment]
I've added @fdlaramee to the google analytics and the google group.

**Comment by fdlaramee** [comment]
I will assume that this comment qualifies as the " contribute to one open ticket on our github repository " mandatory task required by my onboarding process. If not, please let me know.

**Comment by spapastamkou** [comment]
I assume @fdlaramee will be shadow editor whenever possible in the near future, so I close this ticket.
