### ISSUE TITLE
December Editorial Agenda - Thursday 20 December 2018

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1103]
Thursday 20 December 2018. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #1070 French Integration (incl  #1096)
    - [ ] #1072 Sample French lessons
- [ ] #878 Getting a budget line for PH + progress on  #915 #918 #948 
- [ ] update on recruitment sub committee searches
- [ ] #1056 editor training idea (@acrymble)
 - ~~[ ] #1089 "PH in English"?~~
- [ ] #936 #1095 Standarization of new proposals? 
- [ ]  #1018 Community Survey Issue: Website Search 
-   [ ] [#197](https://github.com/programminghistorian/ph-submissions/issues/197) [#185](https://github.com/programminghistorian/ph-submissions/issues/185) technical infrastructure for original ES lessons

**Comment by acrymble** [comment]
Can I propose we take a break until January, and enjoy the year-end? :)

**Comment by amsichani** [comment]
I d say lets see people's availability on these dates based on doodle results (go ahead with zero availability as a choice, I d say) - we can always have smaller Skype meetings, just for the FR and ES task forces, as they need to work on several tickets.

**Comment by jenniferisasi** [comment]
I can definitely meet with the FR team that week to talk about translations for a global audience and how the revision process works. Plus, I'll be in Spain for Winter break so it should be easier to set up a time

**Comment by acrymble** [comment]
As we get larger, do we want to adjust to a format in which each subteam nominates someone to give an update on that team's progress that month? It doesn't have to be the same person each month but having one spokesperson might be a way to make sure we all know what's happening?

**Comment by jenniferisasi** [comment]
@acrymble I think that's a really good idea. 

@amsichani, we decided not to extend the deadline for the editor search, as I received a few applications a couple of hours before the deadline US time. I'll update on the next step.

**Comment by mdlincoln** [comment]
I wanted to check in on the schedule for the (two?) original Spanish lessons currently under review (https://github.com/programminghistorian/ph-submissions/issues/185 and https://github.com/programminghistorian/ph-submissions/issues/197) - because these will be our first lessons published originally in Spanish, I want to make sure I'm available to check that they're technically working ok, especially as we work towards the French launch.

**Comment by amsichani** [comment]
Minutes of the December meeting, mainly actions points and decisions made - please amend if I misunderstood or skip smth: 

- [ ] #721 please update research output accordingly
- [ ] #1070 The FR team is working on setting up the workflow for editing currently 2 lessons. Will need to have a separate meeting with the ES team in order to familiarise with the editing/reviewing process of translations and perhaps a ES rep could mentor (@jenniferisasi  ? )on this process .
The goal is to have 4 lessons ready by mid February for  launching the PH en francais. @mdlincoln  will need to be provided with a detailed schedule so he can organise his workload accordingly.
- [ ] #878 @drjwbaker reports that there was a complication/ misunderstanding from USussex library people on the type of the agreement for hosting a budget line for PH - will report back when there is an update. Please contribute to  #915 (new 'Sponsor Us' page to be launched with FR pages)
- [ ] update on recruitment sub committee searches : @jenniferisasi and @mariajoafana will decide in the next couple of days on the new members of the ES editorial team.
- [ ] #1056 : no further action at this point because of lack of financial resources .
It has been raised that is important to further support new editors by assigning them a mentor / person of contact during their first editorial task. It'd be also useful to somehow formalise the expectations for the shadowing process for new editors - @amsichani will start a ticket on this.
- [ ] #1018 @ZoeLeBlanc will work on this by mid February.
- [ ] technical infrastructure for original ES lessons: @mdlincoln needs a timeline for this so he ll make sure the tech dev part of it will run smoothly.
