### ISSUE TITLE
January Editorial Agenda - Friday 25th January

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1142]
Friday 25th January. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #1070 French Integration (incl  #1096)
    - [ ] #1072 Sample French lessons
    - [ ] #1136 Translation Editorial Process - Meeting - outcomes
- [ ] #1144/ #1137 - Translation for editorial guidelines re: managing editor role
- [ ] Assistant Managing editor for April -June
- [ ] update on recruitment sub committee searches
- [ ] #878 Getting a budget line for PH + progress on  #915 #918 #948 
- [ ]  #1018 Community Survey Issue: Website Search 
- [ ] ~~@arojascastro sabbatical update~~

**Comment by mdlincoln** [comment]
FYI I'll only be able to be on this call for the first 30-40mins

**Comment by arojascastro** [comment]
I'm teaching an unplanned workshop in Paris... I won't make it unfortunately this time...

**Comment by drjwbaker** [comment]
Afraid I won't be able to make this one after all.

**Comment by vgayolrs** [comment]
So sorry, teaching on Fridays from January until March.

**Comment by alsalin** [comment]
Hi all, I'll try to make it in but we have a day of workshops with the folks at Manifold visiting Emory. In case I can't make it in - an announcement: I'll be on maternity leave again! Woo! From about mid-April to end of June (or so, I'll be able to say more once I get closer to April). That would mean I'd need some help in the ME department for that time.

**Comment by mariajoafana** [comment]
Hi all,

I'll also be teaching on Friday mornings this semester.




*Maria José Afanador-Llach, *PhD
Fundación Histórica Neogranadina
mariajose@neogranadina.org

<http://www.neogranadina.org/>

http://www.mariajoseafanador.com

**Comment by walshbr** [comment]
I have to split at 10:40 to make another appointment at 11, but I'll be there for the first bit! I added one item re: #1144 and bumped it up a little in the agenda order (just so that I can say 10 seconds about it before I leave). Should be very quick.

**Comment by drjwbaker** [comment]
Seems lots of us have had to change plans.. @all who are there: feel free to assign us tasks :)

**Comment by spapastamkou** [comment]
Hi all, neither I can make it this time (too feverish to be operational today, sorry): concerning #1072 I plan to update the lesson on openrefine with final corrections, add an image in FR and launch the editorial process next week.

**Comment by amsichani** [comment]
Minutes of the January meeting, mainly actions points and decisions made - please amend if I misunderstood or skip smth:
- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian: plz update the research page if necessary with conference presentations & publications on PH.
- [ ] #1070 French Integration (incl  #1096)
    - [ ] #1072 Sample French lessons : FR team currently looking for lesson reviewers - @mpuren will create a ticket on communicating a call for FR reviewers on lists/twitter/blogpost
    - [ ] #1136 Translation Editorial Process - Meeting - outcomes : great outcomes, thanks all for participating !
- [ ] #1144/ #1137 - Translation for editorial guidelines re: managing editor role : English text is ready - waiting for ES & FR translation
- [ ] Assistant Managing editor for April -June : @amsichani will open a ticket so we can reflect & discuss further on this #1153 
- [ ] update on recruitment sub committee searches : @jenniferisasi reports on having a couple of interesting candidates - final decisions by next week !
- [ ] #878 Getting a budget line for PH + progress on  #915 #918 #948  : no update
- [ ]  #1018 Community Survey Issue: Website Search : @ZoeLeBlanc will further update on this at next meeting | please contribute with thoughts on the relevant ticket
