### ISSUE TITLE
Brandon Sabbatical Checklist

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1146]
I'll be on sabbatical from the January 2019 call to mid-May 2019. Some of these require action on behalf of others before they can be closed, so the check boxes below will simply track my own role in the tickets and whether they're finished. 

Tickets - Jekyll repo

- [x] FFMPEG pull request #1145 
- [x] Update publishing guidelines PR #1144 - is just waiting for Spanish translation to be merged. My role in it should be complete at this point. 
- [x] Update publishing guidelines ticket #1137 will be closed with the above PR

Tickets - Submissions repo
- [x] - FFMPEG lesson - https://github.com/programminghistorian/ph-submissions/issues/186. Waiting on one thing from the author to merge and close. 

If there is something else from me that you're waiting on feel free to ping me here or drop it in this comment. I'll take a look to try to see if there is anything else.

**Comment by drjwbaker** [comment]
Have fun sabbaticaling!

**Comment by mdlincoln** [comment]
😭

**Comment by acrymble** [comment]
Let us know if you need any support Brandon!

**Comment by walshbr** [comment]
#1144 and #1137 can be merged and closed once the Spanish team has translated the changes to the guidelines. My role in that PR should be done now. Still feel free to ping me if something comes up with it or anything else, but I'll consider myself sabbatical'ing now. 🎉
