### ISSUE TITLE
February Editorial Agenda - Friday 22 February 2019

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1154]
Friday 22th February 2019. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #1070 French Integration
    - [ ] #1136 Translation Editorial Process - Meeting - outcomes & #1184
- [ ] #1144/ #1137 - Translation for editorial guidelines re: managing editor role
- [ ] update on recruitment sub committee searches
- [ ] #878 Getting a budget line for PH + progress on  #915 #918 #948 
- [ ]  #1018 Community Survey Issue: Website Search 
- [ ] #1186  potential collaboration with Pelagios
- [ ] #1182 Spanish team objectives for this year
- [ ] #1179 Roy Rosenzweig prize
- [ ] #1155 Our next Great Intervention
- [ ] #1183 Restructure as a "Publisher" & "Publications"

**Comment by fdlaramee** [comment]
Apologies; I will be missing this month's call as Feb 22 is my wife's birthday (an important one, arithmetically speaking, with a round number at the end) and we'll be out of town.

Best,
FDL

**Comment by amsichani** [comment]
Minutes of the Φebruary meeting, mainly actions points and decisions made - please amend if I misunderstood or skip smth:

- [ ] #1184 Recruitment of french-speaking reviewers and translators : @programminghistorian/french-team will issue a call (blogpost)  on recruiting reviewers and translators / a series of tasks before this call including translation of the wiki pages, FR managing editor role, translate the opening texts for review tickets - @mpuren to open a ticket on the actions required

- [ ] #1144/ #1137 - Translation for editorial guidelines re: managing editor role : ES & FR translations required 
- [x]  recruitment sub committee searches: @jenniferisasi will open tickets for onboarding ES editors
- [ ]  #878 getting a budget line for PH: @mdlincoln to check with his institution on this
- [x] #1018 Community Survey Issue: Website Search: Freeze dev until May
- [x] #1186  potential collaboration with Pelagios :  @arojascastro to inform the Pelagios team that we are welcome proposals -as -usual on their tools, given that they will have to be compliant with our current guidelines and our peer reviewing process. We need to see beforehand the call they are willing to issue on this.
- [ ] #1182 Spanish team objectives for this year: open for discussion and ideas
- [ ] #1179 Roy Rosenzweig prize  & #1185 British Academy Network grant £25k : they are interesting calls - plz volunteer to lead , esp from @programminghistorian/spanish-team 
- [x] #1155 Our next Great Intervention : open for discussion and ideas
- [x] #1183 Restructure as a "Publisher" & "Publications" :
@all put in this ticket things we think are impacted by this proposed change.
In response to our comments, @acrymble to write a document that outlines in more detail (but not too much!) the new proposed structure so that we can all comment on it.
