### ISSUE TITLE
2019 ES-Team objectives

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1182]
Building from the discussion in #1179 @vgayolrs has suggested that the ES-team needs to discuss some strategic objectives for the project. I've opened this ticket to host those discussions as it is separate from #1179

**Comment by mariajoafana** [comment]
Thanks for opening the ticket Adam.

**Comment by vgayolrs** [comment]
I'm not ignoring the pings. I only fear that I will not be able to participate much in this until the end of March. (I finish classes and leave the position of director of the academic journal of my institution). However, I would like to read proposals for the rest of the team. For now, here are the points to discuss as there were on #1179:

* the commissioning of a report on language interoperability in common DH tools/approaches (using ES as a test language).
* time to research and publish new versions of existing lessons based on emerging ES language data/sources.
* another writing workshop.
* a speaking/engagement tour.

**Comment by arojascastro** [comment]
I think we should schedule a Skype meeting apart from the English team. Creo que deberíamos reunirnos por separado todos los editores, antiguos y nuevos, y hablar sobre el tema. A mí, en concreto, me interesa saber cómo nos posicionamos sobre temas políticos o geopolíticos relativos a la lengua, etc.

**Comment by arojascastro** [comment]
Algunas tareas que podríamos discutir en esa reunión:
- [ ] https://github.com/programminghistorian/jekyll/issues/1232
- [ ] https://github.com/programminghistorian/jekyll/issues/958
- [ ] https://github.com/programminghistorian/jekyll/issues/1199

**Comment by vgayolrs** [comment]
Aparte de las tareas propuestas por @arojascastro , quisiera proponer los siguientes temas para la reunión.

- [ ] seguimiento de la [lista de traducciones](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md).
- [ ] revisión de los tiempos de edición de las traducciones y lecciones. Hay algunos tickets que tienen meses o casi un año abiertos. [Aquí](https://github.com/programminghistorian/ph-submissions/issues/163), [aquí](https://github.com/programminghistorian/ph-submissions/issues/173), o [aquí](https://github.com/programminghistorian/ph-submissions/issues/205).
- [ ] unificar los tickets de revisión según la plantilla correspondiente de [traducción](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-TRADUCCION.md), de [lección recibida](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-LECCION.md) o de [lección propuesta](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-PROPUESTA-LECCION.md). Me parece, incluso, que deberíamos actualizar las plantillas.
- [ ] establecer un "equipo" de enlace con Matt Lincoln para dar seguimiento a la implementación de mejoras que implican traducciones o cambios en las páginas "estáticas" de PH-es (pienso en lo de ORCID, ticket #1258 ) 

Paralelamente a ello, me parece importante discutir:

- [ ] la actualización de las lecciones de Python2 a Python3 discutidas alguna vez en #407 y #408. Esto sería útil porque Python2 es obsoleto. Además, sería necesario buscar la manera de adaptar algunas partes de esas lecciones para que reconozcan caracteres distintos a ASCII ya que al utilizar esta serie con textos en español, las salidas y visualizaciones tienen muchos errores por problemas con la codificación de caracteres.

**Comment by jenniferisasi** [comment]
Víctor, creo que a lo que te refieres con lo siguiente
>  establecer un "equipo" de enlace con Matt Lincoln para dar seguimiento a la implementación de mejoras que implican traducciones o cambios en las páginas "estáticas" de PH-es (pienso en lo de ORCID, ticket #1258 )

Soy yo como parte del Technical Team. Por ejemplo, Matt me menciona en cualquier cosa que tenga que ver con añadir enlaces, arreglar algún archivo, etc.

**Comment by vgayolrs** [comment]
@jenniferisasi , exacto, acabo de hacer la revisión de roles y ya te vi:
> 
> Soy yo como parte del Technical Team. Por ejemplo, Matt me menciona en cualquier cosa que tenga que ver con añadir enlaces, arreglar algún archivo, etc.

Debí decir si necesitas apoyo del resto del equipo.

**Comment by arojascastro** [comment]
Creo que podemos cerrar esto y, si queremos volver a charlar sobre el tema, convocar una reunión en el futuro y crear un ticket con la agenda como hizo Jennifer.
