### ISSUE TITLE
March Editorial Agenda - Friday 29th March 2019

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1196]
Friday 29th March 2019. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #1136 Translation Editorial Process  & #1184 Recruitment of french-speaking reviewers and translators & blogpost in French #1161
- [ ] #878 Getting a budget line for PH + progress on  #915 #918 #948 
- [ ] #1149 Shadowing milestones 
 - [ ] #1182 Spanish team objectives for this year
- [ ] #1179 Roy Rosenzweig prize
- [ ] #1183 Restructure as a "Publisher" & "Publications"
- [ ] #1199 Translators Guidelines & #1189 (FR) #958 (ES)
 - [ ] #1194 Copyediting stylesheet funded - update and further steps also related to #1209
- [ ] #1208 ORCID for contributors 
- [ ] #1215 New Communication Manager needed + Outreach about new lessons to readers #1224

**Comment by vgayolrs** [comment]
I'm sorry, I can not attend. It's my last day of class.

**Comment by jenniferisasi** [comment]
I think, once again, we didn't take into account the time change in the US happened on the 10th but won't happen in Europe till tomorrow... ? So, yes, it's 10AM in US-EST but 8AM in Mex, and 3PM in París and 2PM in London.

**Comment by drjwbaker** [comment]
Saturday night in Europe..

**Comment by amsichani** [comment]
Minutes of the March meeting, mainly actions points and decisions made - please amend if I misunderstood or skip smth:
 - [ ] #721 : this ticket will be now closed as such. It will remain though a regular item on our meetings' agenda. It is suggested to open dedicated tickets for specific research projects/ submissions the team members are working on /

  - [ ] #1184 Recruitment of french-speaking reviewers and translators & #1161 blogpost in French: the FR team is currently having 3 lessons in the pipelines, working mainly with existing (wo)manpower in terms of editing/reviewing. The blogpost is now on its way and it could eventually help the FR team create a pool of potential reviewers .

  - [ ] #878 Getting a budget line for PH : still working on it from the UniSussex front -more updates to follow. Open to other members/institutions.

  - [ ]  #1149 Shadowing milestones: @amsichani to open a wiki page on this. 
The idea of an Onboarding Lead role was proposed, as a way to help new members of the team to navigate through the question " how shall I get involved?"- a new ticket to be opened for this role by @amsichani .

- [ ] #1182 Spanish team objectives for this year : open for ideas/ discussion - to organise a separate ES Skype?

 - [ ] #1179 Roy Rosenzweig prize:the ticket will be closed in next 5 days if no-one wants to own this. @programminghistorian/spanish-team @programminghistorian/french-team 
 go for it ! 

 - [ ]  #1183 Restructure as a "Publisher" & "Publications" : please try to propose *edits* to text of the proposed restructure (which is at #1183 (comment)), either by suggestions for changes to individual lines or new lines, rather than write comment. @amsichani will send a reminder email on it.

 - [ ] #1199 Translators Guidelines & #1189 (FR) #958 (ES): 

- Create a separate, general page with the translation guidelines (separated from author a lesson)
- Create a wiki page with translation tips similar to the translation R for Data Science that @rivaquiroga  coordinates + tips shared between the Spanish and French team.

 - [ ] #1194 Copyediting stylesheet funded : @acrymble will secure an external professional to work on this - please contribute with ideas here #1209

 - [ ]  #1208 ORCID for contributors :waiting for @mdlincoln update on this.

 - [ ]   #1215 New Communication Manager: @jenniferisasi will take this role and form a team with @rivaquiroga . She will also define the role's tasks and responsibilities and manage resources as needed.This new role calls for an update on the team page with the role and its description.
