### ISSUE TITLE
April 2019 Editorial Agenda - Monday 29th April 2019

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1259]
Monday 29th April 2019. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ]  Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #1199 Translators Guidelines & #1189 (FR) #958 (ES)
- [ ] #1183 Restructure as a "Publisher" & "Publications"
- [ ] #878 Getting a budget line for PH - update
- [ ] #1280 replace spanish managing editor
 - [ ] #1194 Copyediting stylesheet funded - update and further steps also related to #1209
- [ ] #1225 #1248 Optimizing website for printing and pdfs 
- [ ] #1179 Roy Rosenzweig prize
- [ ] #1208 ORCID for contributors

**Comment by walshbr** [comment]
This will be the last one I'm out for - I should be back for the May call.

**Comment by drjwbaker** [comment]
Ack. Another call got in there before we confirmed this one. Sorry.

**Comment by arojascastro** [comment]
I cannot make this time  - sorry! I hope someone else from the Spanish team can make it.

**Comment by vgayolrs** [comment]
neither I

**Comment by amsichani** [comment]
Minutes of the March meeting, mainly actions points and decisions made - please amend if I misunderstood or skip smth:


 - [ ] #1199: @jenniferisasi will start working on the English version , then move onto Spanish and French.

  - [ ]  #1183 : @acrymble will create a new ticket with the new team roles  -- please contribute with their short description/responsibilities and  feel free to add your name on (more than one) roles. We then take it from there to restructure our team.

  - [ ] #878: no updates from the USussex front from @drjwbaker .Will need to start exploring alternative routes/institutions. 

  - [ ] #1280 : this will be mainly discussed internally among  @programminghistorian/spanish-team but it might need extra guidance and assistance from the team on how to deal with such situations. @jenniferisasi to circulate an email on this.

 - [ ] #1194 #1209 : @acrymble is awaiting for internal processes but will need to take into account that is a role mainly covering copy-editing issues and not a technical editor tasks.

  - [ ] #1225 #1248: will park them for the moment as @ZoeLeBlanc is dissertating.

 - [ ] #1179 : to explore this idea of NAfrica/Global South further even without this funding option

- [ ]#1208 : @amsichani will update also the editor guidelines regarding the ORCID
