### ISSUE TITLE
April 2019 Spanish-Team Meeting Agenda

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1273]
Date April 15th, Monday. Time is 9:00 AM - Mexico time; 10:00 AM - Chile; 4:00 PM - Spain @     will be facilitating the call.

Working agenda follows, compiled from #1182 and informal chats. Please add by commenting or editing this comment directly: 

- [x] presentación oficial de @rivaquiroga y @JoshuaGOB 
- [x] meses sabáticos para @mariajoafana (a partir de julio, hay que buscar reemplazo como Managing editor)
- [x]  #1232  Solicitudes de lecciones 
- - [x] draft in pull request #1261 to publish in May (cada uno de los miembros escribirá una propuesta)
- [x]  #958 Lenguaje inclusivo en PH-es (@mariajoafana se encarga)
- - [ ]  section or a paragraph with some recommendations in author guidelines? 
- [x]  #1199 Translators Guidelines 
- - [ ] draft in pull request #1260 to publish before the end of April es+en+fr (@jenniferisasi y @rivaquiroga )
- [x] seguimiento de la[ lista de traducciones](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md).
- - [x] responsable de actualización (@arojascastro )
- [x] revisión de los tiempos de edición de las traducciones y lecciones. Hay algunos tickets que tienen meses o casi un año abiertos. [Aquí](https://github.com/programminghistorian/ph-submissions/issues/163), [aquí](https://github.com/programminghistorian/ph-submissions/issues/173), o [aquí](https://github.com/programminghistorian/ph-submissions/issues/205).
- [x] unificación los tickets de revisión según la plantilla correspondiente de [traducción](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-TRADUCCION.md), de [lección recibida](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-LECCION.md) o de [lección propuesta](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-PROPUESTA-LECCION.md). Me parece, incluso, que deberíamos actualizar las plantillas.
- [x] establecer un "equipo" de enlace con Matt Lincoln para dar seguimiento a la implementación de mejoras que implican traducciones o cambios en las páginas "estáticas" de PH-es (pienso en lo de ORCID, ticket #1258 ) --> @jenniferisasi es la contacto

Paralelamente a ello, a @vgayolrs le parece importante discutir:  
- [x] la actualización de las lecciones de Python2 a Python3 discutidas alguna vez en #407 y #408. Esto sería útil porque Python2 es obsoleto. Además, sería necesario buscar la manera de adaptar algunas partes de esas lecciones para que reconozcan caracteres distintos a ASCII ya que al utilizar esta serie con textos en español, las salidas y visualizaciones tienen muchos errores por problemas con la codificación de caracteres.

Añado (@mariajoafana):
-  [x] propuesta de uno de nuestros revisores en [#163](https://github.com/programminghistorian/ph-submissions/issues/163) para actualizar la versión de QGIS de la versión 2.0 a la 3.4. Esto afecta también la traducción [#173](https://github.com/programminghistorian/ph-submissions/issues/173)

**Comment by arojascastro** [comment]
I guess we can close this since we have separated ticket for each task, right?
