### ISSUE TITLE
Maria José Sabattical Checklist

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1279]
I intend to go on Sabbatical from July 2019 until January 2020.

I'll start gathering my checklist of outstanding tickets here and will close them up before I leave

Tickets - jekyll repo

- [ ]  #958 Lenguaje inclusivo en PH-es 
- [x] #1250 - British Academy funding notice on lesson
 
Tickets - submissions repo

- [ ] 163 -  Georeferenciar con QGIS - programminghistorian/ph-submissions#163
- [ ] 188 - Construir un repositorio de fuentes históricas con Omeka Classic /programminghistorian/ph-submissions/issues/188
- [ ] 212 - Introducción a Map Warper programminghistorian/ph-submissions/issues/212

Besides the editorial tasks 
- [x] Paper with @arojascastro and @jenniferisasi for ACH in July 2019

**Comment by acrymble** [comment]
Thanks for letting us know @mariajoafana . Can you start finding a new Spanish Managing Editor to take over in July (a couple of months early)?

**Comment by jenniferisasi** [comment]
Thanks @mariajoafana. I've edited your comment with those check-boxes cos it makes the workflow a bit easier later on. Let us know if you need help with any of these

**Comment by acrymble** [comment]
@mariajoafana do you need any support with this checklist to make sure everything is done on time?

**Comment by amsichani** [comment]
Hi @mariajoafana, just wanted to touch base on where you are in terms of handing over with your open tasks before your sabbatical starts by the end of July -mainly 
#958 
and open submissions #163 #188 #212
Do let us know if you need extra help. Cheers!

**Comment by mariajoafana** [comment]
Hi @amsichani , thanks for checking, I'm actually staying on the role until September and I'm trying to wrap up things before I leave

**Comment by mariajoafana** [comment]
I'm meeting up with @rivaquiroga on Friday to hand her over the Managing editor position and go over the tasks that are still open before I go into the sabbatical

**Comment by mariajoafana** [comment]
I'm committed to keep my role as editor of this tutorial (212 - Introducción a Map Warper programminghistorian/ph-submissions/issues/212 ) while I'm in sabattical between September 2019 and January 2020. 
I'll also revise this one ( 188 - Construir un repositorio de fuentes históricas con Omeka Classic /programminghistorian/ph-submissions/issues/188 ) once the author incorporates the first revisiones.

**Comment by acrymble** [comment]
Are there any outstanding issues here that we need to resolve before you start your sabbatical? Or can we close it?

**Comment by rivaquiroga** [comment]
The only thing pending is on my side, and is to update the roles in the `ph_authors.yml` and in all the pages that are mention here: https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover. I will have that ready by Monday

**Comment by acrymble** [comment]
@rivaquiroga can we close this?

**Comment by rivaquiroga** [comment]
Yes!
