### ISSUE TITLE
May Editorial Agenda - Friday, May 31 2019

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1286]
Date TBD in May 2019. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@walshbr) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] New Editorial Team Roles #1285
- [ ] Replace Spanish Managing Editor #1280
- [ ] Look into setting up a charity #1301 
- [ ] Efficacy of Skype meetings #1302
- [ ] PH Global Divisions #1296
- [ ] Privacy Policy Required #1321
- [ ] Privacy compliance - #1311
- [ ] Web accessibility - #1315 
- [ ] Proposed revision to workflow documentation - #1318 (JB: very brief I promise)
- [ ] Whitelist of Wikipedia linked terms - #1317

**Comment by jenniferisasi** [comment]
Last minute scheduled appointment for tomorrow so, for the first time in many months, I won't be able to make it to the call. I want to leave updates on the agenda above just in case no other Spanish team member joins the call. 

- Submissions Pending about the Programming Historian: 
Antonio and I submitted a paper proposal to HDH conference in Spain and it got accepted. Nomination for an award still pending on response. 
- Replace Spanish Managing Editor: 
So far, we haven't decided on anyone... but Antonio was already managing editor, Victor has two big commitments for the year, Joshua and Riva are too new, and José Antonio hasn't responded. That kind of leaves me as the only option; I will be back in the job market in August, potentially a grant project to complete during the year, couple of conferences, and work, of course. That said, we need someone and I don't want to boat to sink. Now, what is you (all) opinion about one editor holding three positions, cos I'd be communication manager, technical team, and managing editor (it's a bit much, the only solution I can think of is if someone joins me in communication). 

-  Blogpost/Newsletter for June #1288
I am finalizing the text in hopes to publish it on Monday or during that week at the latests. 

I think that is all.

**Comment by walshbr** [comment]
Thanks @jenniferisasi.

**Comment by walshbr** [comment]
Notes and actionables from the call - 

- New Editorial Team Roles #1285 - I'll formally be on the technical team. @drjwbaker will be sitting in but not formally a member. We're going to aim to set in place one of these new teams a month so that we're not doing all at once. We'll open up new tickets for each individual team to that effect. We also suggested year term limits for leadership positions to keep folks from burning out. 
- Replace Spanish Managing Editor #1280 - @jenniferisasi we discussed in the meeting that we were concerned you'd get burnt out taking on so much. @rivaquiroga spoke in the meeting about how she might be able to take over the ME role but had concerns about the workload and also what it would entail exactly. She suggested she might be able to take it over starting in July, but the two of you should probably chat to make sure you're all comfortable with that.
- Look into setting up a charity #1301 - @drjwbaker  has already commented in ticket.
- Efficacy of Skype meetings #1302 - we suggested meeting as a general board every two months with team specific meetings in the intervening months. We won't be able to implement this until later year in the year though - we suggested September. 
- PH Global Divisions #1296 - We'll leave this open for further discussion, but we thought it might make sense to wrangle a team of 3-5 folks committed to being on the global team to carry the conversation further and make decisions. In other words, rather than waiting until we have a decision on this issue to decide what the team will look like we thought it best to assemble the team and have this decision be their first task. 
 - Privacy Policy Required #1321 - @mdlincoln will look again to sign off on the technical description. Then one member in the technical team will implement it. 
 - Privacy compliance - #1311 - this can be closed once we implement #1321
 - Web accessibility - #1315 - @mdlincoln will follow up on this.
 -  Proposed revision to workflow documentation - #1318 - @drjwbaker will get to this in a PR in the next couple weeks.
 - Whitelist of Wikipedia linked terms - #1317 - @mdlincoln will think about this further.
