### ISSUE TITLE
June 2019 Editorial Agenda - 26th June 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1337]
Date 26th June 2019. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. I (@amsichani ) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

All team members, please make an effort to close at least 1 ticket assigned to you.

- [ ] Current Research Projects or Submissions Pending about the Programming Historian.
 - [ ] [New Team Structure Launch](https://github.com/programminghistorian/jekyll/milestone/10)

- - [ ] Editorial Team setup #1328
- - [ ] Global team setup #1329
- - [ ] Project Development team #1330
- - [ ] Communications Team Setup #1327
- - - [ ] Communication: Blogpost/Newsletter for June #1288
- - [ ] Replace Spanish Managing Editor #1280

- [ ] Look into setting up as a legal entity in the UK #1301
- [ ] Efficacy of Skype meetings #1302
- [ ] Proposed revision to workflow documentation - #1318 
- [ ] Privacy Policy Required #1321
- [ ] Web accessibility - #1315 
- [ ] Whitelist of Wikipedia linked terms - #1317

**Comment by drjwbaker** [comment]
I can no longer make this time. But if I have them I will post updates on #1301 in advance.

**Comment by walshbr** [comment]
Oof I think I read the wrong month/week on my calendar. I'll see if I can shift things around make part of this, but I'll be late in either case.

**Comment by spapastamkou** [comment]
Last minute's reschedule of my afternoon with a work meeting I cannot miss: I am afraid I will either miss the meeting or be really really late.

**Comment by mdlincoln** [comment]
Oh dear, I'm sorry to add to the list of people who will be arriving late, but I'm walking from a meeting right before this so will likely arrive 10min late.

**Comment by acrymble** [comment]
For the record we had the following people in attendance:

@amsichani @acrymble @mdlincoln @mpuren @jenniferisasi @walshbr

**Comment by amsichani** [comment]
Notes from the June call -mainly actions points and decisions made - please amend if I misunderstood or skip smth:

 - [ ] #1328 we need to confirm EN managing editor  &team leader 
- [ ] #1329 @JMParr  to set up a Skype call with the team members and proceed on this
- [ ] #1330 pending to fill the 'ticket master' role
- [ ] #1327 the team is up and running 
- [ ] #1288 @jenniferisasi  will draft the blogpost by the end of June
- [ ] #1280 @mariajoafana will stay in the ES managing editor role until Sept 2019 while training @rivaquiroga 
- [ ] #1301 will wait for updates from @drjwbaker  (not in the call)
- [ ] #1318 now into a [PR](https://github.com/programminghistorian/jekyll/pull/1336/files) please come along with comments so we can finalise it in the next couple of weeks  -- Translation into ES and FR at a second stage
- [ ] #1321 [PR](https://github.com/programminghistorian/jekyll/pull/1353) on its way 
- [ ] #1317  on its way thanks to @acrymble -- no need for a separate technical list of terms 

- [ ]  Also during the meeting we agreed to decide wether we ll go for a July or an August -skype free month via a poll. @amsichani will distribute the poll and gather votes in order to set up accordingly the next Skype meeting.
