### ISSUE TITLE
Onboarding Checklist for FR New Editor: Martin 

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1448]
This is an individual onboarding editor checklist for Martin Grandjean @grandjeanmartin, initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). 
Nous te souhaitons la bienvenue! 

We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. 

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@acrymble)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@jenniferisasi)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x] Our Skype group so that you can participate in our monthly calls (@amsichani)
- [x] We will also write a blog post welcoming you publicly to the team.
- [ ] partner you with an existing editor to 'shadow' the editing process so you can get a feel for it.
- [x] schedule a meeting with @spapastamkou to set up a plan for your first 3 months with the  project, providing tangible goals as you begin to adjust to your new role.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @amsichani (mandatory)
- [x] inform @acrymble of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by mdlincoln** [comment]
Welcome @grandjeanmartin !!! 🎊

**Comment by acrymble** [comment]
Bienvenue @grandjeanmartin

**Comment by grandjeanmartin** [comment]
Hello dear friends,
Many thanks for your welcome. I'll immediately write a message on the Google group to say hello.
@amsichani here's my Skype ID: martin.alfred.grandjean 
Best, Martin

**Comment by acrymble** [comment]
@grandjeanmartin @spapastamkou I've added another item to the list. I think it's important that the two of you schedule a meeting to talk about tangible goals for the first 3 months Martin is with us. I think we've not done well at that in the past, so here's a chance to correct that with a new team member.

**Comment by grandjeanmartin** [comment]
@acrymble Good idea, let's schedule something @spapastamkou! (with @fdlaramee i guess?)

**Comment by spapastamkou** [comment]
yes, @grandjeanmartin and @acrymble. We had considered a small concertation with @fdlaramee to have a view what we do but we thought we'd better wait Martin is in. 3 months is a good horizon, I send a doodle  to schedule this.

**Comment by acrymble** [comment]
@grandjeanmartin please try to complete your tasks as soon as possible or let us know if you need support with any of them. We don't expect any of the steps to take very long, but they do make sure you understand how to make technical contributions to the site.

**Comment by grandjeanmartin** [comment]
@acrymble yep, I was waiting our FR meeting this afternoon to complete these tasks in full knowledge of PH processes and culture.

**Comment by grandjeanmartin** [comment]
@jenniferisasi could you please remind me what I'm supposed to do related to the Twitter account/group?

**Comment by jenniferisasi** [comment]
> @jenniferisasi could you please remind me what I'm supposed to do related to the Twitter account/group?
I just added you to our account, @grandjeanmartin. I had an issue the first time (said you had a private account or similar) but it went through this time. Thank you for bringing this task to my attention (memory). 

You should be able to tweet from our account now, for instance, if you publish a blog-post and want to announce it. For published lessons, @spapastamkou has been sending me emails (as I am the communications manager) for me to tweet about them from time to time until they are all incorporated to our twitter bot.

**Comment by spapastamkou** [comment]
I see we are okay with this. Only thing missing is the shadow editing but this could take some time, as it did for all of us. I close this ticket.
