### ISSUE TITLE
September 2019 Skype call - Editorial Agenda, Monday 30th September 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1449]
Monday 30th September 2019 . Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. @amsichani  will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

All team members, please make an effort to close at least 1 ticket assigned to you.

  
- [ ] Current Research Projects or Submissions Pending about the Programming Historian (@drjwbaker  to add note about Archivist role here #1426)
- [ ]   Development Team Report
- [ ]   Technical Report
- [ ]   Communications Report
- [ ]  Global Team Report 
- [ ]   Editorial Team setup #1328
- [ ]   ProgHist Ltd report  (#1403, #1444)
- [ ]   FR team enlargement #1394
- [ ]  ES team Report  -planning #1469
- [ ] Copyediting workflow  #1381
- [ ] Team Survey results (@acrymble)

**Comment by mdlincoln** [comment]
FYI @amsichani the winning day for our #1430 was September 30th at the usual time, and I've gone ahead and scheduled it - is that going to be OK based on the doodle responses for the editorial team call?

**Comment by amsichani** [comment]
Hi @mdlincoln thanks for letting me know (I haven't receive a doodle for the TechMeeting;-). Probably we ll go with the 2nd most popular choice here.

**Comment by mdlincoln** [comment]
🤦‍♂  or... I misread my long list of doodle polls and thought that your poll was the tech poll haha. Belay that... I'll send another one shortly! Looks like YOU get to have monday after all!

**Comment by drjwbaker** [comment]
# Project Development Team Report

By: @drjwbaker 
Date: 27 Sept 2019

Actions Completed Since Previous Report:

- made this template for reporting to monthly calls https://github.com/programminghistorian/jekyll/issues/1432
- incorporated as a legal entity https://github.com/programminghistorian/jekyll/issues/1437 and added explainers on the the site https://github.com/programminghistorian/jekyll/issues/1442 (thanks to ES and FR teams for their efforts here). Company begins operating on 1 October 2019.
- opened a bank account https://github.com/programminghistorian/jekyll/issues/1440 Will close issues once login details are confirmed.
- interviews for English ME role.

Actions Remaining Open Since Previous Report:

- a number of open issues arising from https://github.com/programminghistorian/jekyll/issues/1437 many of which will be resolved after ProgHist Ltd Board of Directors meeting 3 October https://github.com/programminghistorian/jekyll/issues/1439
- agreeing mechanisms for requesting translation that replace our current ad-hoc system https://github.com/programminghistorian/jekyll/issues/1458 (nearly done)

Queries for the Team:

- none

6-month focus:

- getting mechanisms in place for receiving money https://github.com/programminghistorian/jekyll/issues/1457 including reopening conversations around sponsorship and other revenue generating activities (e.g. paid workshops)

12+ month focus:

- understanding forward financial planning so that we can plan spending and hire staff.

Further Comments:

- none

**Comment by mdlincoln** [comment]
# Tech Team Report

By: @mdlincoln  
Date: 27 Sept 2019

Actions Completed Since Previous Report:

- Broke down #1324 into sub-units of work divided across the team

Actions Remaining Open Since Previous Report:

- Website search #1018 will be discussed at November meeting with presentation by @ZoeLeBlanc 
- Small addition to footer #1224

Queries for the Team:

- Re: #1458 IT is possible to make PR reviews even more stringent, such that ALL requested reviewers must approve it before it can be merged. Helpful, or annoying?

6-month focus:

- Get entire team up to speed on making minor-to-medium technical changes
- Website search #1018 

12+ month focus:

- Plan S / DOIs again #1370 

Further Comments:

- Next tech team meeting October 9

**Comment by amsichani** [comment]
Many thanks @drjwbaker and @mdlincoln for these reports ! May I ask also @jenniferisasi to briefly report on Comms, @JMParr on Global and @spapastamkou on the FR front before our meeting (following this template https://github.com/programminghistorian/jekyll/wiki/Meeting-Report-Template)? Thanks!

**Comment by jenniferisasi** [comment]
# Communications Team Report
By: @jenniferisasi 
Date: 29 Sept 2019

Actions Completed Since Previous Report:

- Completed #1456 as a continuation of the short-term plan to keep users informed
- Published note on @grandjeanmartin joining the team (by @spapastamkou) 
- Publicized search for editorial membres for PH en français on Twitter
- Decided to add a footer for RSS feed #1224; project opened by @mdlincoln 

Actions Remaining Open Since Previous Report:
- Establish a long term plan for the Communications Team 
- Community Survey Issue: Audience and Learning Paths #1022 for @amsichani 

Queries for the Team:
- Can we have an issue open for the newsletter in between publications for people to add accomplishments? For example, once I close #1456 I open a new issue till December. 

6-month focus:
- Create a plan by/for @amsichani as Education Manager
- Get a Research Impact Manager and create a plan for him/her (awaiting decision at @drjwbaker's institution)

12+ month focus:
- Have a newsletter out every 3 months 
- Increase visibility of PH in educational settings

Further Comments:

**Comment by spapastamkou** [comment]
# FR team Report
By: @spapastamkou Date: 30/09/2019

Actions Completed Since Previous Report: 

- Fr team enlargement (#1394):  @grandjeanmartin joined the team (welcome blogpost published; onboarding checklist in progress #1448; 3 months task planning #1469)
- Translated pages in FR: translator guidelines (#1389); privacy policy (#1359) @fdlaramee
- 1 translated lesson published: Comprendre les pages web 

Actions Remaining Open Since Previous Report:

- Fr team enlargement (#1394): open call for new members in progress (blog post published, deadline 10 October, 2 candidatures received up to now) 
- FR lessons request page: #1431 
- Twitter Bot and FR lessons: #1167 (in progress, as we wait for a 6th translated lesson to be published until we can feed the gsheet)
- 2 translated lessons under edition/soon to be edited: ```ph-submissions``` issues #263, #264 @fdlaramee @spapastamkou
- 1 translation in progress: ```ph-submissions``` issue #262 @grandjeanmartin

Queries for the Editorial Board:
Reminder: the question of shadow editing remains open for both @fdlaramee and @grandjeanmartin.

6-month focus: 
- 3 months planning for all FR team members, see #1469
- Participate to the DH francophone conference in May 2020 in Bordeaux, France (no cfp published yet).

12+ month focus: 
- Publish original lessons in FR

Further Comments:
- Marie Puren left the team.

**Comment by spapastamkou** [comment]
I am likely to miss today's meeting after all, because I might still be in public transports around that time (I need to leave work earlier). If it is the case, I apologize in advance. I just left a report on our activities and @fdlaramee and @grandjeanmartin can provide further info on these.

**Comment by rivaquiroga** [comment]
# ES team Report
By: @rivaquiroga Date: 30/09/2019

Actions Completed Since Previous Report: 

- María José's Sabbatical checklist completed (https://github.com/programminghistorian/jekyll/issues/1279) @mariajoafana @rivaquiroga 
- Translated pages in ES: privacy policy (https://github.com/programminghistorian/jekyll/issues/1360) @jenniferisasi


Actions Remaining Open Since Previous Report:

- 3 original lessons under edition ([#188](https://github.com/programminghistorian/ph-submissions/issues/188), [#212](https://github.com/programminghistorian/ph-submissions/issues/212) & [#254](https://github.com/programminghistorian/ph-submissions/issues/254)) @jamotilla @mariajoafana @jenniferisasi 
- 3 translations under review ([#163](https://github.com/programminghistorian/ph-submissions/issues/163), [#173](https://github.com/programminghistorian/ph-submissions/issues/173), [#205](https://github.com/programminghistorian/ph-submissions/issues/205)) @jamotilla @vgayolrs 
- Finding a new Ombudsperson (#443) @rivaquiroga
- @JoshuaGOB & @rivaquiroga shadowing @walshbr on [#251](https://github.com/programminghistorian/ph-submissions/issues/251) as part of their onboarding process. The lesson is soon to start the reviewing process.
- Publish Translation Guidelines (https://github.com/programminghistorian/jekyll/issues/1424) @rivaquiroga
- Follow up with Bogotá Workshop participants to inquire about their tutorials @rivaquiroga 

Queries for the Editorial Board:

6-month focus: 
- 3 months planning as team and for all members, following the model of FR team  #1469

12+ month focus: 
- Will be defined after next team meeting

Further Comments:
- María José Afanador started her sabbatical this month. She will keep her rol as an Editor for the two open tickets she was working on (/programminghistorian/ph-submissions/issues/188 & programminghistorian/ph-submissions/issues/212) 
- @rivaquiroga started as Managing Editor of the ES team this month.
- Next team meeting should take place during October

**Comment by JMParr** [comment]
Global Team:

I have created a Wiki page for our Global Team, and have been working on a
list of contacts. I plan to reach out shortly to the other members of The
Global Team for assistance in making contact. (Separately, are there any
team members who speak Italian? I know a little, but I'm very rusty.)

I have also spoken to my colleague who has been working in Rwanda about the
possibility of working on a grant to do a DH workshop there. She hasn't had
the bandwidth to discuss either logistics or grant writing further, but I
hope to have a conversation later this spring.

Finally, I will be sending out an email to the Global Team members later
this week, about arranging our quarterly call later this week.

**Comment by drjwbaker** [comment]
Thinking about this meeting, I guess we need to get used to thinking about what we want to put in the 'Queries for the Editorial Board' bit of the template rather than - as we had previous - going through by open ticket that needs Editorial Board input. Our meetings should be room for reporting *and* discussing (as we did on the copy editing issue).

**Comment by amsichani** [comment]
Notes from the September call -mainly actions points and decisions made - please amend if I misunderstood or skip smth (I hope these notes work well with the new team/call's structure) :


 ## Current Research Projects or Submissions Pending about the Programming Historian
- @acrymble and @mariajoafana will publish a book chapter on PH 
- @acrymble and @rivaquiroga will work and @drjwbaker (via Sussex) will help submit the BA bid for PH workshops in Mexico and South Africa.
 
**Tasks**
 - [ ]  #1426 @drjwbaker , as part of his Archivist role, will keep all PH-related documents in an offline space, with a publicly accessible registry of all the files, and then providing access to them upon request via email. Please provide him with any documentation (bids, applications etc) that need to be archives. 

 ## Development Team Report 

 **Tasks**
- [ ]  a number of open issues arising from #1437 many of which will be resolved after ProgHist Ltd Board of Directors meeting 3 October #1439 
- [ ]  #1457 Donation mechanism needs to be in place
- [ ]   #1477 Personal Project Plans: as a result of the team survey, and in order to help people devise plans for their project involvement on an ongoing basis, @acrymble suggested that we first trial this on a voluntary basis before rolling it out to the whole team. This would involve having an informal meeting with @acrymble  to discuss and then record your project goals for the next 3, 6, and 12 months. Whether these personal plans are public or private, needs to be decided by the team. Drop @acrymble a line if you are interested 

##  Technical Report

**Decisions**
- Re: #1458 , PR reviews even more stringent - requested reviewers must approve it before it can be merged. Also the person proposing the PR is also able to merge it, once approved.
 
**Tasks**
- Next tech team meeting October 9
- Update from Py2 to Py3 #1460 still needs to be explored
-GitHub Desktop retirement and implications #1466 need to be assessed.

##  Communications Report

**Tasks**
- establish a long term plan for the Communications Team 
- keep an issue open for the newsletter in between publications for people to add accomplishments - @jenniferisasi to open a new ticket for next newsletter
- plan for Education Manager @amsichani /  ensure the role of Research Impact Manager

## FR team Report

**Tasks**
- [ ]  @fdlaramee will shadow @amsichani on [#258] as part of his onboarding process. The lesson is soon to start the reviewing process.


 ## ES team Report

**Tasks**
- [ ] PH-ES 3M Planning 

## Global Team

**Tasks**
- [ ] arrange a meeting date with the team 

## Editorial Team setup

**Task**
 - [ ] Sarah Melton (@svmelton) has been appointed as EN Managing Editor. Assist her with her onboarding list is up #1473


- [ ] #1381 Copyediting workflow : After discussion we decided to hold on the idea of charging for copy editing while we discuss business model options. There was concerns about the possible arbitrary nature of the decision (mainly related to authors' academic status/resources and the clash with our inclusivity policy), and the potential for a surprise cost late in the workflow. It was acknowledged that copy editing does have a cost to the project and must be accounted for.

   **Decisions**
We agreed that editors will make a concerted effort to ensure that authors follow the new style guidelines, and that managing editors are empowered to send lessons back that in their opinion to not substantially meet the spirit of the guidelines.
