### ISSUE TITLE
Onboarding Checklist for new English ME: Sarah Melton

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1473]
**Welcome**

Welcome to the Programming Historian Editorial Board. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.
What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@acrymble)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@jenniferisasi)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x] Our Skype group so that you can participate in our monthly calls (@amsichani)
- [ ] We will also write a blog post welcoming you publicly to the team.
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project (@alsalin).

**What you should do**

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:
communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @amsichani (mandatory)
- [x] inform @acrymble of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

**technical**

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.
- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

**The Culture of the Project**

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by svmelton** [comment]
Greetings! Thanks so much for the welcome and the detailed checklist. Here's my info:

- GH: svmelton (@mdlincoln) 
- Twitter: WorldCatLady
- Skype: svmelton (@amsichani)
- Email: sarah.melton@bc.edu should work as a Google-activated email, but you can use sarah.melton1@gmail.com as a backup if needed. (@acrymble)  

I'll write an email to the group shortly. Thanks, all!

**Comment by acrymble** [comment]
Hi @svmelton I have added you to the google group email lists and to Google analytis. Let me know if you want a tour of either.

**Comment by acrymble** [comment]
@alsalin can I suggest you liase with @svmelton to start talking about handover procedures?

**Comment by alsalin** [comment]
@acrymble we're on it! @svmelton will be shadowing me this month and into November as opportunities to learn the role become available (like publication of lessons, for example). We are also working on solutions to the ME-EN editorial team communication/lesson transparency issue.

**Comment by acrymble** [comment]
Just a reminder to @mdlincoln and @amsichani that you have outstanding actions on this ticket.

**Comment by acrymble** [comment]
@svmelton if you're ready (or need help), it would be great for you to add yourself to the Project Team page. This is a good way to practice the technical skills part of working with github.

**Comment by alsalin** [comment]
@svmelton will be taking over starting on 11/8 - we'll submit a PR to get her name up on the site at that time.

**Comment by amsichani** [comment]
It will be good to write a blog welcoming @svmelton to the project - @programminghistorian/project-team & @jenniferisasi (we need a handler for comms team ) perhaps starting working on this?

**Comment by acrymble** [comment]
I think we need to get that handover pull request done so that @svmelton becomes the ME contact on the site.
