### ISSUE TITLE
October 2019 Skype call - 1 November 2019 - Editorial Agenda 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1483]
Friday 1st November 2019 . Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. @amsichani  will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

All team leaders please post a small report on your team's activities closer that day. 

- [ ] Current Research Projects or Submissions Pending about the Programming Historian 
- [ ]   Development Team Report
- [ ]   Technical Report
- [ ]   Communications Report
- [ ]  Global Team Report 
- [ ]   Editorial Team setup #1328
- [ ]   ProgHist Ltd report  (#1403, #1444)
- [ ]   FR team Report #1394
- [ ]  ES team Report  -planning #1469
- [ ] Internal Communications #1491 
- [ ] What business models are we happy with? #1487
- [ ] Proposal for donation implementation #1503

**Comment by drjwbaker** [comment]
@amsichani This is just after the clocks change in the UK. Without wishing to doubt you, has that been factored in?

**Comment by jenniferisasi** [comment]
> @amsichani This is just after the clocks change in the UK. Without wishing to doubt you, has that been factored in?

Good catch! We always fail to realize until a few minutes before the call. Time doesn't change in the US till November 3rd. Mexico would have already changed it, I think Colombia's doesn't change, and Chile...changed it in early Sept
<img width="772" alt="Screen Shot 2019-10-10 at 12 23 54 PM" src="https://user-images.githubusercontent.com/11022533/66591591-e26db200-eb58-11e9-9711-7f7fa151097a.png">

**Comment by amsichani** [comment]
excellent catch ! I will update the times, please amend if necessary, clock change is not my forte.

**Comment by amsichani** [comment]
So from what I can see, our original time slots are still valid @jenniferisasi ? how about EST?

**Comment by amsichani** [comment]
Hi , can I ask all team leaders @drjwbaker @jenniferisasi  @mdlincoln @spapastamkou @rivaquiroga  @JMParr to post a small report on your team's activities?

**Comment by drjwbaker** [comment]
Sorry, will do now.

**Comment by drjwbaker** [comment]
# Project Development Team Report

By: @drjwbaker 
Date: 1 Nov 2019

Substantive Actions Completed Since Previous Report:

- a number of open issues arising from https://github.com/programminghistorian/jekyll/issues/1437 many of were resolved after ProgHist Ltd Board of Directors meeting 3 October https://github.com/programminghistorian/jekyll/issues/1439
- agreed mechanisms for requesting translation that replace our current ad-hoc system https://github.com/programminghistorian/jekyll/issues/1458 (**in sum**: `@` team and ME)
- @drjwbaker to manage offline archive of bids, internal surveys et al with a list of documents at `https://github.com/programminghistorian/jekyll/tree/gh-pages/archive` https://github.com/programminghistorian/jekyll/issues/1482
- Supported onboarding of @svmelton into her new role.

Substantive Actions Remaining Open Since Previous Report:

- 2-month funded Impact Manager post (@drjwbaker working through internal paperwork to get job advert out) https://github.com/programminghistorian/jekyll/issues/1489
- Proposal for donation mechanism https://github.com/programminghistorian/jekyll/issues/1457 *to be discussed in specific agenda item*
- Ticket on business models we are happy with for fundraising https://github.com/programminghistorian/jekyll/issues/1487 *to be discussed in specific agenda item*

Queries for the Team:

- none

6-month focus:

- getting mechanisms in place for receiving money https://github.com/programminghistorian/jekyll/issues/1457 including reopening conversations around sponsorship and other revenue generating activities (e.g. paid workshops)

12+ month focus:

- understanding forward financial planning so that we can plan spending and hire staff.

Further Comments:

- none

**Comment by jenniferisasi** [comment]
> So from what I can see, our original time slots are still valid @jenniferisasi ? how about EST?

If you keep London time as time reference (which is fine), only the original times for your side of the team are valid (3pm Brit, 4pm central). For those of us in the US, we have to +1 h to the original times. So it's 10AM in Central time (showed with Austin, TX), 11AM for East time (in Pittsburg, PA); it will be 12PM for Riva.

**Comment by spapastamkou** [comment]
# FR team Report
By: @spapastamkou Date: 01/11/2019

Actions Completed Since Previous Report: 
No, but all of the actions in progress are scheduled to be done by the end of the year.  

Actions Remaining Open Since Previous Report:

- Fr team enlargement: #1394 3 candidatures received, Skype calls scheduled for 1st week of November) 
- FR lessons request page: #1431 No progress since last meeting but scheduled to close within November  
- Twitter Bot and FR lessons: #1167 (in progress, as we wait for a 6th translated lesson to be published until we can feed the gsheet)
- 2 translated lessons are currently edited: ```ph-submissions``` issues #263, #264 @fdlaramee @spapastamkou
-  2 translations in progress: ```ph-submissions``` issues #262 @grandjeanmartin and #267 @spapastamkou Due end November- beginning December

Queries for the Editorial Board:
None

6-month focus: 
- 3 months planning for all FR team members, see #1469
- Propose a PH FR workshop for the DH francophone conference (scheduled in May 2020 in Bordeaux, France), as the cfp for workshops is to be published in February.

12+ month focus: 
- Publish original lessons in FR

Further Comments:
None

**Comment by jenniferisasi** [comment]
# Communication Team Report

By: @jenniferisasi  

> [I've been out for 2 weeks + applying for jobs so not very productive here, sorry]

Date: 1 Nov 2019

Substantive Actions Completed Since Previous Report:
- none

Substantive Actions Remaining Open Since Previous Report:
- internal communication strategy #1491 
- (will open) End of the year newsletter
- Establish a long term plan for the Communications Team
Community Survey Issue: Audience and Learning Paths #1022 for @amsichani

Queries for the Team:
- none

6-month focus:
- Create a plan by/for @amsichani as Education Manager
- Get a Research Impact Manager and create a plan for him/her (awaiting decision at @drjwbaker's institution)

12+ month focus:
- Have a newsletter out every 3 months
- Increase visibility of PH in educational settings

Further Comments:
- none

**Comment by acrymble** [comment]
The draft minutes for the meeting are here: 
[minutes-editorial-01-11-2019.txt](https://github.com/programminghistorian/jekyll/files/3798781/minutes-editorial-01-11-2019.txt)
