### ISSUE TITLE
November Technical Team Call - Monday, November 18th

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1521]
Hi @programminghistorian/technical-team, let's get our November Skype call on the books:

The confirmed date in Monday, November 18th at 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

- [x] Develop prioritization & responsibility plan
- Status check on open tickets:
    - [x] #1324 alt text PR checkup @mdlincoln 
    - [x] #1484 Lesson template adjustments @amsichani 
    - [x] #1224 RSS footer @jenniferisasi
    - [x] #1555 printing suggestion for all languages @jenniferisasi (or other?)
- [x] #1018 Site search report from @ZoeLeBlanc

**Comment by jenniferisasi** [comment]
Waiting on a campus interview just one of those days, so I'll respond as soon as I know about it.

**Comment by mdlincoln** [comment]
@jenniferisasi any updates on a good date? It looks like Monday 18th or Tuesday 19th are our best options so far for the rest of the team? I'd like to finalize this by tomorrow.

**Comment by jenniferisasi** [comment]
> @jenniferisasi any updates on a good date? It looks like Monday 18th or Tuesday 19th are our best options so far for the rest of the team? I'd like to finalize this by tomorrow.

Just added my availability to the doodle, though it won't work for me: I have the campus on the 19th, and flying all morning on the 18th, unfortunately.

**Comment by mdlincoln** [comment]
@jenniferisasi totally understandable! We'll miss you - but good luck with the interview, which sounds much more exciting 🍀 🤞

**Comment by jenniferisasi** [comment]
Thanks! @mdlincoln I'll try to work on #1224 RSS footer at least before the meeting but I can't promise to have it done by then because of all other stuff I have. 
I'll miss chatting with you all.

**Comment by mdlincoln** [comment]
@programminghistorian/technical-team The meeting is confirmed at Monday, November 18th at 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

**Comment by ZoeLeBlanc** [comment]
Sorry I'm running late this morning, so maybe move me to the end of the queue. Please and thanks 🙏

**Comment by walshbr** [comment]
We should also discuss #1549 - re: triaging workflow for technical team tickets.

**Comment by mdlincoln** [comment]
Report:

- The tech team is currently circulating a draft on issue workflows and how we will be handling high complexity feature requests from the full editorial team.
- We are formalizing the use of our slack team as a site to triage tickets and are implementing a pair programming system encouraging less experienced members to lead on standard technical tickets, shadowed by a more experienced member who will provided dedicated support, commit to live chat while solving issue, etc.
- Lengthy discussion of #1018; @ZoeLeBlanc has updated the ticket

Next team meeting will happen in January
