### ISSUE TITLE
January 2020 Skype call -Friday 31st January- Project Team Agenda

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1589]
Friday 31st January 2020 . Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. @amsichani  will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

All team leaders please post a small report on your team's activities closer that day. 

- [x] Current Research Projects or Submissions Pending about the Programming Historian 
- [x] Internal Communications #1491 & Decision making #1543
- [x]   Development Team Report
- [x]   Technical Report
- [x]   Communications Report
- [x]  Global Team Report 
- [x]   Editorial Team 
- [x]   ProgHist Ltd report
- [x] EN report - SM
- [x]   FR team Report 
- [x]  ES team Report  
- [x] Edit governance doc to better fit sub-team structure/powers #1543
- [x] Spending prioritisation #1593 
- [x] Business Plan approval #1461
- [x] Stepping Down / Being Stepped Down #1582
- [x] Institutional Partner Programme #1625

**Comment by drjwbaker** [comment]
I should be there.

**Comment by drjwbaker** [comment]
Can we bump #1491 / #1543 to the top so we definitely get to it this time?

**Comment by MaelleAmand** [comment]
I'll be there ! Here is my skype ID:
live:maelle.amand

**Comment by drjwbaker** [comment]
I note that the agenda has mushroomed after we skipped December..

**Comment by drjwbaker** [comment]
# Project Development Team Report

By: @drjwbaker 
Date: 20 Jan 2020

Substantive Actions Completed Since Previous Report:

- plan to manage paid copyediting moved to the wiki https://github.com/programminghistorian/jekyll/wiki/Copyeditors https://github.com/programminghistorian/jekyll/issues/1537 This now moved to a trial on an open ticket https://github.com/programminghistorian/jekyll/issues/1610
- Patreon plan for next 6 months set https://github.com/programminghistorian/jekyll/issues/1554
- Volunteer / supported labels https://github.com/programminghistorian/jekyll/pull/1618
- Started to forward plan our budget

Substantive Actions Remaining Open Since Previous Report:

- 2-month funded Impact Manager post. We hired someone. They start 3 Feb (paperwork nearly complete..). https://github.com/programminghistorian/jekyll/issues/1489
- Sponsor banners https://github.com/programminghistorian/jekyll/pull/1585
- Opened ticket (from discussion at previous call #1491) on editing governance to reflect our team structure **to be discussed today under specific agenda item**
- Suggestion for Institutional Partner Programme **to be discussed today under specific agenda item** https://github.com/programminghistorian/jekyll/issues/1625
- Stepping Down / Being Stepped Down  **to be discussed today under specific agenda item** #1582
- Spending prioritisation **to be discussed today under specific agenda item** #1593
- Business Plan for ProgHist Ltd #1461

Queries for the Team:

- none

6-month focus:

- maturing mechanisms in place for attraction receiving money. Focus on https://github.com/programminghistorian/jekyll/issues/1625

12+ month focus:

- better understanding forward financial planning so that we can plan spending and hire staff.

Further Comments:

- none

**Comment by JMParr** [comment]
Global Team Report
By: @JMParr 
Date: 20 Jan 2020

Actions Completed Since Previous Report:

- Outreach with AMICAL, which is in discussion with their members about potential collaborations with us. They are in the midst of some major programming and will be back in touch next month.

- Outreach with RED HD, which has led to interest in collaboration. I have put them in touch directly with our Spanish team.

- Conversation with the potential Portuguese team, along with @jenniferisasi @svmelton & @rivaquiroga. The conversation was positive, and they asked for some time to discuss amongst themselves. I have just recently followed up.

- Scheduled discussion via Zoom with GO::DH this week.

**6-month focus:**

- Securing collaborations with AMICAL & GO:DH, and hoping to have the Portuguese team onboard within the next few months.

- Seeking funding for DH workshops, pending the outcome of current grant applications.

**Comment by mdlincoln** [comment]
Technical Team Report
By: @mdlincoln 
Date: 21 Jan 2020

Actions Completed Since Previous Report:

- Submitted abstract to DHQ special issue on minimal computing with @jenniferisasi @arojascastro @fdlaramee @svmelton focused on our sociotechnical principles
- Implemented sponsorship banners across site and on lesson pages
- Established a standalone account for Programming Historian on Netlify and set up billing process with @drjwbaker to cover months where our activity exceeds the free allocation supplied by Netlify.
- Implemented blog pagination
- @walshbr drafted new policy for large data uploads #1586 
- @mdlincoln Fixed our current print-styling strategy #1590, which is needlessly prolonging our build time/£€$


6-month focus:

- Completing full text search implementation with @ZoeLeBlanc 
- @amsichani moving ahead on progress indicators for lessons #1525 and estimated duration #1526 
- Monitor DOIs #1370 coordinating with @drjwbaker

**Comment by jenniferisasi** [comment]
## Communications Team Report
By: @jenniferisasi 
Date: 22 January 2020

Actions Completed Since Previous Report:
- End of year newsletter
- Shared plan to enhance PH presence at conferences #1629 (awaiting feedback from team)
- Education Manager @amsichani started work on #1526 and #1525 
- Decide with @acrymble the order to incorporate translations into Patreon #1539 

6-month focus:
- Implement plan to enhance PH presence at conferences and try it 
- Promote Patreon more aggressively? 
- Next Newsletter 
- Overview members of French team and volunteers blogposts

**Comment by amsichani** [comment]
Really appreciated the reports above - can I ask @spapastamkou , @rivaquiroga, @svmelton  and @drjwbaker for a brief report on the FR, ES, EN and Ltd?

**Comment by spapastamkou** [comment]
FR Editorial Team Report
By: @spapastamkou
Date: 2020/01/30

---
### Actions Completed Since Previous Report:

**Translations (2/3 + 1 of a volunteer)**
Analyzing Documents with TF-IDF
Getting Started with Markdown
Generating an Ordered Dataset from an OCR Text File

**Translation editions (2/3)**  
Préserver ses données de recherche
Comprendre les expressions régulières

(Status: Both in PR awaiting for review) 

**Translation reviews (2/2 by all members)**
Préserver ses données de recherche
Comprendre les expressions régulières 

**Other (3/3 + 1)** 
Documented the FR translation guidelines in the wiki
Published lessons request FR page
Created FR Kanban board
Submitted proposal to Humanistica 2020 DH conference on PH FR


### Actions Remaining Open Since Previous Report:

**Translations (1/3)**
From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources 

**Translation editions (1/3)**
 Introduction aux bots Twitter avec Tracery
(status: final checks by Editor in progress - should be ready by mid-February at latest)

---

### Queries for the Editorial Board:

none

---

### 6-month focus:

(Basic elements of the 3M plan that runs from February to April)

**Translations** 
3 with possibility for at least 4

**Translation editions**  

2 (at the moment); also co-assigned to new editors to follow the process

**Translation reviews**
2 (at the moment) 

**Other** 
French copy-editing chart 
Respond to a grant call of the Fonds national Science ouverte France
Workshop or other form of communication around the PH in Humanistice 2020 Conference
Work closer and in time with the Communication Manager to prepare the FR version of the newsletter

### 12+ month focus:

Ideally: integrate new members of other geograhical francophone areas

### Further Comments:

none

**Comment by svmelton** [comment]
### EN Editorial Team Report
By: @svmelton 
Date: 2020/01/30

**Actions Completed Since Previous Report:**

- Recently published: [Introduction to Jupyter Notebooks](https://programminghistorian.org/en/lessons/jupyter-notebooks)

- Almost ready: [Working with Batches of PDF Files](https://github.com/programminghistorian/ph-submissions/issues/258) --> 1st copyedited lesson!

**Issues Still in Process**

- Author is revising [Understanding and Using Common Similarity Measures](https://github.com/programminghistorian/ph-submissions/issues/275)

- Awaiting 2nd reviews on [Running a Collaborative Research Website and Blog with Jekyll and GitHub](https://github.com/programminghistorian/ph-submissions/issues/278) and [Introduction to Geospatial Percent Change Analysis Using R and RStudio](https://github.com/programminghistorian/ph-submissions/issues/260)

- Still stuck on using [sudo](https://github.com/programminghistorian/jekyll/issues/1557)

**6-month focus**

- Identify and mitigate editorial capacity issues

- Identify potential topics for EN solicitations

**Comment by rivaquiroga** [comment]
### ES Editorial Team Report
By: @rivaquiroga  
Date: 2020/01/31

**Actions Completed Since Previous Report:**

- Python lessons updated (2.7 -> 3) + bugs fixed.
- Bogotá participants were contacted. Only two responses.

**New proposals**

- Translation of  "Introduction to MySQL with R". (@JoshuaGOB first lesson as an editor)
- Translation of ""Using Geospatial Data to Inform Historical Research in R". (@rivaquiroga first lesson as an editor)
- Translation of "Building a static website with Jekyll and GitHub Pages". Editor: @jenniferisasi 

**Issues Still in Process**

- Awaiting 2nd reviewers: 
["Introducción a ImagePlot y la visualización de metadatos de colecciones de imágenes"](https://github.com/programminghistorian/ph-submissions/issues/212) (original lesson). Editor: @jenniferisasi  
["Introducción a Map Warper"](https://github.com/programminghistorian/ph-submissions/issues/212) (original lesson). Editor: @arojascastro 

- Author is revising
[" Georeferenciar con QGIS"](https://github.com/programminghistorian/ph-submissions/issues/163) (translation). Editor: @vgayolrs 
["Descarga de múltiples registros mediante cadenas de consultas"](https://github.com/programminghistorian/ph-submissions/issues/205). Editor: @jamotilla 

**3 month focus**
- Two new original lessons published

**6-month focus**
- Develop a Spanish Style Guide

**Currently discusing**
- Candidate for Ombudsperson

**Other comments**
- María José's sabbatical ends on February

**Comment by grandjeanmartin** [comment]
I will not be able to be with you today. I wish you an excellent meeting.

**Comment by arojascastro** [comment]
Sorry I cannot connect today...

**Comment by acrymble** [comment]
The minutes of this meeting were circulated to the team.
