### ISSUE TITLE
February 2020 Technical call - Monday February 17

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1613]
Time to schedule the @programminghistorian/technical-team Skype call for February. Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET.

Day is Monday, February 17th.

## Agenda

- [x] #1525 / #1526  Progress reporting & duration for lesson sequences @amsichani 
- [x] #1571 try out translation tool on ph-submissions? anyone interested?
~- [ ] #1018 Full text search (@ZoeLeBlanc can you report on this please?)~
- [x] #1673 and tutorial on how translation linking works: https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Translation-Links
- [x] #1370 thinking ahead to DOIs (if we have time)

**Comment by mdlincoln** [comment]
Hey @programminghistorian/technical-team looks like the winner is Monday February 17

**Comment by amsichani** [comment]
I might need to leave a bit earlier today so it would be great if we could discuss #1525 first thing, if thats OK.

**Comment by mdlincoln** [comment]
@amsichani OK

**Comment by ZoeLeBlanc** [comment]
@mdlincoln I'm really sorry but I can't make today. I thought my flight was later in the day, but turns out it is midday and so I need to head out for the airport now (kicking myself for not checking this earlier!!). I'll try and get to the search before our next meeting, and maybe you and I can try rescheduling our programming session before then?? Would really appreciate your thoughts on the architecture since you have a million times more experience with Jekyll than me 😅

**Comment by spapastamkou** [comment]
I can take in charge #1571 to try it for my next translation; I schedule this for somewhere in late spring, most probably in April. I'll let you know further details once I see more clearly.

**Comment by mdlincoln** [comment]
- @walshbr will open a new ticket with example of occasional issues with Twitter Bot based on incorrectly-entered data in google sheets. We'll strategize where the best place is to make a fix
- #1525 / #1526 Progress reporting & duration for lesson sequences
    - decided on going for the simple solution for 1525; Anna Maria will ping the group one more time before closing 1526 due to lack of interest
- #1571 try out translation tool on ph-submissions
    - Sofia will have bandwidth to consider this in April
- @mdlincoln is going to follow up one-on-one with @ZoeLeBlanc prior to next meeting to get some progress on FTS
- @programminghistorian/technical-team  will review https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Translation-Links and let me know what clarifications I need to make
- #1370 thinking ahead to DOIs
    - once we have a better idea of how soon we can start implementing DOIs, we will open up a larger project team discussion about finally establishing a formal lesson versioning policy with rules about what changes should trigger a new page/lesson being made, and which are minor enough to be done in-place.
