### ISSUE TITLE
Onboarding Checklist for FR New Editor: Maëlle

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1614]
This is an individual onboarding editor checklist for @MaelleAmand initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Nous te souhaitons la bienvenue, Maëlle!

## Welcome

Welcome to the Programming Historian Editorial Board. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [ ] Our Google Group email so you can communicate with other editors (@acrymble)
- [ ] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@jenniferisasi)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x] Our Skype group so that you can participate in our monthly calls (@amsichani)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [ ] set up a twitter account (optional)
- [x] set up a Skype account and inform @amsichani (mandatory)
- [x] inform @acrymble of your Google-activated email (mandatory)
- [ ] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [ ] contribute to one open ticket on our github repository (mandatory)
- [ ] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [ ] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [ ] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [ ] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [ ] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by grandjeanmartin** [comment]
Bienvenue @MaelleAmand !

**Comment by mdlincoln** [comment]
Welcome @MaelleAmand!

**Comment by amsichani** [comment]
Bienvenue @MaelleAmand ! Looking forward to work with you !

**Comment by jenniferisasi** [comment]
I added @MaelleAmand on Twitter with the same namehandle. If that is incorrect, please let me know.

**Comment by MaelleAmand** [comment]
Merci à tous !!

Thank you so much for this warm welcome !!

I’ve read the to do list and will send you all you need tomorrow !

I wish you a very « programmy » new year.

Best wishes,
Maelle

**Comment by spapastamkou** [comment]
@amsichani : skype id live:maelle.amand

**Comment by acrymble** [comment]
@MaelleAmand can you please let me know your Google enabled email address? Then I can add you to our mailing list. You can send it via @spapastamkou if you want to keep it private.

**Comment by acrymble** [comment]
@MaelleAmand do you need any help with these initial tasks?

**Comment by spapastamkou** [comment]
@MaelleAmand I opened [a ticket](https://github.com/programminghistorian/jekyll/issues/1631) to discuss a matter that is relevant to the FR team, you can participate if you want and thus accomplish the first task of the technical contributions of this ticket.

**Comment by spapastamkou** [comment]
@MaelleAmand y a-t-il quelque chose que tu voudrais qu'on voit ensemble pour avancer avec les tâches, notamment dans la partie technique, de ce ticket et le fermer? On a bien de choses intéressantes pour la suite, mais il faut finir avec cela d'abord:)

**Comment by spapastamkou** [comment]
Chère @MaelleAmand, comme cela fait plusieurs jours que ce ticket est ouvert (normalement cela prend vers les deux semaines) et que les tâches n'avancent pas du tout, je me demande si j'aurais peut-être mal ou pas suffisamment expliqué à propos. Peut-être que la période est mal choisie pour toi pour t'en occuper? 
Ces tâches sont obligatoires pour tous les nouveaux membres et leur intégration dans l'équipe ne peut pas avancer si elles ne sont pas accomplies. Le but est de s'habituer au travail en équipe et saisir la manière dont tourne le projet. Si tu souhaites qu'on en parle, je reste à ta disposition (je serai un peu plus disponible après le 7 février, si besoin de parler par skype par exemple). Merci beaucoup de nous tenir informés.

**Comment by acrymble** [comment]
I suspect she doesn't have github notifications turned on, or that they aren't going to her inbox.

**Comment by spapastamkou** [comment]
@acrymble We also exchanged with @MaelleAmand through skype on 24/01 and sent further explanations on tech tasks by email on 26/01. As this makes a lot of channels, I wonder whether it might not be confusing after all, for a new member. I'll try emailing the link to this ticket so that the discussion is recentered here.

**Comment by spapastamkou** [comment]
It is currently impossible for Maëlle to follow through and join the PH. So I will close this ticket

Please @acrymble @mdlincoln @jenniferisasi and @amsichani consider this for the tasks you have been involved in (access to the googlegroup, github repo, twitter account and skype group).
