### ISSUE TITLE
Onboarding Checklist for FR New Editor: Marie-Christine

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1615]
This is an individual onboarding editor checklist for Marie-Christine Boucher (github username to come) initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Nous te souhaitons la bienvenue, Marie-Christine!

## Welcome

Welcome to the Programming Historian Editorial Board. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@acrymble)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@jenniferisasi)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x] Our Skype group so that you can participate in our monthly calls (@amsichani)
- [x] We will also write a blog post welcoming you publicly to the team.
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @amsichani (mandatory)
- [x] inform @acrymble of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by spapastamkou** [comment]
Memo:
Email with link of this ticket sent 8 January (short of a known gh account) 
Email with further precisions sent 10 January 2020

**Comment by mariechristineb** [comment]
Hello everyone! I'm very glad to be joining the Programming Historian team!

Here are the requested informations (hope I'm posting in the right place):
- GitHub Username (@mdlincoln): mariechristineb
- Twitter handle: @marie_c_boucher
- Skype username (@amsichani): live:boucher_mc 
- Gmail (@acrymble): mc.boucher.de@gmail.com

**Comment by jenniferisasi** [comment]
Thanks @mariechristineb, just added you to our Twitter account.

**Comment by acrymble** [comment]
@spapastamkou are you going to do the 3 month plan with @mariechristineb ?

**Comment by spapastamkou** [comment]
there is a doodle in progress since yesterday (20/01) to see how the FR team will organize its activities for the next months.

**Comment by spapastamkou** [comment]
@mariechristineb there is [a ticket](https://github.com/programminghistorian/jekyll/issues/1631) relevant to the FR team, if you wish to contribute with your views; and after our meeting you could open a ticket [like this](https://github.com/programminghistorian/jekyll/issues/1469) for our 3 months activity planning (you can assign us both to do the follow up). Unless you have other ideas, this could help you finish the tasks of the technical contribution part of this ticket.

**Comment by mariechristineb** [comment]
@spapastamkou Thanks for the tips :) Are we doing the skype call today?

**Comment by spapastamkou** [comment]
@mariechristineb Yes, absolutely for the Skype call. Did you receive my message? @grandjeanmartin @fdlaramee @MaelleAmand

**Comment by spapastamkou** [comment]
thanks for the alert @mariechristineb :-)

**Comment by acrymble** [comment]
@spapastamkou It looks like a blog post is all that's left. Are you happy to do this?

**Comment by spapastamkou** [comment]
I've been waiting to have the bio elements. Maybe you have planned to send them in the coming days, @mariechristineb? Once I have them, I will be happy to write the blog post.

**Comment by mariechristineb** [comment]
Ah, yeah - @spapastamkou I've been meaning to ask about that because I remember seeing a message on that topic and I couldn't figure out where: What kind of bio information do you need? How general vs. detailed should it be?

**Comment by spapastamkou** [comment]
Just sent an email:-) @mariechristineb

**Comment by spapastamkou** [comment]
I will open a pull request for the blogpost from this issue this week and then close this ticket.

**Comment by acrymble** [comment]
I'm going to remove the "blog post" element of this checklist for onboarding, because it's consistently one of the bits that slows the onboarding down, and is covered by @jenniferisasi with her quarterly newsletter, so isn't as necessary anymore. That means we can close this ticket.

**Comment by spapastamkou** [comment]
I had the draft ready and just raised the PR #1665, so all is ok here.
