### ISSUE TITLE
PH-FR 3M Planning 2020/1

### ISSUE THREAD

**Issue by mariechristineb** [programminghistorian/jekyll#1642]
Here is the upcoming FR 3-month plan (February-April): 

### Translations
- [ ] Sustainable Authorship in Plain Text using Pandoc and Markdown (Marie-Christine) (expected end of May) 
- [x] Introduction to Jupyter Noteboks (FDL)
- [ ] From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources (Martin) (left from #1469)
- [x] Setting Up an Integrated Development Environment for Python (Windows) (Sofia)

### Translation editions  
- [x] Débuter avec Markdown (FDL)
- [x] Manipuler les chaînes de caractères avec Python (FDL) 
- [ ] Analyse de documents avec TF-IDF (Sofia) 
- [x] Introduction aux bots Twitter avec Tracery: Sofia (left from #1469, still working on it) - on beginning of May: making extensive and final corrections, there were problems with this lesson - will make an update on the review ticket by May 8 latest, to explaoin my interventions, and publish the lesson)

Note: Marie-Christine will also be co-assigned one translation edition, together with FDL and Sofia, to become familiar with the procedure. 

### Translation reviews
- [x] Manipuler les chaînes de caractères avec Python (Marie-Christine)

### Other 
- [ ] French copy-editing chart (as per #1636) https://programminghistorian.org/en/author-guidelines#step-2-writing-and-formatting-a-new-lesson (remains open)
- [ ] Work on a grant proposal for the PH FR Fonds national Science ouverte France (if eligible) https://www.ouvrirlascience.fr/appel-a-projets-fonds-national-pour-la-science-ouverte/ (Sofia and sollicit views of those who wish in the team)
- [x] Blog post to thank volunteer translators and reviewers, Master TNAH Ecole des chartes as per #1631 (all)
- [x] Prepare translation of the FR version of the PH newsletter together with  @programminghistorian/communication-team (1 volunteer of @programminghistorian/french-team)

**Comment by mariechristineb** [comment]
@spapastamkou Should we transfer the unfinished tasks form the previous 3M plan here and close the older ticket?

**Comment by spapastamkou** [comment]
Thank you @mariechristineb. Let's keep the previous planning ticket open until our forthcoming meeting end of January; we'll be done with all the editions until then (or almost) and we can transfer the rest if any. I'll update in some days and check before closing it.

**Comment by spapastamkou** [comment]
I rename this ticket to know the planning corresponds to the 1st quarter of 2020.  
I just added what remained undone from the previous planning #1469 so that we can close the other ticket.

**Comment by spapastamkou** [comment]
@acrymble This finishes today, actually, as it was from February to April. I need to make some final checks to see where we stand (and finish with at least some points I am on personally) but it is planned for this week.  
We almost finished to define our next one through exchanges by e-mail, as we had bad connexion in our last meeting this week and were not able to finish the day we met.

**Comment by spapastamkou** [comment]
This ticket will be closed by May 8, new ticket no #1762. Some unfinished tasks are transferred in the new ticket, some are being clarified.
