### ISSUE TITLE
Actions Arising from Jan 2020 Project Team meeting

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1657]
- [x] @drjwbaker to update wiki on #1491 and #1543 which is taken as approved.
- [x] @drjwbaker to liase with @mdlincoln on DOIs options
- [x] @drjwbaker to liase with @JMParr re impact manager's role and effect on global team
- [x] @svmelton to take forward suggestion re use of sudo and flagging warnings to users.
- [x] @spapastamkou to liase with @acrymble and @drjwbaker re a bid to support the French Publication from the National Fund for Open Science
- [x] @rivaquiroga to liase with @acrymble re Bogota workshop lessons pipeline
- [x] @rivaquiroga to appoint an ombudsperson for Spanish
- [x] @drjwbaker to update wiki re Spending Prioritisation #1593
- [x] @acrymble to update Business Plan and send copy to @drjwbaker for archiving.
- [x] @acrymble to update wiki re stepping down process  #1582
- [x] @drjwbaker to seek support (reach out please for help) to implement Institutional Partner Programme #1625
- [x] ALL - a new Project Manager at Large is needed. #1650 Anyone interested to contact @acrymble or @amsichani

**Comment by acrymble** [comment]
Thank you everyone for your work on these.
