### ISSUE TITLE
23 March 2020 Skype call - Project Team Agenda

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1661]
23 March 2020 , Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. @amsichani  will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

All team leaders please post a small report on your team's activities closer that day. 

- [x] Current Research Projects or Submissions Pending about the Programming Historian 
- [x] #1657 - outstanding actions from January meeting
- [x] Development Team Report
- [x] Technical Report
- [x] Communications Report
- [x] Global Team Report (lead is on sabbatical)
- [x] ProgHist Ltd report
- [x] EN report - SM
- [x] FR team Report 
- [x] ES team Report  
- [x] #1704 - service agreement between publications & proghist ltd
- [x] #1658 - communicating institutional partnership programme

**Comment by acrymble** [comment]
@amsichani just a reminder we agreed to move these meetings to bi-monthly.

**Comment by amsichani** [comment]
@acrymble I was just changing this

**Comment by jenniferisasi** [comment]
Will add it to my calendar, but wanted to say already that I am not a 100% sure I can make it as I will be only on my second week of my new position.

**Comment by walshbr** [comment]
I can't make this one but will be on the lookout for tasks.

**Comment by arojascastro** [comment]
I cannot make it on this day. Apologies.

**Comment by mariajoafana** [comment]
I'll join the meeting and after this one I'll take over scheduling and running the bi-monthly calls

**Comment by drjwbaker** [comment]
**With apologies I can no longer make the call (our research group brought forward a management meeting as we try to work out how to function in this new locked down world!)**

# Project Development Team Report

By: @drjwbaker 
Date: 20 Mar 2020

Substantive Actions Completed Since Previous Report:

- 2-month funded Impact Manager post. We hired Penny. They started 3 Feb. Will finish end of March. Work going well and report due shortly https://github.com/programminghistorian/jekyll/issues/1489
- Sponsor banners. https://github.com/programminghistorian/jekyll/pull/1585 Implemented. 
- Governance https://github.com/programminghistorian/jekyll/issues/1543 Revisions made to wiki following discussion at last call.
- Institutional Partner Programme https://github.com/programminghistorian/jekyll/issues/1625 We are up and running, have 2 signups, and are working Comms team on comms plan https://github.com/programminghistorian/jekyll/issues/1658
- Stepping Down / Being Stepped Down  #1582 Revisions made to wiki following discussion at last call.
- Spending process and prioritisation #1593 Revisions made to wiki following discussion at last call.
- Business Plan for ProgHist Ltd #1461 First iteration approved and circulated.

Substantive Actions Remaining Open Since Previous Report:

- Various tickets getting the PO team up to speed.
- Some potential grants (Mellon, NEH, FNSO).
- Clarifying relationship between ProgHist Ltd and the Programming Historian https://github.com/programminghistorian/jekyll/issues/1704 (with thanks to @acrymble for revising some inconsistent language on the site).

Queries for the Team:

- how much growth do we put on hold until healthier times emerge? Should we be more risk averse right now?

6-month focus:

- maturing mechanisms in place for receiving money. Focus on https://github.com/programminghistorian/jekyll/issues/1625
- growing IPP
- better understanding forward financial planning so that we can plan spending and hire staff.

12+ month focus:

- have a paid project manager in place (this recommendation will be the substantive outcome of https://github.com/programminghistorian/jekyll/issues/1489)

Further Comments:

- none

**Comment by mdlincoln** [comment]
Technical Team Report

By: @mdlincoln 
Date: 20 Mar 2020

Substantive Actions Completed Since Previous Report:

- With @ZoeLeBlanc settled on a technical architecture for full-text search (#1717 and [search-index](https://github.com/programminghistorian/search-index))
- Refactored translation link generation and created [in-depth documentation](https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Translation-Links)
- Addressed twitter bot bugs @walshbr 
- First option for FTS implemented at #1720

Substantive Actions Remaining Open Since Previous Report:

- Call with @drjwbaker regarding DOIs 2020-03-24
- Final Full-text search interface still to be produced by April

Queries for the Team:


6-month focus:

- FTS
- DOIs

12+ month focus:

- Ensuring Portugese team is supported technically
- Plan for @mdlincoln to retire

**Comment by jenniferisasi** [comment]
Aaaaand here we go again. The US changed time a few days ago so our hours don't align. Would this work? 

<img width="948" alt="Screen Shot 2020-03-20 at 4 36 35 PM" src="https://user-images.githubusercontent.com/11022533/77204368-f8e54580-6ac8-11ea-97d4-5720f582e9de.png">

**Comment by acrymble** [comment]
@amsichani will have to decide the time. Thanks for the warning @jenniferisasi

**Comment by amsichani** [comment]
updated time is  **8:00 AM - Mexico time; 10:00 AM - EST; 2:00 PM - British time; 3:00 PM - CET time.**
 Hope it works --or is it too early for Mexico ? Thanks @jenniferisasi for the heads up!
Also @spapastamkou @jenniferisasi @JMParr @rivaquiroga @svmelton may I ask for a report for your teams?

**Comment by jenniferisasi** [comment]
## Communication Team Report

By: @jenniferisasi 
Date: 22 Mar 2020

Substantive Actions Completed Since Previous Report:
- Temporarily closed plan for promoting PH at conferences
- Agreed to add a Communications tweetflow on our Twitter Bot #1702 (ongoing)
- Closed Plan for promoting PH at conferences given that all are postponed/cancelled until further notice, will re-open #1629

Substantive Actions Remaining Open Since Previous Report:
- Publish first trimester 2020 newsletter #1706 
- Writing tweets in three languages for the Communications tweetflow #1702 
- Split translation concordance into lessons vs. other pages sections #1698 
- Communicating the Institutional Partner Programme #1658 with @drjwbaker 
- Estimated lesson duration  and Progress reporting for Lesson Sequences #1526 #1525 by @amsichani 

Queries for the Team:
- none 

3-month focus:
- Publish mid-year newsletter
- Finish issues above 
- Finalize tweets for Communications and activate them w/ @walshbr

12+ month focus:
- Publish trimester newsletter
- Tweet manually

**Comment by jenniferisasi** [comment]
@mdlincoln did I miss something or did the autocorrect change Portuguese for Polish? 

> 12+ month focus:
> 
> * Ensuring Polish team is supported technically

**Comment by jenniferisasi** [comment]
@arojascastro can you do it now that the meeting is at your 3PM instead of 2?

**Comment by arojascastro** [comment]
@jenniferisasi yes, I can make it tomorrow! Gracias :)

**Comment by JMParr** [comment]
GLOBAL TEAM Report

A lot of our initiatives are on hold because of the COVID-19 pandemic. I am also on a short sabbatical until April 15th, owing to some significant COVID-19 related increases in demands on my time.

We had a team meeting on 14 Feb, which included our new Outreach Manager. We discussed some funding opportunities, as well as how best to target our outreach. We still have not heard back from AMICAL, but @acrymble has been working in his capacity as Development Team Lead to bring the Portuguese Team onboard. We've also been working on developing a set of guidelines to clarify the process for bringing new teams on board, and what our expectations are.

I am unable to make tomorrow's meeting, but should be able to join our next meeting.

**Comment by rivaquiroga** [comment]
## ES Team Report

By: @rivaquiroga  
Date: 22 Mar 2020

**Substantive Actions Completed Since Previous Report:**
- Silvia Gutiérrez joined as Ombudsperson

**Substantive Actions Remaining Open Since Previous Report:**

- *Awaiting for translations/lesson to be submitted* (4)
 "Introduction to MySQL with R", "Using Geospatial Data to Inform Historical Research in R", "Building a static website with Jekyll and GitHub Pages", "Análisis de sentimientos en R con 'syuzhet'"

- *Awaiting 2nd reviewer* (1)
"Introducción a Map Warper" (original lesson). 

- *Author is revising* (2)
"Introducción a ImagePlot y la visualización de metadatos de colecciones de imágenes" (original lesson). 
"Descarga de múltiples registros mediante cadenas de consultas" (translation).

- *Awaiting for bug to be solved for publishing* (1)
"Georeferenciar con QGIS" (translation). 

**Queries to the Editorial Board**
- What can we do to not lose contact with authors of published lessons? (https://github.com/programminghistorian/jekyll/issues/1672)

**3-month focus:**
- Two new original lessons published
- Two translations published
- Develop the Spanish Style Guide

**6-month focus:**
- Have at least one original Spanish lesson translated to English. As soon as the team discusses the implications for our workflow, a ticket will be open to discuss this with the EN team. 

**12+ month focus:**
- At least two more original lessons published
- At least two more original lessons translated to English.

**Further comments:**
- María José is back from her sabbatical

**Comment by spapastamkou** [comment]
Team Name: Editorial French

By: @spapastamkou 
Date: 23/03/2020

---

Actions Completed Since Previous Report:
1 translation accomplished (@fdlaramee)
1 translation review accomplished (@mariechristineb)
2 translated lessons published
FR lessons integrated in the Twitter bot 
Submitted proposal for the 2020 Humanistica conference - proposal accepted - conference cancelled bcz of Covid19 - awaiting for alternative solution 

Actions Remaining Open Since Previous Report:
2 translations in progress
3 translation editions in progress
1 translation edition not started yet (Sofia)
1 grant bid in progress (Sofia)
French copy-editing chart (no progress)

---

**Comment by svmelton** [comment]
English Team Report

By: @svmelton 
Date: 22 Mar 2020

Actions Completed Since Previous Report:

- 1 lesson published: [Working with Batches of PDFs](https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files)

- 1 lesson in copyediting stage ([Understanding and Using Common Similarity Measures](https://github.com/programminghistorian/ph-submissions/issues/275))

- 1 lesson almost ready for copyediting ([Running a Collaborative Research Website](https://github.com/programminghistorian/ph-submissions/issues/278))

- 1 lesson awaiting editor assignment (Automating OCR and Translation with Tesseract)

- EN team members are currently reviewing the proposed service agreement

- As of today, no EN members have asked to take a sabbatical


Actions Remaining Open Since Previous Report:

- [Bug in Georeferencing in QGIS](https://github.com/programminghistorian/jekyll/issues/1672)


3-month focus:

- Recruiting new editors, with an aim to bring on 2

- Working with the new Portuguese team to onboard editors


6-month focus:

- Onboarding new EN editors

**Comment by drjwbaker** [comment]
So much great work at such a difficult time. You are all awesome.

**Comment by arojascastro** [comment]
I am online again... I am talking to you and nobody is answering me :( can you add me to the videochat?

**Comment by jenniferisasi** [comment]
@arojascastro I am calling you but says you are unavailable.

**Comment by arojascastro** [comment]
uhmm weird, this is happening since January... is my contact rojas.castro.antonio@gmail.com? anyway, do not worry, I will just read the reports
