### ISSUE TITLE
Portuguese Title Checklist

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1710]
@JMParr can you help me put together a checklist to make sure we do everything? I'll start it but please edit.

- [x] register an ISSN with the British Library.
- [x] translate all core pages.
- [x] onboard all Portuguese members.
- [x] add all Portuguese members's bios to the PH Project Team page (including a small black and white headshot).
- [x] Select a Portuguese Team Managing Editor (should be prepared to serve at least a year)
- [x] Select a Portuguese Team Ombudsperson (should be prepared to serve at least a year).
- [x] Communicate the Managing Editor and Ombudsperson selections to @acrymble and make sure that they are identified on the website.
- [x] Create a blogpost and tweets to announce the new publication; this will call for translators/reviewers
- [x] provide managing editor training (shadowing) and partner them with an existing managing editor for mentoring.
- [x] provide shadowing opportunities to all incoming editors
- [x] logo for project
- [x] colour-scheme (sympathetic with our existing colour scheme).

**Comment by JMParr** [comment]
I have added the action items I can think of and have added Team Development as a tag.

**Comment by jenniferisasi** [comment]
Though it would be the last thing to do, may I add an item on communication?

**Comment by acrymble** [comment]
Just a note that the managing editor will be Daniel Alves. I will begin the onboarding process slowly in the coming months, to ensure we are not overwhelmed with too much change at once.

**Comment by acrymble** [comment]
It looks like this is just waiting for an ISSN. Whose responsibility is that? @mariajoafana #2019

**Comment by DanielAlvesLABDH** [comment]
@acrymble the ISSN for the Portuguese edition is already on the page.  I think we can close this
