### ISSUE TITLE
Actions Arising from March 2020 Project Team Meeting

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1723]
The following actions arise from the project team meeting. Please tick these off as you complete them:

- [x] @jenniferisasi @rivaquiroga to prioritize Institutional Partnership Programme communication (#1658)
- [x] @mdlincoln @drjwbaker to update team on DOI implementation after meeting with Sussex Library.  (#1683) 
- [x] @mdlincoln to outline a plan for his stepping down, and helping us identify the skills of a suitable replacement (12-month timeline).
- [x] @mdlincoln to appoint a dedicated contact on the technical team for New Publication integration
- [x] @JoshuaGOB to add himself as 'New Publications Manager' on the project team page.
- [x] @programminghistorian/project-team to comment on Approval Process for new Teams (#1718) 
- [x] @spapastamkou @svmelton @rivaquiroga to discuss workflow for translating original Spanish lessons into other languages (#1747)  
- [x] @svmelton to drat text for recruiting new English editors.
- [x] @programminghistorian/project-team to comment on draft service agreement (#1704)

**Comment by acrymble** [comment]
@spapastamkou @svmelton @rivaquiroga to discuss workflow for translating original Spanish lessons into other languages (#1747)

- I believe you've started this conversation. Can we tick this off our list, or is this still something to-do?

**Comment by rivaquiroga** [comment]
Yes!
