### ISSUE TITLE
Identifying Causes of Backlog of old issues

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1756]
We've had a gradual buildup of old issues getting stuck for a wide range of reasons. This is a new problem that is worse than we've experienced so far. In order to make sure it doesn't become endemic, I'm opening this ticket and asking our Project Manager at Large @mariajoafana to help identify causes and also to help people responsible for the tickets to action them and complete the tasks or otherwise ask for the help they need in order to do so.

Some of these are active. Others are not.

- [x] #1018 Full-text search @ZoeLeBlanc 
- [x] #1370 Plan S Implementation @mdlincoln 
- [x] #1525 Progress reporting for Lesson Sequences @amsichani 
- [x] #1571 Proposal for translation tool @spapastamkou @rivaquiroga 
- [x] #1587 Error in Exploring and Analyzing Network Data with Python @svmelton 
- [x] #1633 Anna-Maria's Software Sustainability Institute fellowship - collaboration with PH
- [x] #1635 Spanish Copyediting Setup @acrymble @rivaquiroga 
- [ ] #1636 French Copyediting Setup @acrymble @spapastamkou 
- [x] #1642 PH-FR 3M Planning 2020/1 @spapastamkou 
- [x] #1646 Make a cheat-sheet for editors on escaping quotes / special characters @mdlincoln 
- [x] #1658 Communicating the Institutional Partner Programme @jenniferisasi 
- [x] #1659 FNSO 2019 Call for Funding @spapastamkou 

Please don't regard this as a scolding of any kind, but I would value understanding the reasons some tickets linger and others do not. If it's a matter of not understanding who is responsible for tasks, or forgetting, or not being interested in the task, we really need to know so we can make sure we run efficiently. Thanks everyone.

**Comment by jenniferisasi** [comment]
On #1658 I am collecting the list of emails and should be able to do it on Monday. I was planning on earlier, as other tech tickets I have, but ... work, and emails on Friday don't have the same reception.

**Comment by walshbr** [comment]
#1587 was fixed by a PR - but we forgot to close the issue. I closed it.

**Comment by acrymble** [comment]
I've renamed this ticket to be about 'identifying causes' rather than 'clearing' these tickets. This lets us better understand the sticking points and possible solutions, whether that's forgetting to close a ticket, or having too much one one's plate.

**Comment by mariajoafana** [comment]
All tickets seem to be moving along, I'll recheck today after our meeting

**Comment by acrymble** [comment]
It seems like we've been able to learn a few things @mariajoafana that helps us better understand some of the challenges people face closing tickets.

In addition to your support and suggestions to reduce roles to 2, and possibly to bring in help for diagnosing or assessing bugs, is there anything else we want to know or explore? Or should we close this ticket?

**Comment by acrymble** [comment]
Closing this conversation so we can move ahead with supporting solutions
