### ISSUE TITLE
Matt Lincoln retirement

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1761]
Hi all, I'm starting up this ticket well in advance. As a reminder, I will be stepping down from the project team after we close out the implementation of full-text search and registering DOIs for the project (hopefully complete within the next few months)

My open tickets:

- [x] #1726 - finishing FTS with @ZoeLeBlanc 
- [x] #1205 - getting DOIs to display on article pages
- [x] #1683 - workflow for DOIs
- [x] #1737 - documenting technical considerations for adding new language team

Once these are complete:

Some infrastructure tasks I want to check:

- [ ] hand over Cloudflare website management to another member of the tech team

And then the usual checklist:

- [x] Remove Google Groups access (@jenniferisasi)
- [x] Remove Google Analytics access (@acrymble)
- [x] Remove Github Jekyll access (@mdlincoln)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@jenniferisasi)
- [x] Change team: true to team: false, and add team_end: YYYY to the _data/ph_authors.yml file to remove the person from the Project Team page (@acrymble)
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@acrymble).
- [x] If they hold any other team roles, inform @acrymble that a replacement is needed.
- [x] change shared passwords for any services to maintain account security @acrymble

**Comment by drjwbaker** [comment]
@mdlincoln this is incredibly sad news. Your time, effort, and talent will be sorely missed.

**Comment by mdlincoln** [comment]
@acrymble announced in our technical team meeting just now that @ZoeLeBlanc will be taking over as lead. I'll be updating and reassigning tickets as needed, and start to go through the official list to check off the rest of my retirement.

@ZoeLeBlanc will represent the @programminghistorian/technical-team in the July Meeting.

**Comment by mdlincoln** [comment]
@ZoeLeBlanc @drjwbaker re cloudflare, I think it makes sense to create a free programminghistorian account so that it doesn't need to be managed by a personal account. I'm going to create that now and try to transfer the "ownership" of the site from my account to the central one.

**Comment by acrymble** [comment]
@mdlincoln I don't want to usher you out quicker than you want to go. Do you need access to any of the outstanding services still? Or are you handing in your keys now?

**Comment by mdlincoln** [comment]
Thanks @acrymble but I think my GitHub-based action items are all done. @ZoeLeBlanc and I will coordinate about the cloudflare handoff via slack in the next few days - it's a bit involved but doesn't involve any code changes to the site.

**Comment by acrymble** [comment]
@mdlincoln I've had a look at service integrations and it doesn't look like you had access to any passwords other than Cloudflare. Would you mind taking a quick look at that list and let us know if there were others? I think it's always good practice to change shared passwords when someone steps down, so if you can help us identify those I'd be grateful: https://github.com/programminghistorian/jekyll/wiki/Service-Integrations

**Comment by acrymble** [comment]
@jenniferisasi @drjwbaker just a reminder that you have outstanding actions on this ticket.

**Comment by drjwbaker** [comment]
Sorry. Didn't realise I had so had been deleting notifications. Will do that now.

**Comment by acrymble** [comment]
@ZoeLeBlanc the only outstanding activities involve taking over the github and cloudflare admin from Matt. Are you able to do this? I presume he can't remove himself from github without being able to put someone else in charge?

**Comment by ZoeLeBlanc** [comment]
@acrymble Sorry was sick the last few days! Already have access to Github so I'll remove Matt's access once we finalize the cloudflare transfer (should hopefully be by Friday!) just in case there's any issues.

**Comment by acrymble** [comment]
Is Cloudflare still with Matt or did we take that over? That's the only thing left.

**Comment by ZoeLeBlanc** [comment]
Still need to take it over! I'll message Matt this week.

**Comment by drjwbaker** [comment]
@ZoeLeBlanc now has the shared gmail password. Service integration updated https://github.com/programminghistorian/jekyll/wiki/Service-Integrations

**Comment by ZoeLeBlanc** [comment]
Thanks @drjwbaker! Just tried signing in and it's asking to verify using a phone?? Is that yours @drjwbaker or @acrymble ? Let me know so I can get verified, thanks!!

**Comment by acrymble** [comment]
I think it's mine?

**Comment by ZoeLeBlanc** [comment]
I think my initial request has probably expired. @acrymble can I try again and have you approve the request? Also let me know if you aren't getting the requests. thanks!

**Comment by acrymble** [comment]
@ZoeLeBlanc I haven't received any messages on the phone. You can try again.

**Comment by acrymble** [comment]
@ZoeLeBlanc I approved a suspicious login email so hopefully you can get in now

**Comment by ZoeLeBlanc** [comment]
Thanks @acrymble! Still asking me to verify so going to send you one more request. Sorry for the spam!

**Comment by acrymble** [comment]
@ZoeLeBlanc sorry it's not sending me the text messages. Is there a way I can do whatever you need doing within the account, to resolve the ticket (if not your access?)

**Comment by ZoeLeBlanc** [comment]
That's a great question @acrymble that I'm not sure I can answer yet. My understanding is that we need to both move cloudflare from Matt's personal account to the PH gmail, but then also contact our domain registrar (CHNM) to update our nameservers to point to the correct cloudflare account. I've reached out to Matt to clarify a few things about the process so once I hear from him, I'll let you know if I do absolutely need access to the gmail or if it's something we could coordinate together. Thanks for your help!

**Comment by ZoeLeBlanc** [comment]
Think that we should close out this ticket and make the cloudflare issue a separate ticket since the hold-up is my getting access to the PH gmail account or if @acrymble just takes on migrating cloudflare dns from matt lincoln's personal account to gmu's servers.

**Comment by walshbr** [comment]
I'll close this and open a  separate ticket specific to cloudflare
