### ISSUE TITLE
Sabbatical Checklist for Sofia

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1770]
This ticket will help us track tasks related to @spapastamkou and her various roles while she takes a short sabbatical this summer.

The sabbatical will be from 27 June to 26 July 2020.
@spapastamkou holds the following roles:

- Managing Editor (French @programminghistorian/french-team please be aware)
- Technical Team (@mdlincoln please be aware)
- Global Team (@JMParr please be aware)
- ProgHist Ltd board (@acrymble please be aware)

---

The following tickets are currently assigned to Sofia:

- [ ] Ombudsperson (FR) #1763 
- [x] PH-FR Planning 2020/2 (May-July) #1762 
- [ ] New Translations workflows Spanish >EN, FR > ES, EN #1747 
- [x] Content and Interface accessibility #1743 
- [x] Lessons/translated lessons cost estimation #1721 
- [x] FNSO 2019 Call for Funding #1659 
- [x] French Copyediting Setup #1636 
- [ ] Proposal for translation tool #1571 

The following submission tickets are currently assigned to Sofia either directly or as ME

- [x] Proposition de traducition: Installing Python Modules with Pip
- [ ] Proposition de traduction: Downloading Multiple Records Using Query Strings (in progress and related to #1571)
- [ ] Proposition de traduction: Installer un environnement de developpement pour Python (Linux)
- [x] Proposition de traduction en francais: Sustainable Authorship in Plain Text using Pandoc and Markdown
- [x] Proposition de traduction: Installation de Python sous Windows
- [x] Proposition de traduction en francais: Generating an order dataset from an OCR text file
- [x] Proposition de traduction en francais: Introduction aux carnets Jupyter Notebooks
- [x] Proposition de traduction en francais: Analyse de documents avec TF-IDF
- [ ] Traduction en francaise: De l'hermeneutique aux reseaux
- [x] Relecture de traduction: Introduction aux bots Twitter avec Tracery

@spapastamkou can you please confirm the details are correct here?

**Comment by mdlincoln** [comment]
@spapastamkou I'd prefer to simply close #1571 at this point if you are going to go on sabbatical. You could move it to the old feature request backlog here: https://github.com/programminghistorian/jekyll/wiki/Technical-Team but I don't want "active" tickets hanging open for months when there is not a lot of interest to pursue it

**Comment by acrymble** [comment]
@spapastamkou just to be clear you are not obliged to close or finish all of these open tickets. These just help us manage them or re-assign them while you are away.

**Comment by spapastamkou** [comment]
@mdlincoln This work is combined with [the translation](https://github.com/programminghistorian/ph-submissions/issues/292) I should normally finish by the beginning of July and is part of my [current planning](https://github.com/programminghistorian/jekyll/issues/1762).

**Comment by spapastamkou** [comment]
All checked translation proposals are ready and in the repository: we leave the tickets open until one editor is ready to take them so that we do not forget them. One of them is in my planning foe edition. The last lesson is ready for the pull request but open until 25 May in case there were comments by the reviewers and translator.

**Comment by spapastamkou** [comment]
I add here the ticket #1776: Update Editor Guidelines (doi related).

**Comment by acrymble** [comment]
@spapastamkou it looks to me like everything is in order for your sabbatical, as long as @mariechristineb is on top of any ME duties.

Let me know if you need any help from anyone, and otherwise we'll see you soon.

**Comment by spapastamkou** [comment]
Still have some staff to take care of till then :)

**Comment by spapastamkou** [comment]
Just modified the dates as I am in the middle of treating a second original lesson proposal we received. So will start the sabbatical one week later and return one week later (27 June-26 July).

**Comment by acrymble** [comment]
Just a note to everyone on that @spapastamkou is now on sabbatical for a month. Please direct any relevant correspondence to @mariechristineb or the appropriate team leader.

**Comment by acrymble** [comment]
Welcome back @spapastamkou. We hope you're well rested. I'm sure it will take you some time to get back involved, so I will leave this ticket open for a few days as a reminder of some of the things you may have been working on (or you can close it). A reminder also that we have a team call on 28 July #1788

**Comment by acrymble** [comment]
@spapastamkou I have now closed this ticket but if you need to refer back to it, it is obviously still available here. Let me know if a meeting to discuss anything would be helpful.
