### ISSUE TITLE
Onboarding Checklist for our first Portuguese language publication editor: Daniel 

### ISSUE THREAD

**Issue by JoshuaGOB** [programminghistorian/jekyll#1778]
This is an individual onboarding Managing Editor checklist for Daniel Alves (github username to come) initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Bem-vindo, Daniel!

## Welcome

Welcome to the Programming Historian Editorial Board. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@jenniferisasi)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@jenniferisasi)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [ ] Our Skype group so that you can participate in our monthly calls (@mariajoafana)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @mariajoafana  (mandatory)
- [x] inform @jenniferisasi of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by mdlincoln** [comment]
@JoshuaGOB please remind Daniel to create a github account and let us know the name so we can start to follow through on all these tasks

**Comment by acrymble** [comment]
@JoshuaGOB we normally aim to fully complete this list within 2 weeks. It doesn't look like we've made any progress yet. Is Daniel aware of the checklist?

**Comment by rivaquiroga** [comment]
Yes, he is aware. Last week he told us he expected to start completing the tasks on Friday (29) . We'll check again if he needs any help

**Comment by JoshuaGOB** [comment]
We spoke over email last Thursday and he was wrapping up the semester. He has more time this week and hopefully can get this done. It seems it was a bit premature on my part to start the ticket so this one is on me. 

On Jun 1, 2020, at 11:04, Riva Quiroga <notifications@github.com> wrote:

﻿
Yes, he is aware. Last week he told us he expected to start completing the tasks on Friday (29) . We'll check again if he needs any help

**Comment by DanielAlvesLABDH** [comment]
Dear all, I'm starting now. Please be patient with my rhythm. Thanks for your warm welcome. And thanks for given us the chance to contribute to this great project. I think we will collaborate smoothly. All the best. Daniel

**Comment by DanielAlvesLABDH** [comment]
My Twitter account is @DanielAlvesFCSH
Amazing! Just found out that I have two GitHub accounts. Didn't remember this last one with the same user of my Twitter ;-)

**Comment by acrymble** [comment]
@DanielAlvesLABDH once you have finished the last tasks we can close this ticket. Then we can onboard another Portuguese team member (to keep you company!)

**Comment by DanielAlvesLABDH** [comment]
This process is concluded from my side. I would ask that @daniellesanchesDH (Danielle Sanches) be invited to be the next Portuguese team member for the onboarding process.

**Comment by acrymble** [comment]
@mariajoafana can I just confirm that you have Daniel's skype details so we can close the onboarding process?

**Comment by JoshuaGOB** [comment]
Hi @DanielAlvesLABDH congrats on finishing your on boarding. Would you like to do the onboarding for @daniellesanchesDH ? I’d like to walk you through it so you get that experience as well.

**Comment by DanielAlvesLABDH** [comment]
Great @JoshuaGOB thanks. I would appreciate that. What is the first step?

**Comment by JoshuaGOB** [comment]
Since @DanielAlvesLABDH is in contact here and in the Programming Historian google group I think we can close this and move on to the next team member.
