### ISSUE TITLE
Sabbatical checklist for Anna-Maria

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1782]
I intend to go on a short sabbatical from July until October 2020.

I'll start gathering my checklist of outstanding tickets here and aim to close them up before I leave

I am currently holding the following roles:
Editor (@programminghistorian/english-team please be aware)
Technical Team (@programminghistorian/technical-team  please be aware)
Education manager (@programminghistorian/communication-team please be aware)
ProgHist Ltd board (@acrymble please be aware)

The following tickets are currently assigned to me:

- [x] https://github.com/programminghistorian/jekyll/issues/1767 Lessons' banners layout - review and implementation 

- [ ] https://github.com/programminghistorian/jekyll/issues/1525 Progress reporting for Lesson Sequences (to be passed off to someone else)

- [ ] want to write a small blogpost for these two from a user experience point of view before leaving (not critical at present)

- [x]  https://github.com/programminghistorian/jekyll/issues/1737 Open a wiki page documenting how to start up a new language section

- [ ] https://github.com/programminghistorian/jekyll/issues/1633 Anna-Maria's Software Sustainability Institute fellowship - collaboration with PH (will occur post-sabbatical)

- [x] any urgent Ltd-related issues - I will stay in touch with Ltd during my sabbatical with minimum capacity in joining meetings though

submissions 

- [ ] https://github.com/programminghistorian/ph-submissions/issues/285  Review Ticket: OCR and Machine Translation

**Comment by acrymble** [comment]
@amsichani I would like to suggest that you pass off #1525 to someone else on the @programminghistorian/technical-team before you go on sabbatical. I don't think it helps to have tasks like that hanging over you while you are away.

Since you're busy, I think you could also opt not to write a blog post as you've suggested.

**Comment by amsichani** [comment]
Thats the plan @acrymble , I 've already discussed it with Matt. The blogpost can wait too, if thats OK. Thanks for understanding

**Comment by acrymble** [comment]
Ok based on that it looks like you've finished everything outstanding before your sabbatical begins. So I'll close this ticket and I'm sure we all hope you manage to relax a bit while you're away. We'll see you again soon.
