### ISSUE TITLE
July 28 2020 Skype Call - Project Team Agenda

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1788]
July 28 2020 , Time is 9:00 AM - Mexico, Colombia; 10:00 AM - Ottawa, Philadelphia, Boston; 10:00 AM Chile; 3:00 PM - London; 4:00 PM - Paris and Berlin. @mariajoafana will be facilitating the call.

Working agenda in progress. The time and day will be scheduled within the next couple of weeks. Please add by commenting or editing this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [x] Actions Arising from May 2020 Project Team Meeting #1789  
- [x] Welcome Daniel Alves, Managing editor of the Portuguese Team and the new members!
- [x] ES team Report
- [x] EN report - SM (action carried forward: SM and English team to select new editors from applicants from #1789)
- [x] FR team Report #1762 #1763 
- [x] Portuguese team report: #1778 Update on Portuguese Team onboarding and shadowing practice #1681 #1829 #1830 
- [x] Global Team Report 
- [x] Technical Report & #1761 - Matt Lincoln Retirement #1737 Wiki page-new language section
- [x] Communications Report
- [x] ProgHist Ltd report
- [x] Current Research Projects or Submissions Pending about the Programming Historian
- [x] #1704 - Service agreement between publications & Proghist Ltd
- [x] #1837 2020-2021 Goals
- [x] #1712 Technological resources metric or ratings fro resource intensive lessons
- [x] #1777 & #1817 Debugging for the Python lesson sequence

**Comment by drjwbaker** [comment]
# ProgHist Ltd Report

By: @drjwbaker 
Date: 20 July 2020

Financial Summary:

- Healthy. We've come a long way in 7 months.
- 4x IPP members https://programminghistorian.org/en/support-us#institutional-partner-programme
- Patreon steadily growing https://www.patreon.com/theprogramminghistorian

Substantive Actions Completed Since Previous Report:

- We ran our first AGM https://github.com/programminghistorian/jekyll/issues/1797
- We put in place a policy for closing a line of spending https://github.com/programminghistorian/jekyll/issues/1796

Substantive Actions Remaining Open Since Previous Report (and not on this meeting agenda):

- Plan S Compliance https://github.com/programminghistorian/jekyll/issues/1849 (in short: do we want to make the final bit of effort)
- Bug fixing trial led by @acrymble  https://github.com/programminghistorian/jekyll/issues/1817 (in short: low cost way of taking some burden from MEs/editors)
- Becoming a charity in the UK https://github.com/programminghistorian/jekyll/issues/1671 (in short: going through paperwork, looking to submit in the Autumn)
- ES + FR copyediting. Waiting for MEs to set this up. We have the funds when you are ready.
- Funded project manager. Starting to think about costs, location, job spec.

Queries for the Team:

- reminder of spending requests process https://github.com/programminghistorian/jekyll/wiki/Spending-Requests

6-month focus:

- see Business Plan https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Business-Planning

12+ month focus:

- have a paid project manager in place (this recommendation is the substantive outcome of https://github.com/programminghistorian/jekyll/issues/1489)

Further Comments:

- none

**Comment by rivaquiroga** [comment]
## Spanish Team Report

By: @rivaquiroga 
Date: 27 July 2020

**Substantive Actions Completed Since Previous Report**

- One original lesson from the Bogotá Workshop published: ["Introducción a Map Warper"](https://doi.org/10.46430/phes0048) 
- One translation published: ["Georreferenciar con QGIS"](https://doi.org/10.46430/phes0047)
- One translation ticket archived. 

These three tickets were opened between 2018 and January 2019. Now, we only have tickets opened this year :tada:. 

**Substantive Actions Remaining Open Since Previous Report**

- One original lesson under review (awaiting reviewer)
- Two translations about to start the reviewing process (looking for reviewers). One is a lesson from the Bogotá Workshop that was first published in English
- Proposals: 
    - Two original lessons being developed (submission pending)
    - Two lessons being translated (submission pending)
- Spanish Style Guide under development: https://github.com/programminghistorian/jekyll/pull/1771

**3-month focus**
- Publish Spanish Style Guide
- Separate author & translator guidelines in two different pages.

**6-month focus**
- Start review process of two new original lessons

**12+ month focus**
- At least one original ES lesson translated to English or French

**Comment by jenniferisasi** [comment]
## Comms Team Report

By: @jenniferisasi  
Date: 27 July 2020

**Substantive Actions Completed Since Previous Report**

- 2nd Newsletter of the year published
- Moved lesson-retirement-policy and translation concordance pages to footer
- onboarded new members to comms platforms

**Substantive Actions Remaining Open Since Previous Report**

- Add DOI numbers on lesson header #1860
- UX changes
- Annual statistics on submissions, reviews, approval rate, time from submission to publication #1849

**3-month focus**
- Publish 3rd Newsletter
- Promote PT publication once everything is ready

**6-month focus**

**12+ month focus**

**Comment by JMParr** [comment]
Global Team Report
By: @JMParr 
Date: 27 July 2020

Global initiatives have been delayed due to the unanticipated Pandemic, and the sabbatical of @JMParr due to additional COVID-related demands on teaching, etc.  @JoshuaGOB has been heavily engaged in helping to bring The Portuguese Team on board and get them up to speed. Initiatives have included:

- Discussions about funding, including how the pandemic might impact our desired workshops/programming in West Africa. @spapastamkou has a grant application in.

- @acrymble , @drjwbaker , and @JMParr  made an attempt at funding to build a sustainable model of using DH to train non-academics to code. Unfortunately, the application was not successful.

- @acrymble  has stepped back from The Global Team to focus more on his work with Team Development, etc. @spapastamkou is on sabbatical. With the new Portuguese team now on board, we'd like to recruit a member from that team to work with us on Global Team.

- @JMParr has been researching ways to try to diversify our use of images in our lessons. The goal is to ensure that the PH aesthetic allows for cultural and racial diversity. 

- Propose creating a PH sticker for _The Programming Historian_.

3-month goals:

- New Portuguese team member added to Global Team.
-Consider the ways the pandemic might be impacting Global DH, and see if there are things  PH can do to help support.

6-month goal:

-Develop a list of recommendations re: image use and diversity.
- An initial report on impact of the pandemic.

**Comment by svmelton** [comment]
## EN Team Report

By: @svmelton 
Date: 27 July 2020

**Actions Since Last Report**

- Three new editors will be joining PH English! (Sylvia Fernandez, Alex Wermer-Colan, and Nabeel Siddiqui) The onboarding process will begin in the upcoming weeks.

- One lesson has just passed peer review: [OCR and Machine Translation](https://github.com/programminghistorian/ph-submissions/issues/285)

- One lesson has completed one round of revision: [Crowdsourced Data Cleaning with Python and Pandas](https://github.com/programminghistorian/ph-submissions/issues/301#issuecomment-664571003)

- 2 other lessons have been sent to the editorial team for initial review. Lesson progress can be found on our [publication tracking board](https://github.com/programminghistorian/jekyll/projects/3).

**Outstanding Actions Since Last Report**

- We have not yet been successful in identifying a new ombudsperson, but Sarah is making inquires

**3-month goals**

- Onboarding new editors

- Discussion of a deputy editor

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc 

Date: 28 July 2020

Substantive Actions Completed Since Previous Report:

- #1767  Lessons' banners layout. Completed by @amsichani
- (From our tech team meeting in June and #1787) #1814 Process for Reviewing Internal Technical Documentation. Completed by @walshbr

Substantive Actions Remaining Open Since Previous Report:

- Complete Matt Lincoln's retirement with Cloudflare transfer #1761
- Finalize progress reporting for Lesson Sequences #1525. Now that @amsichani is on sabbatical, @ZoeLeBlanc is looking over code and getting original proposal up to speed with latest codebase
- For PT Technical Onboarding we are waiting for final merges and then adding language stemmer for FTS (see #1802 and #1737 for more discussion)
- For updating guidelines on submitting lessons to PH-Submission we are waiting on PT team to be fully setup #1795 (Three cheers to @walshbr for this much needed update 🎉 !)
- Discuss with the tech team in our next meeting if we want to change Github admin rights to improve onboarding (originating from #1855)

Queries for the Team:

- Do we want to setup password management service like LastPass for security? (Technically would be more secure, but want to get feedback on how useable it would be for everyone)

6-month focus:

- Getting @zoeleblanc up to speed as tech lead and getting rest of team back together after sabbaticals completed
- Support Portuguese team onboarding and any additional new editors that need training

12+ month focus:

- New features?
- Documentation review

**Comment by DanielAlvesLABDH** [comment]
Portuguese Team Report

By: @DanielAlvesLABDH
Date: 28 July 2020

Substantive Actions Completed Since Previous Report

- Three editors have come on board: Aracele, Josir, and Danielle
- We have a logo!
- Began translation on the following pages: Index.md, Lessons.md, Project-team.md, Feedback.md, Contribute.md, Privacy-policy.md, About.md, research.md, reviewer-guidelines.md, support-us.md and Editor-guidelines.md

Substantive Actions Remaining Open Since Previous Report

- Select a new publication Team Ombudsperson
- Submitting: Index.md, Lessons.md, Project-team.md, Feedback.md, Contribute.md, Privacy-policy.md, About.md, research.md, reviewer-guidelines.md, support-us.md and Editor-guidelines.md

3-month focus

- Second round of core pages: topics.yml, Activities.yml, teamroles.yml, snippets.yml, ph_authors.yml
- Translating and uploading the Portuguese version of the PH platform #1818 
- Create a blogpost and tweets to announce the new publication; this will call for translators/reviewers

6-month focus

- Start the translation of at least six lessons from the English originals

12+ month focus

    Finish and publish at least 16 lessons translated from the English originals
    Implement some of the lessons in one graduate course at NOVA-FCSH (Lisbon) and in another graduate course at FGV (Rio de Janeiro)

**Comment by fdlaramee** [comment]
Apologies, I will not be able to attend today's meeting. Best regards, FDL.

**Comment by spapastamkou** [comment]
FR Team Repoty

By: @spapastamkou 
Date: 28/07/20

---

Actions Completed Since Previous Report:

Translations: 3 out 5
Translations Editions: 2 out 4
Translation Reviews: 2 out 5 (1 published and 1 to be published)

Actions Remaining Open Since Previous Report:

Translations: 2 
Translation Editions: 2 
Translation Reviews: 3 

(not really in the privious report):1original lesson proposal is in progress and one more to come

---

Queries for the Editorial Board:
None

---

6-month focus:

- FR copy-editing chart
- We cruelly lack editors! 6 translations are ready and wait to be edited; 1 original lesson soon to be ready as well.

12+ month focus:

New members. 

Further Comments:

**Comment by JoshuaGOB** [comment]
Hi @DanielAlvesLABDH I added some of the items that were scattered in emails and tickets to your report so that we could have them in the same place. Hope that's okay.

**Comment by drjwbaker** [comment]
@DanielAlvesLABDH further to your comment in this meeting, it sounds like there is project/funding support for the PT team. Should this be recognised in our 'Supporters' section? https://programminghistorian.org/en/support-us#supporters (sorry if this has already been covered elsewhere)

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Hi @DanielAlvesLABDH I added some of the items that were scattered in emails and tickets to your report so that we could have them in the same place. Hope that's okay.

That is fine, Perfect! Thanks

**Comment by drjwbaker** [comment]
> Do we want to setup password management service like LastPass for security? (Technically would be more secure, but want to get feedback on how useable it would be for everyone)

@ZoeLeBlanc I use LastPass. And yes, I like this idea. The only issue I find is actually remembering the LastPass password (I keep managing to forget mine......)

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> @DanielAlvesLABDH further to your comment in this meeting, it sounds like there is project/funding support for the PT team. Should this be recognised in our 'Supporters' section? https://programminghistorian.org/en/support-us#supporters (sorry if this has already been covered elsewhere)

Yes, that is something that we plan to do. But the project didn't start yet officially because of the pandemic. Thanks

**Comment by drjwbaker** [comment]
@mariajoafana Now we have SO much amazing going on, and especially with a fourth language team, I'm wondering if we need to make more time to discuss issues that team members think we need time to discuss in a whole team meeting (especially `policy` tickets https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance). This is not a criticism of your chairing, rather I feel like we used to spend more time on 'issues' and hear more people give their opinions, and that we might want to get some of that back (maybe I'm alone in thinking that!).

I have two ideas (but I'm not saying these are the only options!):

1) We alternate between 'reports' and 'issues' meetings. That is, in one meeting we go through reports, then in the next meeting we go through tickets that need discussion, and so on. I think could work only work on a monthly meeting cycle or as a 6-weekly meeting cycle (because otherwise it could be up to 4 months until an issue gets discussed)
2) We keep a mix of reports and tickets in every meeting, but alternate who reports. That is, half the teams report at one meeting and half the teams report at the next. This could work on our current meeting cycle, but might be more confusing to administer.

**Comment by mariajoafana** [comment]
Yes @drjwbaker I agree that is not entirely productive in terms of discussing issues to devote all meetings to go through the reports. We can have each team leader upload their report for every meeting but only go through the report every other meeting. We can try this out in the September call, ask Team leaders to add tickets that need discussion, and then go through the reports again in the November meeting.

**Comment by drjwbaker** [comment]
> Yes @drjwbaker I agree that is not entirely productive in terms of discussing issues to devote all meetings to go through the reports. We can have each team leader upload their report for every meeting but only go through the report every other meeting. We can try this out in the September call, ask Team leaders to add tickets that need discussion, and then go through the reports again in the November meeting.

Fab. So November will be a 'report' focused meeting, is that your meaning?

**Comment by acrymble** [comment]
The minutes/actions have been circulated via Google Groups and have been archived. So will close this ticket now.
