### ISSUE TITLE
Actions Arising - Project Team meeting 28/07/2020

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1868]
The following actions have arisen from the July 2020 Project Team Meeting

- [x] @mariajoafana & @rivaquiroga to draft copyediting ES guide by next meeting #1635 
- [ ] @svmelton to onboard 3 new editors
- [ ] @svmelton to discuss w English team about appointing a deputy editor (@acrymble to support if needed)
- [x] @acrymble to support @spapastamkou on expanding French team capacity
- [x] @DanielAlvesLABDH to report to @JoshuaGOB on the Portuguese team onboarding process, so that we can streamline the process for future teams.
- [x] @drjwbaker to give @ZoeLeBlanc access to Gmail acct so she can take over cloudflare #1761
- [ ] @ZoeLeBlanc to complete Portuguese technical onboarding process #1802
- [x] @walshbr to give @JoshuaGOB admin access to Github for onboarding purposes (already done I think).
- [x] @ZoeLeBlanc @DanielAlvesLABDH @rivaquiroga @spapastamkou to inform @acrymble if they are happy to proceed with the Service Agreement #1703 
- [x] @acrymble to arrange a meeting with team leads @ZoeLeBlanc @jenniferisasi @JMParr on support team goals for the next year. #1837
- [x] @acrymble to recommend to ProgHist that bug trial has been successful #1817
