### ISSUE TITLE
Onboarding Checklist for our Portuguese language publication editor Joana

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#1870]
## This is an individual onboarding Managing Editor checklist for Joana Paulino initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Bem-vinda, Joana!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Google Analytics account for monitoring web traffic (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] Our Skype group so that you can participate in our monthly calls (@JoshuaGOB - who will pass your details on to the relevant team member)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory)
- [x] set up a Skype account and inform @JoshuaGOB (mandatory)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by joanacvp** [comment]
@JoshuaGOB 

- Username on GitHub: @joanacvp
- Skype account: Joana Paulino (joana_paulino40@hotmail.com)
- Google-activated email: jpaulino@fcsh.unl.pt

**Comment by joanacvp** [comment]
I am just finishing the Onboarding process.

**Comment by joanacvp** [comment]
I have already finished all of my tasks. I am just waiting for:
- Skype group @mariajoafana joana_paulino40@hotmail.com
 - Partner with an existing editor to develop a 3 month plan so that you can acclimatise to the project (@JoshuaGOB).
 - Become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project (@acrymble)

**Comment by JoshuaGOB** [comment]
Hi @joanacvp I'm currently working on the shadowing practice during this week and hopefully we can get you assigned soon. Thank you for reminding me.

**Comment by JoshuaGOB** [comment]
Shadowing assigned which closes this ticket
