### ISSUE TITLE
September 2020 Skype Call - Project Team Agenda

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1871]
29 September 2020 , Time is 9:00 AM - Mexico, Colombia; 10:00 AM - Ottawa, Philadelphia, Boston; 11:00 AM Chile; 3:00 PM - London; 4:00 PM - Paris and Berlin. @mariajoafana will be facilitating the call.

Working agenda in progress. The time and day will be scheduled within the next couple of weeks. Please add in these agenda under "Issues and tasks for discussion" the tickets that you'll like to further discuss in the meeting. You can comment or edit this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [x] Actions Arising from July 2020 Project Team Meeting #1868
- Issues and tasks for discussion: 

 - [x] Publisher tasks (includes tasks that concern comm, tech, global, & ProgHist)
    - [x] #1703 - Service Agreement Implementation
    - [x] #1837 - 2020-2021 Goals
    - [x] #1856 - Job description draft 
    - [x] #1867 - PH Sponsored Workshops

- [ ] ES team issues
   - [x] #1695 

- [x] EN issues

- [x] FR team issues 

- [x] Portuguese team issues

**Comment by fdlaramee** [comment]
I will not be able to attend this time. Thanks.

**Comment by drjwbaker** [comment]
# ProgHist Ltd Report

By: @drjwbaker 
Date: 25 September 2020

Financial Summary:

- Remain healthy.
- 5x IPP members (1 more since July) https://programminghistorian.org/en/support-us#institutional-partner-programme
- Patreon steadily growing https://www.patreon.com/theprogramminghistorian

Substantive Actions Completed Since Previous Report:

- Bug fixing now a Ltd supported activity https://github.com/programminghistorian/jekyll/issues/1817
- Made first application to become a charity. This was rejected, but a paper reject rather than saying we aren't charitable. There is some work to fix it, but at least we know what to do https://github.com/programminghistorian/jekyll/issues/1671

Substantive Actions Remaining Open Since Previous Report (and not on this meeting agenda):

- Funded project manager. Led by @acrymble. Ltd providing input re what we can sustainably afford https://github.com/programminghistorian/jekyll/issues/1856
- Plan S Compliance https://github.com/programminghistorian/jekyll/issues/1849 (in short: do we want to make the final bit of effort)
- ES + FR copyediting. Waiting for MEs to set this up. We have the funds when you are ready.

Queries for the Team:

- reminder of spending requests process https://github.com/programminghistorian/jekyll/wiki/Spending-Requests

6-month focus:

- see Business Plan https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Business-Planning

12+ month focus:

- have a paid project manager in place (this recommendation is the substantive outcome of https://github.com/programminghistorian/jekyll/issues/1489)

Further Comments:

- none

**Comment by jenniferisasi** [comment]
# Comms Team Report

By: @jenniferisasi  
Date: 28 September 2020

Financial Summary:

Substantive Actions Completed Since Previous Report:

- Implement DOI number on lesson header (Jennifer) 
- Blogpost for potential IPP members (Adam, consulted w/Jenn)
- Informational material for potential IPP members (Adam, consulted w/Jenn) 
- Tweeted weekly about/looking for Patreon supporters

Substantive Actions Remaining Open Since Previous Report (and not on this meeting agenda):

- Newsletter for 3rd trimester to publish by end of week #1903 
- Paid role proposal design (@acrymble not sure if this goes here)

Queries for the Team:

6-month focus:

- New way of communicating our progress with the public to replace Newsletter (or maybe we don't need one since Twitter works very well; but need something to show IPPs too)

12+ month focus:

- 

Further Comments:

- none

**Comment by rivaquiroga** [comment]
## Spanish Team Report

By: @rivaquiroga 
Date: 28 September 2020

**Substantive Actions Completed Since Previous Report**

- Spanish Style Guide is ready. We will be merging this week :tada:. 

**Substantive Actions Remaining Open Since Previous Report**

- One original lesson under review 
- One original lesson about to start the reviewing process
- Three translations under review

**3-month focus**
- Publish first copy edited lesson.
- Separate author & translator guidelines in two different pages.
- Run online Python workshop

**6-month focus**
- Start review process of one original lesson

**12+ month focus**
- At least one original ES lesson translated to English or French

Further Comments:
- For the online workshop, we will ask for a voluntary contribution from participants.

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc 

Date: 28 September 2020

Substantive Actions Completed Since Previous Report:

- #1525 Lesson sequence reporting. Completed by @amsichani and @ZoeLeBlanc 
- #1802 Added full text stemming support to search and code for project loop (ticket is still technically open until PT code is live). Completed by @ZoeLeBlanc and @acrymble respectively

Substantive Actions Remaining Open Since Previous Report:

- Complete Matt Lincoln's retirement with Cloudflare transfer #1761. Essentially Zoe can't get access to PH gmail inbox so recommend separating this out as an individual issue and closing the rest of the ticket. 
- For updating guidelines on submitting lessons to PH-Submission we are waiting on PT team to be fully setup #1795 (will discuss in our next tech team meeting)
- #1737 not sure if there's much remaining work for the technical team (seems like remaining part is requesting new DOIs https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Setting-Up-a-New-Language#ask-drjwbaker-on-behalf-of-the-ltd-to-check-with-the-doi-provider-that-they-are-happy-provide-dois-for-a-new-publication-if-the-provider-cannot-supply-dois-the-new-publication-will-run-without-dois-until-the-ltd-finds-a-solution)


6-month focus:

- Tech team meeting in October to discuss goals and maintenance for the next few months. Review https://github.com/programminghistorian/jekyll/wiki/Technical-Team#new-feature-backlog to see if we want to undertake any particular feature
- Help support Portuguese team onboarding and any additional new editors that need training

12+ month focus:

- New features?
- Documentation review

**Comment by spapastamkou** [comment]
## FR Team Report

By: @spapastamkou 
Date: 29/09/20

---

Actions Completed Since Previous Report:

Translations: none from the team members (we have a good stock of non yet edited translations) - 1 external in progress
Translation Reviews: 1 (published)

Actions Remaining Open Since Previous Report:

Original lesson proposal: 1 new
Translation Reviews: 2 in progress
FR copy-editing chart (not started)
1 translation that was associated with a translation tool test (Sofia) - in standby currently

---

Queries for the Editorial Board:
None

---

6-month focus:

- FR copy-editing chart
- Integration of 2 members

12+ month focus:

Have our original lessons translated to EN and/or ES.

**Comment by DanielAlvesLABDH** [comment]
## Portuguese Team Report

By: @DanielAlvesLABDH 
Date: 29 September 2020

**Substantive Actions Completed Since Previous Report**

- Onboarding for Joana Paulino and Danielle Sanches
- Chosing the PT ombudsperson (Luís Ferla from Unifesp, Brazil)  

**Substantive Actions Remaining Open Since Previous Report**

- Translation of the PT platform (will finish this week)

**3-month focus**
- Uploading the Portuguese version of the PH platform #1818
- Create a blogpost and tweets to announce the new publication
- Round table to present and discuss the impact of the "Programming Historian in Portuguese" in the online event "I JORNADA NACIONAL DE HUMANIDADES DIGITAIS", organized by IBICT, Brazil (October 13th)
- Onboarding of the two remaining editors of the PT team (Jimmy and Ricardo)
- Start the translation of at least 3 lessons from the English originals

**6-month focus**
- Start the translation of at least 6 lessons from the English originals

**12+ month focus**
- Finish and publish at least 16 lessons translated from the English originals
- Implement some of the lessons in one graduate course at NOVA-FCSH (Lisbon) and in another graduate course at FGV (Rio de Janeiro)

**Comment by svmelton** [comment]
## English Team Report

By: @svmelton 
Date: 29 September 2020

**Substantive Actions Completed Since Previous Report**

- [1 lesson](https://github.com/programminghistorian/ph-submissions/issues/285) ready for copyedits
- [1 lesson](https://github.com/programminghistorian/ph-submissions/issues/278) ready for final editor's review
- Ian Milligan has joined as the English ombudsperson
- Marie-Christine has begun to work on our identified bugs


**Substantive Actions Remaining Open Since Previous Report**

- Onboarding of new editors has begun, final step is lesson shadowing
- Discussion of deputy editor is still outstanding


**3-month focus**

- Complete onboarding
- Publish 2 lessons

**6-month focus**

- Identify and onboard deputy editor

**Comment by drjwbaker** [comment]
> ## Spanish Team Report
>
>     * Run online Python workshop
>     * For the online workshop, we will ask for a voluntary contribution from participants.

@rivaquiroga Are these related to https://github.com/programminghistorian/jekyll/issues/1867?

**Comment by drjwbaker** [comment]
This meeting format worked really well. Bravo @mariajoafana.

**Comment by rivaquiroga** [comment]
> > ## Spanish Team Report
> > ```
> > * Run online Python workshop
> > * For the online workshop, we will ask for a voluntary contribution from participants.
> > ```
> 
> @rivaquiroga Are these related to #1867?

Yes, @drjwbaker
