### ISSUE TITLE
Onboarding Checklist for New EN Editor Sylvia

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1872]
## This is an individual onboarding checklist for Sylvia initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Welcome, Sylvia!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Google Analytics account for monitoring web traffic (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] Our Skype group so that you can participate in our monthly calls (@JoshuaGOB - who will pass your details on to the relevant team member)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@svmelton)
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project. (@acrymble)

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by sferna109** [comment]
Hi @JoshuaGOB  here is the information requested:
1.Github account: sferna109 (https://github.com/sferna109)
2.Twitter account: sferna109 (https://twitter.com/sferna109)
3. Skype account: sferna4
4. Google activated email: sferna109@gmail.com

**Comment by mariajoafana** [comment]
Welcome to the team @sferna109 ! I just added you to our Skype account

**Comment by acrymble** [comment]
@sferna109 as you complete the tasks, please check them off for us in the ticket.

**Comment by acrymble** [comment]
@sferna109 please email me at a.crymble@ucl.ac.uk and we can arrange a meeting to discuss how best to get you up to speed.

**Comment by acrymble** [comment]
@sferna109 if possible can we get your bio and photo up this week? Our Portuguese team is waiting for access to the authors.yml file so they can translate it and get their publication live, so we don't want to hold them up.

**Comment by acrymble** [comment]
@sferna109 I'm just uploading your bio (as promised via email). Are there any elements of this checklist that's still outstanding, or is this complete?

**Comment by sferna109** [comment]
> @sferna109 I'm just uploading your bio (as promised via email). Are there any elements of this checklist that's still outstanding, or is this complete?

@acrymble thank you for taking care of this matter, this is now complete .

**Comment by walshbr** [comment]
@sferna109 or @svmelton - I think we adopted a version of this where we'll be group mentoring the new folks together, right? So that last checkbox is done and this can be closed?
