### ISSUE TITLE
Onboarding Checklist for New EN Editor Nabeel

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1873]
## This is an individual onboarding checklist for Nabeel initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Welcome, Nabeel!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [ ] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@svmelton)
- [ ] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project. (@acrymble)

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory)
- [x] set up a Skype account and inform @JoshuaGOB (mandatory)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] Send a photo of yourself and a very brief bio to @acrymble to be added to the project team page 
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by acrymble** [comment]
Does Nabeel know about this ticket @svmelton ?

**Comment by svmelton** [comment]
I've sent him an email, but it occurs to me that he just switched jobs and may not have seen it. I'll see if I can find his new email.

**Comment by nabsiddiqui** [comment]
Hello @acrymble @svmelton 

Sorry for the delay. I did just switch jobs, and I am about a week behind on everything due to a course I had to take about preparing for Covid. I will have this done by tomorrow.

**Comment by nabsiddiqui** [comment]
@JoshuaGOB 

1. @nabsiddiqui is my GitHub account
2. My twitter account is @nabsiddiqui as well but I am almost never on it. 
3. My Skype is nabeel.siddiqui27
4. My google email is nasiddiqui@email.wm.edu

**Comment by acrymble** [comment]
That's ok @nabsiddiqui it's a strange time for all. Can you email me on a.crymble@ucl.ac.uk and we can arrange a time to take you through a few things?
