### ISSUE TITLE
Onboarding Checklist for New EN Editor Alex

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1874]
## This is an individual onboarding checklist for Alex initially found [here](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Welcome, Alex!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Google Analytics account for monitoring web traffic (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] Our Skype group so that you can participate in our monthly calls (@JoshuaGOB - who will pass your details on to the relevant team member)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@svmelton)
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project. (@acrymble)

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory)
- [x] set up a Skype account and inform @JoshuaGOB (mandatory)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by acrymble** [comment]
Does Alex know about this ticket @svmelton ?

**Comment by hawc2** [comment]
Yes, I'm on board!

**Comment by acrymble** [comment]
Great @hawc2 can you send me an email and we can start introducing you to a few of our systems and people? a.crymble@ucl.ac.uk

**Comment by hawc2** [comment]
@JoshuaGOB my email is alwermercolan@gmail.com. My Skype is hawc22. My twitter is @alexwermercolan. Let me know if you need anything else.

**Comment by JoshuaGOB** [comment]
All set on my end @hawc2 and welcome to the team!

@mariajoafana will add you to the Skype call.

@acrymble Just a quick question about adding members to teams. I believe this is done by the team admins right? so for the Project Team it would need to be @walshbr or @ZoeLeBlanc and for the English team @svmelton?

**Comment by walshbr** [comment]
You're an admin for the organization @JoshuaGOB, so you should be able to do it. And I don't think you need to be on the particular team to add them. But if it doesn't seem to work let me know!

**Comment by JoshuaGOB** [comment]
So sorry but I'm stumped. I'm able to add them to the repository but even after they accept their invite they still show up as outside collaborators. I had assumed that once team maintainers added them to their specific team they would move out of [here](https://github.com/programminghistorian/jekyll/settings/access) but Josir was already added to PT and he's still showing up there. Also, I don't have the option to add them from within a team to test if this is always the case. Thank your for helping me out!

**Comment by walshbr** [comment]
I think the problem is that you need to add them to actual GitHub organization, not to the individual repository. The link for the organization members is here - https://github.com/orgs/programminghistorian/teams. If you click on "project team" you should see, on the left, a plus icon for adding to the team more generally. And then the individual teams for the group are listed below. You should be able to click on the EN team and add them there. 

If you can't figure it out though ping me again and I can add again.

**Comment by JoshuaGOB** [comment]
Hi @walshbr this is what I'm seeing when I go through https://github.com/orgs/programminghistorian/teams:
https://ibb.co/XDhJvz7
https://ibb.co/Wsk8HD0

**Comment by acrymble** [comment]
@JoshuaGOB similar problem for me. I can only add people if I'm already on the team.

**Comment by walshbr** [comment]
Can you try now? I tried clicking one other button, but if that doesn't work I'm stumped too because you should have literally the same level of access as me but that link gives a different screen for me.

**Comment by acrymble** [comment]
@walshbr thanks this worked for me. I made the update for @sferna109 to try it out.

**Comment by JoshuaGOB** [comment]
Forgot to check back in @walshbr but this is now working perfectly and I redid all of the other ones I had done before. Thank you.

**Comment by walshbr** [comment]
Sorry it took so long to figure out @JoshuaGOB! GitHub changed their permissions structure, and it's confusing.

**Comment by acrymble** [comment]
@svmelton the last task on this checklist for @hawc2 is to partner him with an editor to shadow the editorial process. Is that already underway?

**Comment by walshbr** [comment]
@svmelton or  @hawc2 - I think we adopted a version of this where we'll be group mentoring the new folks together, right? So that last checkbox is done and this can be closed?

**Comment by svmelton** [comment]
Yup, thanks for checking!
