### ISSUE TITLE
December Technical Team Meeting: December 4 2020

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#1906]
Doodle poll: https://doodle.com/poll/ay7akym7e6h7ki8d

@programminghistorian/technical-team please fill out your preferences for the October Technical Team meeting. Times are 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

Agenda:

- Review any outstanding tickets (maybe discuss if #1795 is ready to be restarted?)
- Discuss new feature backlog https://github.com/programminghistorian/jekyll/wiki/Technical-Team#new-feature-backlog and any other potential longterm goals

**Comment by ZoeLeBlanc** [comment]
Alright gonna try this again for a second time! Sorry for not getting it scheduled last month but hoping we can get a meeting on the books before our team-wide one on the 23rd of November. If everyone could try to respond by Tuesday November 10 that would be very much appreciated 🙏 

Doodle poll: https://doodle.com/poll/78uif72nr6q24gve

@programminghistorian/technical-team please fill out your preferences for the November Technical Team meeting. Times are 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

Agenda:

- Review any outstanding tickets (maybe discuss if #1795 is ready to be restarted?)
- Discuss new feature backlog https://github.com/programminghistorian/jekyll/wiki/Technical-Team#new-feature-backlog and any other potential longterm goals
- Anything else that comes to mind?

**Comment by ZoeLeBlanc** [comment]
~~OKAY! Third time is a charm is a saying right?? So hoping that's true for our team!! Really want to meet before the holiday break so that we can check in and also plan some goals for 2021 🚀~~

~~Please try to respond by **November 27** with your availability 🙏~~

~~Doodle poll: https://doodle.com/poll/abem5asceudqtwd4~~

~~@programminghistorian/technical-team please fill out your preferences for the November Technical Team meeting. Times are 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time~~

**UPDATE: Meeting Scheduled for December 4, 2020 at 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time** using our usual Skype ProgHist Tech Team

Agenda:

- [x] Review any outstanding tickets (@walshbr if you could update us on #1844 that would be appreciated!! Also updates on PT team maybe?)
- [x] Discuss new feature backlog https://github.com/programminghistorian/jekyll/wiki/Technical-Team#new-feature-backlog
- [x] Discuss adding testing field to yaml #1938 
- [x] Discuss doing analytics project of github issues for #1909 
- [x] Discuss if we could add anything to #1932 documentation (think it would be good to discuss Technical Guidance Wiki to see if there's things we're missing)
- [x] Anything else that comes to mind?

**Comment by walshbr** [comment]
Notes / Actionables -

- #1844 - other tech team people will give feedback on the wording there. 
- We will look at a slack integration for ph-submissions to get notifications for the errors. 
- A new ticket for examining the metadata templates for new lessons. 
- @amsichani will think further about #1938

**Comment by ZoeLeBlanc** [comment]
Adding a few more notes here (mostly so I don't forget anything):
 - @ZoeLeBlanc will setup slack integration and will setup ticket for reviewing metadata fields in both lesson templates and editor guidelines for ph-submissions
- From new feature backlog, we'll be working on the low CSS contrast (potentially adding a dark mode) #1524. @ZoeLeBlanc will setup the ticket and goal is to start reviewing what's possible before the next tech team meeting
- For #1909 the tech team will collaborate on analyzing issues from PH with the hopes of generating a conference presentation/publication. @walshbr also brought up potential ways for finding out what lessons are being assigned that we might want to circle back to at a later date (surveys, button clicks, open syllabus are some ideas)
- For #1932 @ZoeLeBlanc will add documentation to the wiki to help clarify how to communicate with tech team members, how to ask for help, and what are some of the common bugs you might encounter
- Also discussed #1945 which @jenniferisasi and @amsichani will be tackling together

Great work team 🚀 🎉 !
