### ISSUE TITLE
Onboarding Checklist for Portuguese language publication editor: Jimmy Medeiros

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#1913]
## This is an individual onboarding Editor checklist for Jimmy Medeiros (@JimmyMedeiros82). Bem-vindo, Jimmy!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the [/contribute](https://programminghistorian.org/en/contribute) pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by JoshuaGOB** [comment]
Hello @JimmyMedeiros82 Welcome! Please feel free to send any questions you may have about the onboarding process. You should have received a couple of emails adding you to our different sites. You can accept these invitations as you go along with the **Technical** set of tasks of the onboarding.

**Comment by JimmyMedeiros82** [comment]
Hello Joshua. Thank you for sending the emails. Let's start the onboard process.

Following the checklist: you already have a GitHub account (@ JimmyMedeiros82).

My skype account is jimmymedeiros_2. You can find me with the email jimmymedeiros@yahoo.com.br

And my gmail is jimmy.d.med@gmail.com

**Comment by JimmyMedeiros82** [comment]
Hello Joshua and others friends,
I'm starting the onboard process!Excited that we are close to launching the Programming Historian em português. 
Best regards,Jimmy Medeiros


Enviado do Yahoo Mail no Android 
 
  Em seg, 5 5e out 5e 2020 às 14:52, JoshuaOB<notifications@github.com> escreveu:   


Hello @JimmyMedeiros82 Welcome! Please feel free to send any questions you may have about the onboarding process. You should have received a couple of emails adding you to our different sites. You can accept these invitations as you go along with the Technical set of tasks of the onboarding.

**Comment by DanielAlvesLABDH** [comment]
Hello @JimmyMedeiros82 ! What is the status of your onboarding? Need any help?

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82! O @JoshuaGOB ou eu podemos ajudar na conclusão deste processo. Abraço

**Comment by JimmyMedeiros82** [comment]
Olá Daniel e Joshua,
Peço desculpas pela demora excessiva. Tive problemas pessoais que me atrapalharam nestes últimos dois meses. Vou concluir o onboarding! 
Ainda é possível?
Vou relembrar o que fazer e concluir o processo. 
Um abraço, Jimmy

Enviado do Yahoo Mail no Android 
 
  Em qui, 28 28e jan 28e 2021 às 10:14, Daniel Alves<notifications@github.com> escreveu:   


Olá @JimmyMedeiros82! O @JoshuaGOB ou eu podemos ajudar na conclusão deste processo. Abraço

**Comment by DanielAlvesLABDH** [comment]
Carlo que siim Jimmy, conta connosco! Abraço

**Comment by JimmyMedeiros82** [comment]
Oi Daniel, 

De início, pelo que revi, falta finalizar a leitura do tópico "Making Technical Contributions". Fiz e vou refazer hoje.
Depois é preciso fazer um pull-request da minha bio e uma foto preto e branco. Isso eu faço direto com o botão de editar em /data/ph_authors.yml  ?

Por fim, serão detalhes mais simples, como ler as seções de contribuições " /contribute " e fazer as marcações de bookmarks. 

Abraço, Jimmy

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82 , vejo que já avançaste nas leituras e no resto do processo de onboarding. Acho que agora seria útil termos uma sessão para praticares um pouco mais o trabalho com o GitHub. Uma ideia que tive para isto era puderes fazer ou acompanhar a edição/correcção de alguns erros em vários ficheiros da plataforma PT. Quando puderes diz-me quais as tuas disponibilidades. Abraço

**Comment by JimmyMedeiros82** [comment]
Oi @DanielAlvesLABDH estou à disposição para avançar nestas atividades.
Podemos começar amanhã?

Abraço

**Comment by DanielAlvesLABDH** [comment]
Podemos sim. Para mim o melhor horário é depois das 18 aqui em Lisboa. É possível?

**Comment by JimmyMedeiros82** [comment]
Está ótimo, @DanielAlvesLABDH !

**Comment by JimmyMedeiros82** [comment]
Olá @DanielAlvesLABDH tem dois pontos em aberto no onboarding. 
Posso marcar ambos como concluído ou teremos alguma formalidade adicional para cumprir estas obrigações?

**Comment by DanielAlvesLABDH** [comment]
Hi @JoshuaGOB, since @JimmyMedeiros82 is working its way into the wonderful world of GitHub with me 😉, can we tick the option "partner you with an existing editor..." and close this ticket?

**Comment by JoshuaGOB** [comment]
Hi @DanielAlvesLABDH, that seems perfect to me! Oficialmente bem-vindo @JimmyMedeiros82

**Comment by JimmyMedeiros82** [comment]
Thank you so much for all your help!
