### ISSUE TITLE
Actions Arising - Project Team meeting 23/11/2020 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1940]
The following actions have arisen from the November 2020 Project Team Meeting

- [x]  @ZoeLeBlanc and @mariajoafana to check on Ticket analytics to contribute to #1909  
- [x]  @ZoeLeBlanc and Tech Team to advance on infrastructure review and assess @acrymble proposal of adding a YAML header with data that tracks when was the lesson last tested    
- [x]  @svmelton and all teams to discuss in ticket #1056 what does shadowing exactly and assess ideas regarding supporting our editors get trained for the editorial process  
- [x] @jenniferisasi finish instructions for bug-fixing requests #1908
- [x] @spapastamkou and the French Team to complete the recruitment of new editors and start the set up a workflow to work in the French copyediting guide after this happen
- [x] @rivaquiroga and Spanish Team to discuss the recruitment of at least two new team members

**Comment by acrymble** [comment]
Has any of this been done? It doesn't look like anyone is using github anymore to track progress.

**Comment by spapastamkou** [comment]
We FR team met this week and made a pre-selection; just left the weekend to digest it before making up our minds.
