### ISSUE TITLE
January 25 2021 Project Team Zoom Call 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1941]
January 25 2020 , Time is 8:00 AM Mexico, 9:00 AM - Colombia, Ottawa, Philadelphia, Boston; 11:00 AM Chile and Brasil (GMT-3); 2:00 PM - London; 3:00 PM - Paris and Portugal. @mariajoafana will be facilitating the call. 

Zoom link: 
https://uniandes-edu-co.zoom.us/j/81909129045?pwd=RTRyL3I4OVRjWWxiMEtDZk1ITmRBZz09Código de acceso: JS31Rf

Working agenda in progress. Please add in this agenda under "Issues and tasks for discussion" the tickets that you'll like to further discuss in the meeting. You can comment or edit this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [x] Actions Arising from November 2020 Project Team Meeting: #1940 

- Issues and tasks for discussion: 

 - [x] #1986 Team Leaders Terms & Selection Process (@acrymble)
 - [x] Long-term tech / hosting requirements (we've been offered hosting support from one of the IPPs. What are our long-term needs, and will Jekyll / github hosting always fulfill them? Do we need succession planning in place for our system? Question from @acrymble for @programminghistorian/technical-team )
 - ES and FR team issues
- New members for the Spanish and French Team progress: proposal of running training workshops for new members. How should we do it? We started a conversation here: #1056 
 - [x] #1984 Software citation
 - [x] Tickets open for a long time: #1777 #1524 #1662 #1710 #1712 
 - [x] @mariajoafana taking over the Team Development Manager position to oversee and help main editors when needed
- [x] ES team issues
   - [ ]   

- [x] EN issues

- [x] FR team issues 

- [x] Portuguese team issues
- When is the Portuguese site going live? #1802 
- [ ]

**Comment by svmelton** [comment]
I will unfortunately be unable to attend this meeting, but I'll write a report closer to the date.

**Comment by ZoeLeBlanc** [comment]
Hi everyone! 
Unfortunately I've come down with something quite serious and spent the weekend in the hospital (so far unknown what's causing it). Back home now but still feeling quite exhausted and ill, so going to miss our meeting tomorrow. Most of the tech team tasks I was planning to tackle this weekend so hoping to get to them once I feel better. Apologies for the delay and hope everyone else is doing well.

**Comment by drjwbaker** [comment]
Ugh. Take care of yourself @ZoeLeBlanc. Our collective well-being is the priority.

**Comment by DanielAlvesLABDH** [comment]
Get well soon @ZoeLeBlanc , that is the important thing!

**Comment by acrymble** [comment]
@mariajoafana can we please have a clear agenda in advance?

**Comment by acrymble** [comment]
## ProgHist Team Report

By: @acrymble  
Date: 22 January 2021

** Updates Since Previous Report:**
- IPP Pages update (English & Spanish now live). Now working on French
- 2020-21 Goals now reporting bi-monthly on progress to ProgHist board
1) Phased end to volunteering on all 'services' provided to pubs (@amsichani)
    - no report yet. Some meetings in progress.
2) Clearly defined project manager role to advertise (@acrymble)
    - With ProgHist board for approval. Proposed half-time permanent position. Needs approving + fundraising (about 40% of the way there).
3) 40 IPP members to provide sustainable income support (@acrymble, @amsichani)
    - 8 IPP to date. 6 other conversations in progress.
    - PLEASE tell us of potential leads for this. Including your own institution.
4) Fully registered as a charity in the UK (@drjwbaker)
    - on hold while we prioritize other areas.
6) Ensure paid bug fixing is taking place and that the system is efficient and fit for purpose (@rivaquiroga) 
    - Riva has just agreed to take this on to get it running more smoothly. We look forward to supporting her.

Exploring improvements to Patreon strategy with aim of increasing average donation (small donations eaten up largely by fees). Consulting current Patrons - with support from @jenniferisasi and @amsichani.

**Questions for the team**

- Does anyone's university want to join IPP? Can you find out for us or tell us who the best contact is so we can check?
- #1988 Middle IPP band criteria - we will be adding a middle price for middle income countries. Please tell us of any unforeseen problems with our plan, if you know of any.

**3-month focus:**

- Goal 2 - Project Manager defined
- IPP fundraising - aiming for 4 more signups by end of March


**12-month focus:**
- Complete all goals as above.

**Comment by jenniferisasi** [comment]
## Comms Team Report

By: @jenniferisasi   
Date: 22 January 2021

** Will have to leave the meeting by 9:30am (weekly office meeting)

*Mixed some with ProgHist Team Report

** Updates Since Previous Report:**
1) Final 2020 Newsletter published in new format: internally multilingual vs. 3 newsletters
  -  Changed prompted by a lack of readership overall; still doing it every 3 months to keep a list of progress, it is useful for us internally, for presentations, etc. They peak the day I publish it and then is visited a couple of times every month
2) IPP Pages update (English & Spanish now live). Now working on French
3) Support @acrymble in exploring improvements to Patreon strategy with aim of increasing average donation (small donations eaten up largely by fees). Consulting current Patrons - with support also from @amsichani.
4) Work on #1908 update `feedback` page 
5) Project Manager (@mariajoafana) and Tech Lead (@ZoeLeBlanc) working on #1909 (discussed also within tech team)

**Questions for the team**
Does anyone think we need *more* comms presence? (unless the idea is small, it would need additional support)
    - Going to implement @acrymble's suggestion of current IPP promotion  

**3-month focus:**
- Finalize #1945 with @amsichani (Education + Tech)
- Keep track of things for newsletter
- replan or phase-out education manager role (tbd w/ @amsichani)
- Improve Patreon blog usage with @acrymble 

**12-month focus:**
- Complete all goals as above.
- Phase out of Comms team
- Implement results on Patreon consultation with ProgHist Ltd (@acrymble)

**Comment by rivaquiroga** [comment]
## ES Team Report

By: @rivaquiroga  
Date: 25 January 2021

**Updates Since Previous Report:**
- Antonio and Victor stepped down.
- Call for editors: we want to recruit three new editors. We will onboard them one at a time.    
- New version of author and translator guidelines published. 
- Exploring the idea of running a workshop for [Open Data Day](https://opendataday.org/) and applying to the mini-grant scheme ($300 USD). 

**Editorial work**

- 1 translation published since previous report (Spanish version of the lesson from the Bogotá workshop that was originally published in English)
- 3 original lessons on the pipeline. 
- 3 translations on the pipeline. 

**3-month focus:**
- Onboard one of the new editors. 
- Copy-edit first original lesson.

**Comment by svmelton** [comment]
## EN Team Report

By: @svmelton  
Date: 25 January 2021

**Updates Since Previous Report:**
- 2 new lessons published 
- 2 lessons at copyediting
- 5 lessons under review
- 3 new submissions
- All editors now onboarded

**3-month focus:**
- Continue to refine on-boarding process
- Copy-edit first original lesson.

**Comment by spapastamkou** [comment]
## FR Team Report

Team Name  FR Editorial

By: @spapastamkou 
Date: 25 January 2021

---

**Actions Completed Since Previous Report:**

1 translated lesson published
1 translation proposal in progress (external) 
1 original lesson now under review

**Actions Remaining Open Since Previous Report:**  

FR Copy Editing Chart
1 translation proposed by Sofia coupled to testing a translation tool for GitHub 
4 translated lessons need to be edited for review

**Other**
Call for editors: info on progress
Workshop proposal sent (15/12/2020) to CFP Humanistica 2021 to present PH en français

**Queries for the Editorial Board:**
Training workshops for new editors as solution to problems raised by shadowing process
Compare proposed timelines of forthcoming onboardings in spring of ES and FR editors

---

**6-month focus:**
Integration of new editors 

**12+ month focus:**
Continue combined publication of translated and original lessons in FR
More effectively communicate on PH FR

**Further Comments:**


None

**Comment by DanielAlvesLABDH** [comment]
## Portuguese Team Report

By: @DanielAlvesLABDH 
Date: 25 January 2021

**Substantive Actions Completed Since Previous Report**

- Our first translated lesson is now complete and we are ready to go live!
- Concluded a paper about "Digital Humanities and teaching in the History Degree in Portugal", with a section about the Programming Historian. To be published on May 2021

**Substantive Actions Remaining Open Since Previous Report**

- Three lessons translated from English (waiting for review)
- Onboarding for Jimmy Medeiros (not closed yet)

**3-month focus**
- Create a blogpost and tweets to announce the new publication
- Onboarding of the last editor of the PT team (Ricardo)
- Implement some of the lessons in one graduate course at NOVA-FCSH (Lisbon) and in another graduate course at FGV (Rio de Janeiro), in the context of the project "Digital Literacy in the Social Sciences and Humanities", funded by FGV (will start March 2021)

**6-month focus**
- Start the translation of at least 6 lessons from the English originals

**12+ month focus**
- Finish and publish at least 16 lessons translated from the English originals

**Comment by DanielAlvesLABDH** [comment]
Dear all, unfortunately I cannot attend the meeting because my Department is discussing a reform in the curricula and we were all asked for a meeting starting today at 2 pm

**Comment by mariajoafana** [comment]
@DanielAlvesLABDH thanks for letting us know, although the meeting is 11am Brasil time. Hopefully you can make it.

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> @DanielAlvesLABDH thanks for letting us know, although the meeting is 11am Brasil time. Hopefully you can make it.

I'm in Portugal @mariajoafana ;-)

**Comment by JMParr** [comment]
### **Global Team Report**

By: @JMParr 
Date: 25 January 2021

The Global Team held a quarterly meeting on 13 Jan to discuss its strategy for 2021. We set a series of goals:

**3 Months:**

- UCLDH 2020-21 seminar series “The Digital Humanities Long View”. To present a paper about PH and multilingual / regional DH needs. The team mentioned contacting the other MEs to address the issue and make them part of the paper.

- Facilitating a new strategy for streamlining the onboarding of new editors across teams, and new language teams. Specifically, we wondered if there was a way to do periodic scheduled multilingual onboarding of new editors to help reduce some of the bus factor of individual editors/MEs leading the work (and to streamline the communication between teams).

**6 Months:**

- Need a document/extended blog about the process related to how the Portuguese team reconciled Portuguese Portuguese and Brazilian Portuguese / bigger cultural-linguistic differences than in Spanish.

- The French team wants to look at their representitiveness - esp. African speakers of French. Sofia said that she plans on speaking to a Senegalese academic to see if he would be interested in joining once they are finished with recruiting and onboarding the new members.

- Riva discussed getting PH more involved in Open Data Day - organize an event within a key area, and we can apply for a small grant (about $300): Open mapping, equal development, environment, tracking public funding. Talk about where data is open. (Discuss with James).  RQ to discuss this with Adam on Friday (15 Jan)

- We discussed the (eventual) growth of the Global Team. We are okay for now, but eventually would like to add and/or rotate representation from the French and Spanish teams, and add representation from the Portuguese team once they are onboarded and settled in.

**Comment by mariajoafana** [comment]
> I'm in Portugal @mariajoafana ;-)

Yes! sorry

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc

Date: 25 January 2021

Actions Completed Since Previous Report:

- Brandon completed #1795 with #1844 so we now have updated workflow for submitting lessons 🎉
- Closed Matt Lincoln's retirement #1761 (with exception of cloudflare issue, which hoping to tackle today)

Substantive Actions Remaining Open Since Previous Report:

- #1802 is almost done. We now have a PR moving over the crossref.xml and that shows PT live. One hold up is having the first lesson in the actual Jekyll repo. Once that's there we can publish the PT site and request a DOI for the lesson from Sussex. Also looks like there's some syntax errors that need to be cleaned up.
- We are proposing updating yaml fields on initial lesson submission to limit user error but want sign off from language teams first #1995
- Initial PR #1994 for adding last tested fields to lessons is now up. Initial issue is described in #1938. Currently the proposed approach records all testers names and most recent test date. If that approach is approved, then all we need is translations and then we're good to add it in.
- For the lesson sequence banners in ES #1945, we're currently paused until all lessons are published.
- Low contrast mode is pretty close to finished. We just need to work on making the button a bit more responsive (also open to feedback on the UI choices) #1992
- Still need to setup Github repo for doing analytics project of github issues for [#1909](https://github.com/programminghistorian/jekyll/issues/1909)
- In our tech team meeting, we discussed if we could add anything to [#1932](https://github.com/programminghistorian/jekyll/issues/1932) documentation (think it would be good to discuss Technical Guidance Wiki to see if there's things we're missing) and I'll be reviewing ways we could add more signposts for editors to understand how to communicate with Tech team both on Github and Slack

6-month focus:

- Tech team meeting in February/March to discuss goals and maintenance for the next few months.
- Continue to help support Portuguese team onboarding and any additional new editors that need training

12+ month focus:

- New features?
- Documentation review
- Review of Github issues trends

**Comment by mariajoafana** [comment]
> Hi everyone!
> Unfortunately I've come down with something quite serious and spent the weekend in the hospital (so far unknown what's causing it). Back home now but still feeling quite exhausted and ill, so going to miss our meeting tomorrow. Most of the tech team tasks I was planning to tackle this weekend so hoping to get to them once I feel better. Apologies for the delay and hope everyone else is doing well.

I hope you feel better soon @ZoeLeBlanc

**Comment by ZoeLeBlanc** [comment]
Thanks @mariajoafana !! Funny story when I was feverish last week I thought we had our meeting last Monday so I'm actually fine now and I'll be on our call in a minute :)
