### ISSUE TITLE
Anna-Maria's maternity leave checklist

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1956]
As I am now slowly preparing for my maternity leave (late Feb - June 2021) :rainbow: :rainbow: :rainbow: , below is a checklist of my pending tickets / tasks (plz, bear with me for any lateness):

**english team**

- [x] publish OCR and Machine Translation [#285](https://github.com/programminghistorian/ph-submissions/issues/285)
- [ ] finalise and publish Detecting Text Reuse with Passim [#305](https://github.com/programminghistorian/ph-submissions/issues/305)

**technical team**
- [ ] work with @jenniferisasi on #1945 
- [ ]  think about adding testing field to yaml #1938 -- also related to #1633

**ProgHist Ltd**
- [x] invites to new IPP members - work with @acrymble 
- [x] work with team leaders on discussing next steps for phased end of volunteering on all services  -- also linked to [#1856](https://github.com/programminghistorian/jekyll/issues/1856)  
- [ ] decide with the ProgHist Directors on a timeline for ProgHist2021 goals during [#1946](https://github.com/programminghistorian/jekyll/issues/1946)

**Comment by acrymble** [comment]
@svmelton @ZoeLeBlanc As AM is currently on leave, are there any actions here that need to be allocated to someone else? If not, can we close this at #2019 ?

**Comment by svmelton** [comment]
We can close this on my end—the English team tasks will be on my plate once the author has completed their edits.
