### ISSUE TITLE
Actions arising from January 2021 meeting

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1996]
- [x] @ZoeLeBlanc to create a repository to aggregate PH Github data

- [ ] @programminghistorian/technical-team to ask editors to add names of those (reviewers, translators) who tested the lesson and the most recent testing date 

- [x] @programminghistorian/spanish-team is recruiting 3 new members

- [x] @programminghistorian/french-team is recruiting 5 members 

- [x] @programminghistorian/french-team to organize a workshop to train new members y a 3-hour lesson. All members together. Develop some documentation

- [ ] @programminghistorian/spanish-team proposed a scaffolding process in which one new editor is trained and then trains a new member

- [x] @jenniferisasi to finish instructions for bug-fixing requests #1908 Lead editors and tech team to check the instructions and translate them 

- [x] Team leaders: Comms, Tech, Global, ProgHist assess their role and time on it and comment to ticket #1986. 

- [x] @rivaquiroga to complete software citation #1984 

- [x] @programminghistorian/technical-team to consider @acrymble question on long term tech and into CHNM hosting. Not pressing at the moment, will revisit later on

- [x] @rivaquiroga to add a generic and short sentence in guidelines regarding ticket #1712 

- [x] @rivaquiroga to ask a tester with Windows to test for bugs #1777  

- [ ] @programminghistorian/technical-team to check accessibility best practices upon completion of #1662

- [x] @DanielAlvesLABDH to let us know about the planning of the Portuguese site launch and promotion (blog, twitter)
