### ISSUE TITLE
Onboarding Checklist for French language publication editor: Matthias Gille Levenson

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2017]
This is an individual onboarding Editor checklist for Matthias GILLE LEVENSON (@matgille). Sois le bienvenu, Matthias!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@spapastamkou) 
- [ ] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the [/contribuer](https://programminghistorian.org/fr/contribuer) pages of the website, including author, reviewer, and editor guidelines (consignes aux auteurs, traducteurs, évaluateurs et rédacteurs)
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by matgille** [comment]
@JoshuaGOB Hi Joshua, I'm Matthias and this is my username: matgille ! Thanks !

**Comment by JoshuaGOB** [comment]
Hello @matgille and welcome!
Please send me your google activated email so I can add you to our group email. Thank you.

**Comment by spapastamkou** [comment]
@matgille As-tu besoin de voir ou revoir ensemble quelque-chose ici? Cela peut ne pas paraître très clair au début, et si c'est le cas, n'hésite pas à faire signe:-)

**Comment by matgille** [comment]
Merci ! Normalement j'ai bien envoyé mon courriel à Joshua, mais par voie de mail, je n'utiliserai mon adresse google que pour le groupe de PH et je préférerais qu'elle ne soit pas publique (si possible bien sûr) et que l'on me contacte via mes adresses universitaires. 

@JoshuaGOB Hi Joshua, did you receive my email with my google username ?

**Comment by matgille** [comment]
J'espère faire les choses correctement !
Edit: une première série de tests a échoué du fait d'une erreur d'espaces de ma part dans `ph_authors.yml`. C'est réglé normalement.

**Comment by matgille** [comment]
Bon en fait probablement pas, j'en suis désolé. En faisant un copier-coller dans le fichier .yml, j'ai dû changer une espace quelque part...

**Comment by JoshuaGOB** [comment]
Hi @matgille I haven’t received yet. Could you please resend it to joshuaortizbaco[at]utexas.edu

**Comment by spapastamkou** [comment]
@matgille Otherwise, if you prefer not to have it exposed here, you can
send it to me and I will forward to Joshua and Adam. Thanks!

>

**Comment by JoshuaGOB** [comment]
Hi @matgille, you should be good to go. Just make sure to accept the invitation, it does expire, and say a quick hello to the rest of the team. Again, welcome!
