### ISSUE TITLE
Onboarding Checklist for French language publication editor: Gwenaëlle Patat

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2018]
This is an individual onboarding Editor checklist for Gwenaëlle Patat (@InesSalome). Sois la bienvenue, Gwen!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@spapastamkou) 
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project. 

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the [/contribuer](https://programminghistorian.org/fr/contribuer) pages of the website, including author, reviewer, and editor guidelines (consignes aux auteurs, traducteurs, évaluateurs et rédacteurs)
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by InesSalome** [comment]
@JoshuaGOB

Hello Joshua, I am really honored to be part of the project ! This is my Github account : @InesSalome and my Google-activated email : gwenaelle.patat@gmail.com. You can add me to the PH Team when you find the time.

**Comment by JoshuaGOB** [comment]
Hi, we have you set up here in Github, our Google group and analytics. Good luck and welcome to the team!

**Comment by InesSalome** [comment]
Thank you very much !

**Comment by spapastamkou** [comment]
@acrymble Are you in charge of the invitation for membership at ProgHist Ltd. ? Did not ping you before! If you confirm, we are practically done with this ticket. Thanks!

**Comment by acrymble** [comment]
Yes @spapastamkou but can you please email me a list of everyone and their email addresses so I can send them all at once? I know there are a few and we don't want to miss anyone.

**Comment by spapastamkou** [comment]
Let's do like this @acrymble. I do not yet have all the G-enabled addresses so I will send you the list by the end of the week. Thank you.

**Comment by spapastamkou** [comment]
Everything is fine here, so I close this ticket. Thank you all for your help!
