### ISSUE TITLE
March 24, 2021 Project Team Zoom Call

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#2019]
March 24 2020 , Time is 8:00 AM Mexico, 9:00 AM - Colombia; 10:00AM Ottawa, Philadelphia, Boston; 11:00 AM Chile and Brasil (GMT-3); 2:00 PM - London and Portugal; 3:00 PM - Paris. @mariajoafana will be facilitating the call. 

You can use this time converter to double-check the time of the meeting in your time zone: https://www.timeanddate.com/worldclock/

Zoom link: 
 https://uniandes-edu-co.zoom.us/j/86560566452

Working agenda in progress. Please add in this agenda under "Issues and tasks for discussion" the tickets that you'll like to further discuss in the meeting. You can comment or edit this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [x] Actions Arising from January 2021 Project Team Meeting: #1996 

- Issues and tasks for discussion: 

 - [x] #1986 Team Leaders Terms & Selection Process (@acrymble)
- [x] #2089 Deleting Lesson Request Pages (@acrymble)
- [x] Go Fund Me campaign for hiring gf.me/u/znjc5d (@acrymble)
 
- [x] Updates on tickets open for a long time with no clear path to completion:  
Editor training idea #1056 
Visualizing Data with Bokeh and Pandas #1662 
DOAJ listing for ES and FR publications #1827 
Annual statistics on submissions #1849 
Wiki page for saving tickets #1857 
Bug transforming Data for Reuse #1876 
Optimize the use of Github tickets #1909 

  
- [x] ES team issues
Debrief about PH Spanish workshop    

- [x] EN issues
Simultaneous language proposals

- [x] FR team issues 
Onboarding process of new members #2065 #2056 
French Team Editorial workshop #2035 

- [ ] Portuguese team issues
Onboarding new members #2076  

- [ ]

**Comment by rivaquiroga** [comment]
## ES Team Report

By: @rivaquiroga  
Date: March 22, 2021

**Updates Since Previous Report:**
- The call for three new editors was published. It will remain open until April 30. 
- We copyedited a lesson for the first time :rocket:
- We organized two workshops for Open Data Day with funding from the Open Knowledge Foundation. ~50 + ~30 people attended. 

**Editorial work**
- 1 original lesson published since previous report (our sixth)
- 1 translation published since previous report
- 3 original lessons being edited
- 2 translations being edited

**3-month focus:**
- Tomorrow: talk + workshop at INTELE
- Onboard new editor(s).

**Comment by jenniferisasi** [comment]
## Comms Team Report

By: @jenniferisasi   
Date: March 22, 2021

**Updates Since Previous Report:**
- Updated 'bug feedback' pages
- Tweeted during events, which brought a lot of traffic on Twitter
- The call for three new editors for ES (with @rivaquiroga)
- Compiled updates for 1st Newsletter of 2021 #2054 
- Helped ProgHist with fundraising plan


**3-month focus:**
- Fundraising communications plan
- Keep track of updates for Newsletter
- Tomorrow: talk + workshop at INTELE (with @rivaquiroga)

**Comment by acrymble** [comment]
# ProgHist Report

By: @acrymble Date: 23/03/2021

## Actions Completed Since Previous Report:

### Funding Related:

* IPP Pages update (French pages now live. Only PT to go)
* Middle band IPP level set at £400 and implemented
* Patreon - one off funding boost of about £300 due to tweaks to strategy. Remains a source of sustainable income.
* IPPs - now have 12 IPPs including new (Software Sustainability Institute; Princeton University; Roy Rosenzweig Center for History & New Media; Transkribus).
* GoFundMe page ready to raise final £15000 needed to hire our first staff member. Thanks to @rivaquiroga and @jenniferisasi for support.

### Non-Funding Related:

* @drjwbaker has made significant progress on registering ProgHist ltd as a charity. This will significantly reduce our tax obligations.

## Actions Remaining Open Since Previous Report:

* @rivaquiroga has proposed an improved workflow for lesson maintenance. This is on going but making good progress.
* PT IPP pages on hold while team focuses on publishing instead.

## Queries for the Editorial Board:

I think we should consider as a Project Team shifting all "Publishing" activity - Global, Comms, Tech, ProgHist - into the charity in the next 1-2 years (see #1986 - Team Leader - Terms & Selection Process). This would simplify things legally and in terms of communication channels and reporting. I don't need to lead this, as this isn't a power grab. But I think we should discuss its advantages and disadvantages.

## 6-month focus:

* 8 more IPP signups @acrymble @rivaquiroga 
* GoFundMe campaign launched and target met @acrymble @jenniferisasi @rivaquiroga 
* Hire project manager @acrymble
* Register as a Charity @drjwbaker 
* Finish lesson maintenance workflow @rivaquiroga 
* Assess and address skills gaps within the ProgHist team

## 12+ month focus:

* work together to formulate a 5 year plan in cooperation with other publishing teams.

**Comment by spapastamkou** [comment]
## FR Team Report 2

**Actions Completed Since Previous Report:**

3 editors onboarded - 2 in progress: #2065 #2086
1 [original lesson reviewed and author revised](https://github.com/programminghistorian/ph-submissions/issues/329); now under final editorial control #2053
1 translation [under review](https://github.com/programminghistorian/ph-submissions/issues/359), 1 to be reviewed (new FR editors)
Training workshop for new editors on 27 March #2035
FR Copy Editing Chart: ticket opened #2042

**Actions Remaining Open Since Previous Report:**  

2 translated lessons need to be edited for review
1 translation proposal in progress (external) 

**Other**
none

**Queries for the Editorial Board:**
none

**6-month focus:**
Accomplish copy editing chart
1 translation editing per each team member 

**12+ month focus:**
Define priorities for original lessons 
Accomplish translation of Python series lessons

**Further Comments:**
none

**Comment by svmelton** [comment]
## EN Team Report

By: @svmelton 
Date: March 23, 2021

**Updates Since Previous Report:**

- 2 pieces back from copyediting and awaiting authors' final edits
- 2 new submissions received
- [1 piece](https://github.com/programminghistorian/ph-submissions/issues/348) at peer review
- [1 piece](https://github.com/programminghistorian/ph-submissions/issues/325) back from peer review

**Actions Remaining Open Since Previous Report:**

- None

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc

Date: 23 March 2021

Actions Completed Since Previous Report:

- We closed #1802  and PT went live. We know have DOIs as well 🎉
- We closed #1992 and added low contrast mode to the site
- #2016 is ready to be closed and officially removes Travis from our pipeline which was replaced by Github Actions (and saved us a third of operating budget every month 🙌🏽 )

Substantive Actions Remaining Open Since Previous Report:

- Still working on whether to change initial lesson submission metadata and need to setup meeting with managing editors #1995
- PR #1994 for adding last tested fields to lessons is now ready for translations. In issue #1938, we discussed whether we would change the layout for metadata fields and we are still coming to final decisions but want to have this merged in by the end of April for our first lesson testers. 
- For #1909 we did set up a new repository for doing data analysis with our Github issues (which you can visit here https://github.com/programminghistorian/ph-activity-analyzer) and in our March tech team meeting we decided that this ticket was mostly about email hygiene and so might not really be a technical ticket
- We opened #2072 to conduct an accessibility audit now that low-contrast is live and @walshbr is leading that initiative. 
- @hawc2 is also leading #2030 which is an assessment of our current archiving of web links strategy. He's proposing that we might use a new system with perma.cc that would help us preserve our lesson content a bit more than web archive.
- Hoping to finish lesson sequence banners in ES #1945 and translation concordance #2002 in the coming weeks (thanks @jenniferisasi for taking the lead on these!)
- Finally now undertaking a redesign our front page #2020 to hopefully make it more user friendly and multilingual friendly (@ZoeLeBlanc is leading this initiative)

6-month focus:

- Front page redesign
- Accessibility audit
- Adding more documentation to the wiki

12+ month focus:

- Review alternatives to Jekyll (is it time for a faster static site generator?)
- Review of Github issues trends

**Comment by drjwbaker** [comment]
apologies, my previous meeting may overrun so I may be late :(

**Comment by DanielAlvesLABDH** [comment]
## Portuguese Team Report

By: @DanielAlvesLABDH 
Date: 24 March 2021

**Substantive Actions Completed Since Previous Report**

- Finished onboarding for Jimmy Medeiros
- Blogpost and tweets to announce the new publication

**Substantive Actions Remaining Open Since Previous Report**

- Three lessons about Python translated from English (waiting for final revision from the translators)

**3-month focus**
- Onboarding of the last editor of the PT team (Ricardo Pimenta) already started
- Implement some of the lessons in one graduate course at NOVA-FCSH (Lisbon) and in another graduate course at FGV (Rio de Janeiro), in the context of the project "Digital Literacy in the Social Sciences and Humanities", funded by FGV (already started)
- Three new lessons translations were received and are now in the peer review process: introducao-ao-markdown; download-de-paginas-web-com-python and camadas-vetoriais-qgis
- "Digital Humanities and teaching in the History Degree in Portugal" (Daniel Alves), with a section about the Programming Historian. To be published on May 2021

**6-month focus**
- Start the translation of at least 6 lessons from the English originals

**12+ month focus**
- Finish and publish at least 16 lessons translated from the English originals

**Comment by rivaquiroga** [comment]
Something I forgot to ask to the @programminghistorian/technical-team: are there plans to update [the guide for making technical contributions](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions ) now that we are using GitHub Actions? This guide is a key part of the onboarding process of new editors. Is there anything the rest of us can do to help?

**Comment by mariajoafana** [comment]
I've added your question to ticket #2090 so we can discuss it in the next meeting if not sooner. I'm going to close this now
