### ISSUE TITLE
March Technical Team Meeting: March 10 2020

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2047]
Thanks to everyone for filling out the doodle poll!

**March Tech Team Meeting scheduled for March 10 2020 10:00 AM - EST 🎉** 
Times are 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.
Zoom link:  https://princeton.zoom.us/j/98074745251

Agenda:
- Updating Initial Lesson Metadata Guidelines #1995
- Add Last Tested Yaml To Lessons #1938
- Determine future of CI for PH repos #2016
- Front page redesign #2020
- Could perma.cc help PH keep weblinks sustainable? #2030 (with the help of @hawc2 )
- Lower contrast CSS option #1524
- Optimize the use of GitHib tickets #1909

Already a lot on the agenda but feel free to add any other topics!

**Comment by ZoeLeBlanc** [comment]
Next steps:

- [ ] Zoe will take care of #2016 (on own blog and then Jennifer will reference in the research page)
- [ ] Checkout out dependabot for github actions packages so that we ensure they are being maintained (ht: @hawc2 ) (Zoe)
- [ ] #1995 email each managing editors and maybe start English and Spanish lesson templates (Zoe)
- [ ] #2020 remove text from blocks and shuffle them. Also need to rethink main landing page (Zoe)
- [ ] Fix home link for languages other than English so that it actually goes back to full home page (Zoe)
- [ ] Try different shapes and layouts for redesign (Zoe)
- [ ] Bring up perma.cc to the main meeting and find out if we have library partners who would want to join on our behalf (also maybe intermediate level of use initially and then downgrade?) (Alex)
- [ ] Documentation for snapshots of links (do we have this? Brandon and Zoe)
- [x] Merge in low contrast and then start accessibility audit (Zoe and Brandon)
- [x] Figure out which icon we like for day and night mode (go back to switch suggested by Alex) (Zoe )
 ![](https://image.shutterstock.com/image-vector/vector-day-night-switch-mobile-260nw-1576065022.jpg)
default email settings and notifications documentation #1909 (Zoe and Jennifer maybe?)

**Comment by walshbr** [comment]
Closing b/c this meeting happened.
