### ISSUE TITLE
Onboarding Checklist for French language publication editor: Antoine HENRY

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2056]
This is an individual onboarding Editor checklist for Antoine HENRY (@icolab). Sois le bienvenu, Antoine!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@spapastamkou) 
- [ ] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB / @spapastamkou of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB / @spapastamkou of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the [/contribuer](https://programminghistorian.org/fr/contribuer) pages of the website, including author, reviewer, and editor guidelines (consignes aux auteurs, traducteurs, évaluateurs et rédacteurs)
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by spapastamkou** [comment]
Hey @icolab, if you need any support with the tasks here, let me know:)

**Comment by icolab** [comment]
Sorry, I will do it today or tomorrow!

**Comment by icolab** [comment]
Ping @JoshuaGOB for my github account.

**Comment by spapastamkou** [comment]
Email and github username transmitted by email.

**Comment by JoshuaGOB** [comment]
Hello @icolab and welcome to the team! I sent out your invitations for our GitHub repo and Google Groups. Please make sure you accept the invitations as they do expire.

**Comment by icolab** [comment]
@JoshuaGOB Done and I will send an email on the list soon.

**Comment by spapastamkou** [comment]
@icolab We are only an email-to-say-hi away from closing this ticket:-)

**Comment by icolab** [comment]
Done, sorry, the message was in my draft... and I will be there tomorow for the call
