### ISSUE TITLE
Onboarding Checklist for French language publication editor: Giulia Taurino

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2065]
This is an individual onboarding Editor checklist for Giulia Taurino @giuliataurino. Nous te souhaitons la bienvenue, Giulia!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@spapastamkou) 
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB / @spapastamkou of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB / @spapastamkou of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [ ] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [ ] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [ ] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [ ] Read all sections of the [/contribuer](https://programminghistorian.org/fr/contribuer) pages of the website, including author, reviewer, and editor guidelines (consignes aux auteurs, traducteurs, évaluateurs et rédacteurs)
- [ ] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by giuliataurino** [comment]
Hi @JoshuaGOB, @spapastamkou,
Here are my github account (@giuliataurino / Giulia Taurino) and email (giulia.taurino89@gmail.com).
G.

**Comment by JoshuaGOB** [comment]
Hello @giuliataurino. Welcome to the team! You should have received invitations to our GitHub repo and the Google Group. Once you accept the invitations you would be good to go.

**Comment by spapastamkou** [comment]
all ok here? If you need support with something, @giuliataurino, let us know, we'll be glad to help!

**Comment by JoshuaGOB** [comment]
Hi @giuliataurino I resent the invitation to our github repository as the old one had expired. Please let me know if you need any help with this.

**Comment by giuliataurino** [comment]
Hi @JoshuaGOB,
I think I might have missed the first invitation to the GitHub repo, but I correctly received this one!
@spapastamkou, would you mind sharing the link to the workshop planned for March 27th?
Thanks!

**Comment by acrymble** [comment]
@spapastamkou I've just gone through the members page and @giuliataurino is still not listed there. Can you help her get her profile up please?

**Comment by JoshuaGOB** [comment]
Hi @spapastamkou and @acrymble, I just resent the invitation and it appears the account is now in. 

@giuliataurino Please let me know if you can now complete this task: 

- [ ] make a technical contribution on your own using that ticket. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars. You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)

**Comment by spapastamkou** [comment]
Thank you @acrymble and @JoshuaGOB. 
@giuliataurino Please let me know if you need any help to complete the tasks here, which is necessary for your eventual integration in the team. Feel free to write me for any problem if you prefer. Thank you very much.

**Comment by spapastamkou** [comment]
@JoshuaGOB There has been no progress at all here, will you hate me if I ask you to retire access from the Ggroup and the repository? Please accept my sincere apologies. Once you confirm, I will close this ticket. Thank you very much.

**Comment by JoshuaGOB** [comment]
No problem at all @spapastamkou. It's all set and I'll close this now.

**Comment by spapastamkou** [comment]
Thanks @JoshuaGOB !
