### ISSUE TITLE
Onboarding Checklist for Portuguese language publication editor: Ricardo Pimenta

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#2076]
## This is an individual onboarding Editor checklist for Ricardo Pimenta (@pymentha). Bem-vindo, Ricardo!

---

## Bem-vindo 

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [ ] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [ ] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [ ] Read all sections of the [/contribua](https://programminghistorian.org/pt/contribua) pages of the website, including author, reviewer, and editor guidelines
- [ ] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by DanielAlvesLABDH** [comment]
Olá @pymentha! Vamos dar início à sua introdução ao GitHub do Programming Historian. Comece pelas tarefas da secção "communication" enviando o seu GitHub user e o seu gmail para o @JoshuaGOB, usando a caixa de comentário abaixo. Qualquer dúvida, não hesite em perguntar. Abraço

**Comment by pymentha** [comment]
Hello @JoshuaGOB, my Gmail account is ricardo.pimenta@gmail.com

**Comment by DanielAlvesLABDH** [comment]
@pymentha agora já pode marcar a opção "make a technical contribution" e passar aos outros pontos da secção "technical". Se tiver dúvidas sobre os próximos passos,  não hesite em perguntar. Abraço

**Comment by DanielAlvesLABDH** [comment]
Olá @pymentha , alguma dúvida? Precisa de ajuda?

**Comment by DanielAlvesLABDH** [comment]
Olá @pymentha podemos avançar com isto? Abraço

**Comment by JoshuaGOB** [comment]
Olá @DanielAlvesLABDH Revisei a tarefa obrigatória de fazer uma contribuição técnica e @pymentha já fez. Depois de associar com um editor existente, podemos fechar o ticket.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @JoshuaGOB. É preciso que o @pymentha nos diga se está pronto para a próxima fase. Abraço

**Comment by acrymble** [comment]
A reminder that this checklist is supposed to take no more than 2 weeks.

**Comment by DanielAlvesLABDH** [comment]
@acrymble, just had a talk with @pymentha today, and due to an excess of working duties he is going to suspend is collaboration with us. We will keep collaborating with the DH Lab that Ricardo coordinate, because Josir, one of our editors, is a close collaborator in that Lab. So, for now, we are going to suspend this onboarding process. Thanks

**Comment by rivaquiroga** [comment]
@DanielAlvesLABDH , while adding the new Spanish editors to our Project Team page, I realized Ricardo Pimenta still appears there as an [PT editor](https://programminghistorian.org/en/project-team#programming-historian-em-portugu%C3%AAs). Is that correct? If the onboarding was suspended, then the related tasks that were completed must be reverted.

**Comment by acrymble** [comment]
Good catch @rivaquiroga!

* [x] Remove Google Groups access
* [x] Remove Github Jekyll access 
* [x] Remove from ProgHist Ltd register of members (will be done via #2246)
* [x] Remove Twitter access (@jenniferisasi) - Jenn does he have access to Twitter? I know not everyone does.
* [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@acrymble)

**Comment by DanielAlvesLABDH** [comment]
Dear @rivaquiroga and @acrymble thanks for this

**Comment by jenniferisasi** [comment]
Checking on Twitter ... he didn't have access yet.
