### ISSUE TITLE
Onboarding Checklist for French language publication editor: Célian Ringwald

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2086]
This is an individual onboarding Editor checklist for Célian Ringwald @datalogism. Nous te souhaitons la bienvenue, Célian!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@spapastamkou) 
- [ ] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x]  set up a GitHub account and inform @JoshuaGOB / @spapastamkou of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB / @spapastamkou of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the [/contribuer](https://programminghistorian.org/fr/contribuer) pages of the website, including author, reviewer, and editor guidelines (consignes aux auteurs, traducteurs, évaluateurs et rédacteurs)
- [ ] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by datalogism** [comment]
Hello @spapastamkou  and @JoshuaGOB,
proud to write my first message within PH :)
You have now my @datalogism
Concerning my gmail, i got this one : celian.ringwald1@gmail.com.
I will immerse myself in the reading 'Onboarding Process for New Editors' & 'Making Technical Contributions' for saterday :)
Have a sunny day !

**Comment by datalogism** [comment]
@JoshuaGOB can you add me to the gitlab team ? I need to be yours for beginning my first edition task :) Thank you by advance

**Comment by spapastamkou** [comment]
Let me know if you need further help for adding your bio once the github access is ok, @datalogism

**Comment by datalogism** [comment]
Allright @JoshuaGOB thank you so much !

**Comment by JoshuaGOB** [comment]
Hello @datalogism and welcome. You should be setup with everything you need. Feel free to let me know if any of the invites didn't work.

**Comment by spapastamkou** [comment]
@datalogism Especially since you started contributing with reviews etc it would be good to go forward with this ticket and finish with remaining tasks. Thanks!

**Comment by datalogism** [comment]
I will finish it during the week, i have been busy last week but i didn't forget it !

**Comment by datalogism** [comment]
@spapastamkou  i add some trouble with the add of my bio on  /data/ph_authors.yml and the add my photo on  /avatars.
i was thinking that it was about the name of the photo, and i duplicated a pull request... can you help me on theses points ?

**Comment by spapastamkou** [comment]
@datalogism Pas de souci:-) Je vais voir ce qui se passe et te fais signe là-bas.

**Comment by datalogism** [comment]
@spapastamkou @JoshuaGOB  As this ticket is still open i am taking advantage of the opportunity to report a problem that i got with my gmail account.
I can no longer access to celian.ringwald1@gmail.com, for this reason i needed to inform you about my new gmail adress :
ringwald.celian@gmail.com.
