### ISSUE TITLE
Actions arising from March 2021 meeting

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#2090]
PLEASE FEEL FREE TO ADD ANY ACTIONS I MIGHT BE MISSING

- [ ] @mariajoafana to coordinate a plan of timeframes for each one of the roles and start putting this into practice by finding a new Comms leader with @jenniferisasi to take over the role starting in January 2022 #1986 

- [x] @rivaquiroga to run the second round of bug testing and engage with English team @svmelton @hawc2 #1777 This is also related to the Lesson Maintenance Workflow #2058 #2082 and https://github.com/programminghistorian/jekyll/wiki/Bug-Assessment 
 
- [x] @ZoeLeBlanc @svmelton to start inquiring into possible grants to apply in the US

- [x] All teams to consider @acrymble proposal to move the Project Team Board to ProgHist, this will mean to take minutes of the meeting
 
- [ ] @programminghistorian/spanish-team to complete the recruitment of 3 new members

- [x] @drjwbaker and @hawc2 to look into using perma.cc for archiving project's weblinks, we need a library to sponsor this #2030  

- [x] @rivaquiroga forgot to ask to the @programminghistorian/technical-team: are there plans to update the guide for making technical contributions now that we are using GitHub Actions? This guide is a key part of the onboarding process of new editors. Is there anything the rest of us can do to help?
