### ISSUE TITLE
July 28 2021 Project Team Meeting

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#2159]
July 28 2021, Time is 9:00 AM - Colombia, Mexico; 10:00AM EDT; 3:00 PM - London, Portugal; 4:00 PM CET - Paris. @mariajoafana will be facilitating the call. 

You can use this time converter to double-check the time of the meeting in your time zone: https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210728T1400

Zoom invitation:  https://uniandes-edu-co.zoom.us/j/89661075902

Working agenda in progress. Please add in this agenda under "Issues and tasks for discussion" the tickets that you'll like to further discuss in the meeting. You can comment or edit this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [x] Actions Arising from May 2021 Project Team Meeting: https://github.com/programminghistorian/jekyll/issues/2158  

- Issues and tasks for discussion: 

 - [x] @drjwbaker and @hawc2 on how to test and implement perma.cc for archiving project's weblinks #2030  

- [x] #1986 - Team Leader Selection Process @acrymble @nabsiddiqui 
- [x] Update from AGM: ProgHist Business Plan 2021 @acrymble - including new goal proposal by @spapastamkou on legal matters (Paper B ProgHist Business Plan 2021 AGM.pdf)
- [x] Update from AGM: ProgHist Service Agreement Terms 2021 @acrymble (https://github.com/programminghistorian/jekyll/wiki/Service-Agreement-Publisher-and-Publications)

- [x] Discussing a 3, 5, & 10 year plan @acrymble
 
- [ ] Updates on tickets open for a long time with no clear path to completion:  

- [x] @Anisa-ProgHist Proposal for new system to use Labels to identify:

 - Issues which represent Priority Actions arising from Project Team Meetings (relating to Item above)
 - Issues which are Closed but remain On Hold (to pick up again in the future) 
 

- [x] @Anisa-ProgHist question of where best to save Project Team Meeting minutes so that they remain accessible to all

**Comment by anisa-hawes** [comment]
Hello there @mariajoafana. I've joined the team today, and would be interested to speak with you about contributing to the Project Team Meeting! Let me know when you have scope to connect.

**Comment by mariajoafana** [comment]
Sure @Anisa-ProgHist I'll contact you via email so we can coordinate

**Comment by drjwbaker** [comment]
I now can't make this, apologies.

**Comment by acrymble** [comment]
Team Name: ProgHist

By: Adam Crymble Date: 28 July 2021

Actions Completed Since Previous Report:

- Hired & onboarded Digital Humanities Publishing Assistant @Anisa-ProgHist 
- Established Lesson maintenance workflow and started fixing lessons (@Anisa-ProgHist / @rivaquiroga )
- Hosted 2 UCL digital humanities students to help us with lesson maintenance & accessibility work @acrymble
- Have approved a £300 budget per publication for outreach activities. @acrymble to open ticket to discuss logistics of spending that money.
- New funded project with JISC (UK) and National Archives (UK) to support Call for Papers on data analysis lessons (@drjwbaker)

Actions Remaining Open Since Previous Report:

- Registering as a charity - paperwork submitted but not yet approved @drjwbaker 
- Copyediting setup in French - still on going @spapastamkou
- Copyediting setup in Portuguese - not yet commenced
- IPP recruitment. Now have 20 IPPs (goal is 40). @acrymble
- End of volunteering on 'services' to publications @amsichani still working with subteams. Making good progress.

Queries for the Editorial Board:

- When @jenniferisasi steps down as Comms Lead in December 2021, ProgHist would like to pass this to @Anisa-ProgHist as part of her paid work, and proposes eliminating the Comms Lead role as a voluntary position.

6-month focus:

- Lesson maintenance
- Copyediting setup
- Supporting @Anisa-ProgHist 
- IPP fundraising
- Charity registration
- End of volunteering

12+ month focus:

- Team-wide long term plan established

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc

Date: 28 July 2021

Actions Completed Since Previous Report:

- @walshbr closed #2006 (Adding PT to Twitter Bot)
- @jenniferisasi closed  #1945 (Lesson sequence banners in ES)
- #2106 is pretty much ready to merge once we decide on language to add to the blog to indicate that  we'll no longer have our html-proofer check the blog for links or html formatting. 

Substantive Actions Remaining Open Since Previous Report:
(Many of these will be discussed at our August Tech Team meeting next week #2216)
-  Discussed how to change initial lesson submission metadata at our last tech team meeting and Zoe still needs to setup meeting with managing editors #1995
- We opened #2072 to conduct an accessibility audit and @walshbr has done an enormous undertaking to get us most of the way there. We'll be discussing remaining issues at our next tech team meeting in August.
- @hawc2 has also done an amazing job leading #2030 which is an assessment of our current archiving of web links strategy. 
- @jenniferisasi is leading #2100 to make the menu bar fixed when you scroll
- Zoe is still planning to undertake a redesign our front page #2020 to hopefully make it more user friendly and multilingual friendly though she is waiting until we complete the accessibility audit
- Discussing whether @Anisa-ProgHist needs any help with this ticket  #2195 
- Zoe finally dealing with Transfer cloudflare management  #1981 with the help of @acrymble 
- Finalizing @walshbr retiring this summer 😢  #2214 and also onboarding @hawc2 officially to the Tech Team 🎉#2215


6-month focus:
- recruiting more Tech Team members
- Front page redesign
- Finish accessibility audit
- Adding more documentation to the wiki

12+ month focus:

- Review alternatives to Jekyll (is it time for a faster static site generator?)
- Grant application to support tech team activities
- Review of Github issues trends

**Comment by spapastamkou** [comment]
## FR Team Report 
by @spapastamkou on 28 July 2021

**Actions Completed Since Previous Report - New Actions:**
1 translated lesson reviewed and published 
1 translated lesson that was received is now under review
1 original lesson (2nd) that was received is now under review 
3rd original lesson proposal accepted - lesson to be received by end of September  


**Actions Remaining Open Since Previous Report:**  
FR Copy Editing Chart: in progress, now under final check (Sofia)
2 translations under review: 1 translator reviewing, 1 reviewed but subject to bug assessment / fix (Python 2 to 3) 
   
**Other**
1 team member would like to work on a solution for the XML / XSL lesson #1876 that requires some rewriting - has ideas - can work on both EN and ES versions - who should he discuss with? (subject to him finishing the editing of a translated lesson in FR, now in final stage before publishing)  

**Queries for the Editorial Board:**
none 

**6-month focus:**
Achieve more inclusivity for team members  

**12+ month focus:**
Work on targeted outreach 
Accomplish translation of Python series lessons ("task force" of 3 team members)

**Comment by jenniferisasi** [comment]
# Communications Team Report

By: @jenniferisasi 

Date: 28 July 2021

Actions Completed Since Previous Report:
- published mid year newsletter

Substantive Actions Remaining Open Since Previous Report:
- Front page redesign #2020 overlapping with @programminghistorian/technical-team 
- Change menu bar from static top to fixed top #2100 overlapping with technical-team 
- Process to avoid content overlap in original lessons in different languages #2141 (with [spreadsheet in-progress](https://docs.google.com/spreadsheets/d/1vrvZTygZLfQRoQildD667Xcgzhf_reQC8Nq4OD-BRIA/edit#gid=0))

6-month focus:
- @jenniferisasi to transition out of Comms leader position 
- so find a way to pass the role to @Anisa-ProgHist
- document main actions

**Comment by rivaquiroga** [comment]
## ES Team Report 
by @rivaquiroga on 28 July 2021

**Actions Completed Since Previous Report**
- 2 new original lessons published. We hitted the 50 lessons milestone :tada:
- we shortlisted the candidates for new editors

**Actions Remaining Open Since Previous Report:**  
- 3 original lessons under review
- 1 translation under review
- candidates interviews will be held during the first weeks of August

**3-month focus:**
- Onboard new editors

**Comment by anisa-hawes** [comment]
Dear @mariajoafana and dear all, 

Thank you for your time yesterday.

I have added the Minutes to our private repository. They are available for you to view via this link: 

https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2021/07_2021_ProjectTeamMeeting.md

Please let me know if you feel I have missed any important points, or mis-represented something which you said. I will be happy to make adjustments. 

Very best, 
Anisa

**Comment by acrymble** [comment]
@Anisa-ProgHist you've done a brilliant job. Just one very minor note that this line doesn't technically apply to the "Project Team" (only to ProgHist):

Quorum of 3 reached (per Article 9 of the Articles of Association).

**Comment by anisa-hawes** [comment]
Ah! Thank you, @acrymble! Didn't realise this. I will remove that statement.
