### ISSUE TITLE
Onboarding Checklist for Spanish language publication editor: Nicolás Llano

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2239]
This is an individual onboarding Editor checklist for Nicolás Llano (@nllano). ¡Bienvenido, Nicolás!

## Bienvenido

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB )
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project (@rivaquiroga)
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project (@acrymble)

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. The process will work better if you perform those tasks in the order they appear below:

### communication

- [x] set up a GitHub account and inform @JoshuaGOB of your username 
- [x] inform @JoshuaGOB  of your Google-activated email

You can add a comment below to inform him.

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let your Managing Editor know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions.
- [x] make a technical contribution on your own using those guidelines. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page. Please, make this contribution in only one pull request. If you are not sure how to do it, please let us know.
- [x] Read all sections of the [/contribuciones](https://programminghistorian.org/es) menu of the website, including author, reviewer, translator and editor guidelines.
- [x] (optional) Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### meet the extended team (optional)

- [x] (optional) Attend the next Project Team Meeting (late September at 9:00 am UTC-5, date to be confirmed in the following weeks). These meetings are mandatory for team leaders and optional for everybody else. Nevertheless, they are a good opportunity to meet the rest of the extended team, put faces to names, have a better idea about how your work as an editor contributes to the project, and help build the future of Programming Historian.

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by jenniferisasi** [comment]
I am going to upload an avatar photo for the blogpost; @nllano

**Comment by nllano** [comment]
Hey @JoshuaGOB  my email is llano.nicolas@gmail.com 
Thanks!

**Comment by nllano** [comment]
> I am going to upload an avatar photo for the blogpost; @nllano

Thanks @jenniferisasi

**Comment by rivaquiroga** [comment]
@JoshuaGOB, ¿es posible reenviar la invitación a GitHub a @nllano? Al parecer todavía no tiene acceso.

**Comment by JoshuaGOB** [comment]
Listo @rivaquiroga!

**Comment by acrymble** [comment]
Is this done @rivaquiroga ?

**Comment by rivaquiroga** [comment]
Yes 🚀
