### ISSUE TITLE
Anisa Website/Service Integration Training plan

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2298]
This is a checklist of website-inclined / Service integration things we need to work to invest in @anisa-hawes who will then help us document & share that knowledge with the right people when they need it, including through onboardings or professional development. At a minimum, I think she needs to know what all these do and how they work (and how to step in during an emergency). Please add to the list if I've missed things. I've tried not to include things I think @anisa-hawes already knows or manages!

- [x] Github pull request repair via command line #2227 🎉
- [x] Domain registration/hosting #1981 
- [ ] Technical Contribution Documentation (updates needed? -https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions )
- [x] Add/remove Github Jekyll/ph-submissions access
- [x] Google Group (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [ ] Add/remove editing access to shared Google Docs
- [x] Google Analytics
- [x] DOAJ (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] Sherpa / Romeo (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [ ] Netlify (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] Twitter (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] TweetDeck Manage Twitter access for our Team 
- [x] Twitterbot (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] YouTube (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] Perma.cc (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] Zenodo (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#zenodo)

We hope to finish this training / knowledge transfer by 31/12/2021

**Comment by acrymble** [comment]
@drjwbaker I believe DOAJ is a September archivist task. Would you be willing to train @anisa-hawes on what this involves, and make sure she also has access to any relevant login details?

**Comment by drjwbaker** [comment]
Did it already. Next one in March (I've been doing it every 6 months). Reminder is in the PH gmail, so I'll change it to remind myself to hand over to @anisa-hawes then.

**Comment by acrymble** [comment]
> Did it already. Next one in March (I've been doing it every 6 months). Reminder is in the PH gmail, so I'll change it to remind myself to hand over to @anisa-hawes then.

Ok I will update the service integration wiki to note that. Also noting that I don't have the password for this anymore so I'm going to remove my name from the list of password holders.

**Comment by anisa-hawes** [comment]
Thank you for co-ordinating this @acrymble! I have already got the credentials for Twitter and Perma.cc so I have checked these.

**Comment by anisa-hawes** [comment]
Just a note to let the @programminghistorian/portuguese-team & all others know that _Programming Historian em português_ is now listed on Sherpa Romeo! 

You can view the publication's entry here: https://v2.sherpa.ac.uk/id/publication/40243, and find our publisher information here: https://v2.sherpa.ac.uk/id/publisher/62625

**Comment by josircg** [comment]
Excelent news Anisa!

**Comment by DanielAlvesLABDH** [comment]
Great news @anisa-hawes! Many thanks!

**Comment by anisa-hawes** [comment]
@drjwbaker & I worked together this morning to create our 2021 citable deposit: https://zenodo.org/record/5645020#.YYQUt73P25M. We've updated the Service Integrations Wiki page with the latest information.

Next steps: we are in the process of setting up a generic project-owned GitHub account with webhook to Zenodo enabled. This account will be linked to the project email address too, rather than via one of ours.

**Comment by drjwbaker** [comment]
Further to this, can somebody with the right permissions (@ZoeLeBlanc?) please add https://github.com/proghist as a member of our repo? Context here that the github-to-zenodo webhook is connected to my personal account, which is a dependency issue, so @Anisa Hawes and I agreed to migrate to a generic github attached to the shared gmail.

**Comment by acrymble** [comment]
done @drjwbaker

**Comment by drjwbaker** [comment]
Request made to @zenodo per this ticket https://github.com/zenodo/zenodo/issues/826

**Comment by drjwbaker** [comment]
> done @drjwbaker

Any chance you could redo this @acrymble (or someone else with permissions). I hit the link whilst logged in with the wrong account. Very sorry!

**Comment by ZoeLeBlanc** [comment]
Just sent you another invite (this time to the Project Team so you would have access to multiple repos). Let me know if that works or not @drjwbaker !

**Comment by drjwbaker** [comment]
Perfect. Thanks @ZoeLeBlanc.

**Comment by drjwbaker** [comment]
> Just sent you another invite (this time to the Project Team so you would have access to multiple repos). Let me know if that works or not @drjwbaker !

@ZoeLeBlanc: so it looks like to do this, @proghist needs sufficient permissions to access the repo settings (especially https://github.com/programminghistorian/jekyll/settings/hooks). Any chance you could update the settings when you get a minute {not urgent though!}

**Comment by anisa-hawes** [comment]
Hello all, 

Who is the best person to introduce me to our Twitter Bot? 

December has arrived so quickly! I'm keen to gather the knowledge and skills listed above before the end of the year.

Should have clarified:

I already know where to find our Twitter Bot Google Sheet, how to add a new Lesson to the pipeline, and how to move a Retired Lesson to the "Deprecated" tab. Is there anything else I need to know @programminghistorian/technical-team?

**Comment by anisa-hawes** [comment]
I noticed that on the [Admin when team members step down](https://github.com/programminghistorian/jekyll/wiki/Admin-when-team-members-step-down) page of our Wiki, I am listed as responsible for removing access to our Jekyll repo and Twitter account. 

At the moment, I'm not clear on how to do this (or whether I have the admin permissions to do so). 

I tried to remove a former editor from the French team a few months ago, and didn't have the right permissions. Could someone double check if my Jekyll permission tier grants the options needed?

Closely related: I'm also not sure if I have the admin permission to invite someone to join our organisation of GitHub, or grant someone access to our shared Twitter account. 

Does anyone have time to show me?

**Comment by jenniferisasi** [comment]
> Hello all,
> 
> Who is the best person to introduce me to our Twitter Bot?
> 
> December has arrived so quickly! I'm keen to gather the knowledge and skills listed above before the end of the year.
> 
> Should have clarified:
> 
> I already know where to find our Twitter Bot Google Sheet, how to add a new Lesson to the pipeline, and how to move a Retired Lesson to the "Deprecated" tab. Is there anything else I need to know @programminghistorian/technical-team?

@anisa-hawes I think that should cover your responsibilities (although even adding a lesson is the task of the editor publishing the lesson). The bot itself is taken care of my the tech-team if something goes wrong (hope not, cos it was Brandon who created it). I don't think there is anything else to it, but happy to chat about it if you have any question.

**Comment by acrymble** [comment]
@jenniferisasi @anisa-hawes the purpose isn't so much who will fix it, but who has admin access and passwords to the bits of all the services we use. We're trying to make sure that no matter who retires from the project, we know all of the logins, what everything is for, etc.

At the moment a lot of these are distributed quite widely and attached to personal accounts in complicate ways.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. Yes, understood. I have the password for our shared Twitter account, but I don't think I have admin access?

**Comment by jenniferisasi** [comment]
> Thank you, @acrymble. Yes, understood. I have the password for our shared Twitter account, but I don't think I have admin access?

Let me look that up, but because we need to share private info, I'll touch base on Slack.

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi! I'm now set up on TweetDeck and can manage Team access + roles.
I've updated the documentation [here](https://github.com/programminghistorian/jekyll/wiki/Service-Integrations), including link to instructions for Managing Teams and Team Roles.

**Comment by anisa-hawes** [comment]
Apologies. Although I have the password for our shared YouTube account, I've just tested logging in and it has generated a verification code which appears to have been sent to a mobile phone. Whose mobile is linked? Is it yours @mariajoafana?

**Comment by drjwbaker** [comment]
That would be me I think. Usually when trying to share the gmail logins, we need to have a call where I tell the person trying to log in the codes I can see on my phone.

**Comment by anisa-hawes** [comment]
Ah! I see. I don't actually need to log in to YouTube now, I just wanted to test it out. Apologies!

**Comment by acrymble** [comment]
@anisa-hawes I think all of these tasks are now possible.

**Comment by anisa-hawes** [comment]
🎉 Almost ready to close this Issue! 🎉

Updates:

- [x]  Google Group

- [x] Google Analytics

Meeting with James next week to learn about:

- [x] DOAJ Done #2528! 
 
Will also ask JB about:

- [x] YouTube [I'm checking this off, as I have transferred this task to #2625]

- If we want to link the YouTube account to the new admin@ email, it looks like we can do so using these instructions: https://support.google.com/youtube/answer/3056283?hl=en-GB#. I think steps 1-12 under the heading Move your Brand Account to a different Google Account are the ones we need.

- [x] Add/remove Github Jekyll/ph-submissions access

- Although I am administrator of our Organisation here on GitHub, this isn't something I have permissions to do. Are you able to help with this @ZoeLeBlanc? 


- [ ] Technical Contribution Documentation TO DO this spring/summer 

- I'm planning to undertake a full clean-up/update of our Wiki this spring/summer 
- I'm aware that some general updates are needed, including to the Making Technical Contributions page (which still refers to Travis)

**Comment by anisa-hawes** [comment]
The Service Integrations Wiki page has been moved to our [Private Repo](https://github.com/programminghistorian/project-and-business-archive/blob/master/service-integrations/ProgHist-Service-Integrations.md).

I've left this note + link for Members in its old location.

**Comment by anisa-hawes** [comment]
While I am now a member of the Google Group (with my admin@programminghistorian.org email), while working with our new English team members today, I discovered that I'm not able to edit the shared Google Docs, i.e., the Concordance Document or invite others to be editors. @acrymble are you able to double check that I am set as an administrator?

**Comment by anisa-hawes** [comment]
Updates:

JB and I discussed the option of moving our YouTube account to the new admin@ email. I found these instructions: https://support.google.com/youtube/answer/3056283?hl=en-GB# and think steps 1-12 (under the heading Move your Brand Account to a different Google Account) will be the ones we need. However, our [currently advertised](https://programminghistorian.org/posts/education-and-community-lead) Education & Community Lead may be better placed than me to be the administrator of the YouTube account, as their responsibilities will include co-ordinating events, circulating and publicising our educational training materials. With this in mind, *I am going to leave this task un-checked on this list*. For now, the Service Integration document clearly states that the YouTube account credentials are links to [programminghistorian@gmail.com](mailto:programminghistorian@gmail.com) (which JB and AC both have the credentials for).

One of my tasks for the coming months will be to undertake a full clean-up/update of our Wiki, so *I am going to leave this task un-checked on this list* too and will open separate Issues if I need input when I update specific Wiki pages/sections.

One remaining ‘task’/aspect of training which I would like to resolve here, is whether [admin@programminghistorian.org](mailto:admin@programminghistorian.org) can be given credentials to manage access to our shared Google Sheets, specifically our [Twitter Bot](https://docs.google.com/spreadsheets/d/1o-C-3WwfcEYWipIFb112tkuM-XOI8pVVpA9_sag9Ph8/edit#gid=1625380994)
[Lesson Concordance](https://docs.google.com/spreadsheets/d/1vrvZTygZLfQRoQildD667Xcgzhf_reQC8Nq4OD-BRIA/edit#gid=0) and
[Reviewer Tracker](https://docs.google.com/spreadsheets/d/1EMQyVpIYnWjNr4hEQDDilkUl28gGPA2gSLjp61_AFgM/edit#gid=456827024) which I have found I can neither edit myself nor invite editorial colleagues to edit.

**Comment by drjwbaker** [comment]
> I am going to leave this task un-checked on this list

Totally agree with your rationale here.

**Comment by acrymble** [comment]
@anisa-hawes I've sent you editor invites on those spreadsheets. I don't know if it's possible to change the owner of a document (which is programminghistorian@gmail.com)

**Comment by acrymble** [comment]
@anisa-hawes just wanted to check to see if this list is still relevant, or if we should make a new one for the coming year?

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. I think it makes sense to close this, and set up some new goals for the months ahead.
