### ISSUE TITLE
Onboarding Checklist for Portuguese language publication editor: Eric Brasil

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#2302]
This is an individual onboarding Editor checklist for Eric Brasil @ericbrasiln. Bem vindo Eric!

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@JoshuaGOB)
- [x] Our Github Repository so you can upload materials to the site (@JoshuaGOB)
- [x] Partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project. (@DanielAlvesLABDH) 
- [ ] Invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional. The process will work better if you perform those tasks in the order they appear bellow:

### communication

- [x]  set up a GitHub account and inform @JoshuaGOB of your username (mandatory; use the 'Comment' box on this page)
- [x] inform @JoshuaGOB of your Google-activated email (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github / jekyll website.

- [x] Read the 'Onboarding Process for New Editors' wiki page: https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
- [x] make a technical contribution on your own using that ticket. This will normally be adding your bio to the [/data/ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml) file, and uploading a square black and white avatar (.png) of yourself to [/avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the [/contribua](https://programminghistorian.org/pt/contribua) pages of the website, including author, reviewer, and editor guidelines (directrizes de autor, revisor e editor)
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by ericbrasiln** [comment]
Thanks, @DanielAlvesLABDH 
I am very happy to be part of the team.

@JoshuaGOB my gmail is profericbrasil@gmail.com

Until Monday I'll create a branch called `issue-2302` and then I'll submit the PR with the changes to the /data/ph_authors.yml file and my avatar.

**Comment by acrymble** [comment]
@DanielAlvesLABDH we will do invites to the ProgHist ltd less frequently, and normally after the person has started doing editorial work. The checklist says this will be done within 2 weeks, but please don't let that prevent you from closing this ticket.

**Comment by DanielAlvesLABDH** [comment]
Following @acrymble suggestion I'm signaling @anisa-hawes here so that she could help @ericbrasiln having access to the Google Group email. Thanks!
After that I will scheduled a meeting with Eric so he can start to known how PH works and how the PT team is developing.

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. Unfortunately, I'm not part of the Google Group myself yet. There is a technical hold-up related to the credentials of our Cloudflare account , see #1981 and #1761. Zoe and I are meeting this Friday 8th October to work on resolving the issue, but in the meantime, I will need to ask if @JoshuaGOB or someone from the @programminghistorian/technical-team if they could please invite @ericbrasiln to the Google Group? Eric's email address can be found [above in this thread](https://github.com/programminghistorian/jekyll/issues/2302#issuecomment-927221982). Thank you.

**Comment by DanielAlvesLABDH** [comment]
Thank you @anisa-hawes

**Comment by jenniferisasi** [comment]
I just added @ericbrasiln to the google group

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi!

**Comment by DanielAlvesLABDH** [comment]
Many thanks for this @jenniferisasi

**Comment by DanielAlvesLABDH** [comment]
@ericbrasiln agora é oficial! Vamos combinar uma reunião por estes dias para dar inicio à colaboração. Bem vindo! Abraço

**Comment by ericbrasiln** [comment]
Thanks, @jenniferisasi !
Obrigado pela acolhida, @DanielAlvesLABDH 
Podemos marcar para a próxima semana. Abraços

**Comment by DanielAlvesLABDH** [comment]
Sendo assim vou dar por concluído este processo e encerrar este ticket. Obrigado a todos. Thanks to to all. The ticket will be closed.
