### ISSUE TITLE
Onboarding Checklist for English Language Publication Editor: Giulia Taurino

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2475]
This is an individual onboarding Editor checklist for Giulia Taurino (@giuliataurino). Welcome, Giulia!

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do:

- [ ] Set up initial meeting with your Managing Editor @svmelton and assign an initial lesson to edit with a mentor
- [x] @svmelton will invite you to our #ph-english Slack channel
- [x] @anisa-hawes will help you to add your profile to our website via our Jekyll Repository
- [x] @anisa-hawes will introduce you to our Submissions Repository 
- [x] @anisa-hawes will show you the Project Board we use to track lessons as they progress
- [x] @ZoeLeBlanc will add you to our Github Repository so you can upload materials to the site
- [x] @JoshuaGOB will add your Google email to our list

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. The process will work better if you perform those tasks in the order they appear below:
- [x] Provide/set up a Google-enabled email address for our Google Group
- [x] Provide/set up a GitHub username for our Submissions Repository
- [x] Read the [author, reviewer and translator guidelines](https://programminghistorian.org/en/contribute) pages of our website 
- [x] Read the [Privileges and Responsibilities of Membership page of our Wiki](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership)

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by svmelton** [comment]
Hi @JoshuaGOB! Giulia's email is giulia.taurino89@gmail.com.

**Comment by svmelton** [comment]
Just a note that it looks like Giulia is the only one missing on the Google group @JoshuaGOB. Thanks!

**Comment by JoshuaGOB** [comment]
Sorry for the oversite @svmelton and @giuliataurino. I must have closed the tab between the human verification and the additional "add member" button pressing. Welcome @giuliataurino!
