### ISSUE TITLE
Onboarding Checklist for new French ME: Marie Flesch

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2713]
This is an individual onboarding Editor checklist for Marie Flesch: @marie-flesch. Bienvenue, Marie!

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What the PH team will do:

- [x] @anisa-hawes will help you to add your profile to [the Project Team pages](https://programminghistorian.org/fr/equipe-projet) of our website
- [x] @anisa-hawes will introduce you to our Jekyll repositories
- [x]  @anisa-hawes will introduce you to our ph-submissions
- [x] @ZoeLeBlanc will add you to our GitHub organisation so you can contribute to the site
- [x] @anisa-hawes will add you to our Google Group
- [x] partner you with an existing editor so that you can acclimatise to the project (@spapastamkou)

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. The process will work better if you perform those tasks in the order they appear below:
- [x] Provide/set up a Google-enabled email address for our Google Group
- [x] Provide/set up a GitHub username for our Submissions Repository
- [x] Read the [author, reviewer and translator guidelines](https://programminghistorian.org/fr/contribuer) pages of our website 
- [x] Read the [Privileges and Responsibilities of Membership page of our Wiki](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership)
- [x] Read the [Code of Conduct](https://github.com/programminghistorian/jekyll/blob/gh-pages/CODE_OF_CONDUCT.md)

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by spapastamkou** [comment]
@anisa-hawes I opened this mostly to get us started (and to prepare your welcome back from leave:). I combined, for the lists, the most recent issues of onboarding the EN editors and the issue of Sarah's onboarding (a bit). We should exchange between us to add further tasks or edit them.
(And I should add: thanks!)

**Comment by spapastamkou** [comment]
I asked Marie for her preferred email and a github username, will provide them here once they are in.

**Comment by spapastamkou** [comment]
preferred email is: marie.flesch on gmail (@anisa-hawes @acrymble)

**Comment by anisa-hawes** [comment]
Hello Marie, 

Welcome to the project! ✨ 

I am sending you an email to organise a time connect. I'd like to support your orientation by introducing you our Submissions and Jekyll repositories, and explaining a bit about how we work within these spaces.

I'd also like to help you to add your profile photo (300 pixels square, greyscale image) and bio to [our Project Team page](https://programminghistorian.org/fr/equipe-projet). 

Looking forward to working with you!

Anisa

--

**Actions:**

- [x] Email Marie to organise first orientation session

**Comment by anisa-hawes** [comment]
Marie and I have arranged to meet for an initial orientation session on Wednesday 9th November.

In our session, we'll work through the following tasks/conversations:

- [x] Introduce Jekyll Issues
- [x] Introduce the Pull Request system
- [x] Add Marie's profile + portrait to the Project Team page
- [x] Introduce ph-submissions

**Comment by spapastamkou** [comment]
added MF's GitHub username in the initial comment - cc @anisa-hawes

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou!

@ZoeLeBlanc could you invite Marie Flesch: @marie-flesch to our organisation on GitHub? Thank you! 🙂

**Comment by spapastamkou** [comment]
hi there! I hope it is ok for Marie's @marie-flesch access on our GitHub repository so that she can make the best out of her meeting with Anisa on 9 Nov? @ZoeLeBlanc could you confirm this, please? - or alternatively could you give her access in the days to come so that I can work with her on small practical tasks? Thanks a lot!

**Comment by ZoeLeBlanc** [comment]
Just added her @spapastamkou and @anisa-hawes ! Sorry for not seeing this earlier! Welcome to the team @marie-flesch 🥳

**Comment by marie-flesch** [comment]
thanks @ZoeLeBlanc  :)

**Comment by spapastamkou** [comment]
cheers @ZoeLeBlanc, the timing is perfect :-)

**Comment by anisa-hawes** [comment]
Marie and I have organised to connect for a follow-up orientation session (to focus on ph-submissions) on Wednesday 23rd November.

**Comment by anisa-hawes** [comment]
I am closing this Issue, although (of course) I will still be around to support @marie-flesch during the coming months. 

Warm welcome! ✨
