### ISSUE TITLE
Sofia Sabbatical

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2793]
I am opening this issue to organize my sabbatical. It should start as soon as possible in January but I will update about the exact date in the coming days and no doubt after Christmas. The sabbatical should last 3 months. I will list here the issues I am (co)assigned in order to close them in the coming days or organize these that cannot be closed shortly.  

  **All team, trustees**
- [x] Software citation bis #2552 @anisa-hawes to make the necessary clarification to author guidelines
- [x] Board of Trustees Meeting: Monday 16th January 2023 #2778 
**Editorial**
- [ ] [Evaluation de leçon: Concevoir une recherche en sciences humaines en termes de données](https://github.com/programminghistorian/ph-submissions/issues/459)
- [ ] [La lecture multi-échelles de données structurées](https://github.com/programminghistorian/ph-submissions/issues/482) 
**Managing Editor tasks**
- [ ] [AI for automated transcription of Historical Documents (PH/TNA/JISC)](https://github.com/programminghistorian/ph-submissions/issues/421) - publish lesson, train to the tasks of ME 
- [x] [Relecture de traduction : Construire un site web statique avec Jekyll et Github Pages](https://github.com/programminghistorian/ph-submissions/issues/449) - add a report before closing the issue
- [x] Update list of contributors and roles FR team (Gsheets)

**Comment by acrymble** [comment]
Hi @spapastamkou have you chosen a date yet?

**Comment by spapastamkou** [comment]
@acrymble I do my best for the sabbatical to start by the 25th and in any case no later the the 30th January.

**Comment by spapastamkou** [comment]
Dates of sabbatical: 13 February - 13 May 2023. 
I will assure the editorial follow up of the two lessons I am editor of during this time.
