### ISSUE TITLE
evaluation of ongoing design work

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#414]
I'm creating a ticket for a dedicated thread to identify and discuss issues with the new css/layout/design work i've been doing at http://fredgibbs.net/jekyll/.

In particular, there is one code issue that needs to be evaluated. I have coded the nav bar to get language info from https://github.com/fredgibbs/jekyll/blob/gh-pages/_data/snippets.yml. i think this is the cleanest way to maintain translations that appear in include files, but others, esp @wcaleb and @mdlincoln should double check that this approach makes sense. If it's OK, then we will probably need the topics.yml file to be organized (and translated) in a similar way so the spanish lessons page will work like the new english one from @amandavisconti.

I have edited many of our instruction pages to streamline the prose--cumulative editing over many years has resulted quite verbose instructions! I haven't changed (at least on purpose) any workflows or policies. The biggest change was that I removed a bunch of the generic markdown instructions from the author-guidelines page since we have a tutorial on that now. Our site specific stuff is still there of course. 

Looking forward to hearing your suggestions!

**Comment by mdlincoln** [comment]
Thanks @fredgibbs - I'll take a look this weekend.

**Comment by acrymble** [comment]
Really love your new work here @fredgibbs .

I havn't had a chance to go through it all yet. But a few quick comments:

- [x] will your changes to the text be easy for the Spanish team to incorporate without re-translating everything?
- [x] On front page (http://fredgibbs.net/jekyll/) I find the blue and teal band too similar in colour to link colours.
- [x] re: footer. The ISSN number has been removed. This seems like the least obtrusive place to put it (though I also think that should be in the new 'about' page somewhere). I'm not sure it's relevant that we're hosted in Github. And 'See Change History' seems a bit jargony. Will enough people understand that?
- [x] On about page, the 'Editorial Board of the Programming Historian' has been removed. I appreciate you might not like that term, but there are times when we need to fill in forms that require a name of a publisher (eg, when submitting material to the British Library). I think it's a good idea to encourage consistency in that.
- [x] wondering how we can make the Spanish link more obvious without being obtrusive.

Overall, very great stuff in my opinion.

**Comment by amandavisconti** [comment]
This looks amazing! I've been out moving between states and starting a new job this month, but I'll wrap up the dangling pieces of my lesson page work before the May call and let Fred know when they're ready for incorporation.

**Comment by jerielizabeth** [comment]
The design looks really great, @fredgibbs! I particularly love the font choice. Serifs are coming back!

One css thing I noticed while clicking through. The spacing between the header and the content assumes that the lesson leads off with a header. On lessons where it doesn't (such as http://fredgibbs.net/jekyll/lessons/intro-to-augmented-reality-with-unity), the text crowds up to the bottom bar.

**Comment by mdlincoln** [comment]
The same issue that @jerielizabeth pointed out applies also on the main pages, e.g. the image on the homepage at <http://fredgibbs.net/jekyll/> abuts the header.

**Comment by fredgibbs** [comment]
Thanks for the initial feedback! I will continue to post updates on this thread so we know where everything stands. Anyone have opinions about what @acrymble suggests? Otherwise I will make the changes as requested. 

As the recent design work concludes, we should develop a plan for incorporating the pages/code at  http://fredgibbs.net/jekyll/ into the main (gh-pages) repo. It might be worth documenting that here. 

As far as I can tell, per my earlier comment, the limiting factor is the automated spanish lessons page (and the necessary yml files). Other than that, it's basically done. Because I’ve changed so many pages (in minor but crucial ways, like the layout name in the yaml headers), it would be preferable to merge these into the code base sooner than later in order to minimize conflicting changes as we continue to maintain and develop the site.

**Comment by mdlincoln** [comment]
@fredgibbs This redesign looks wonderful!

It would be great to have updates posted here. I did a pass through the currently-open issues here and collected everything that I thought was related to your redesign under one "milestone". If you see anything that can be closed, please do so - or let me know if there's anything that needs an extra pair of eyes.

You are right that we should hold off further technical work on the published page until we get yours and @amandavisconti's changes merged in.

How does this order of operations sound?
1. @fredgibbs if you can merge the current gh-pages branch back on to your fork, it'll make the eventual PR much easier. I tried running a test merge like that on my own machine, and there were only a few conflicts.
2. Once @amandavisconti finishes remaining lesson page work, @fredgibbs you should merge _that_ work on to your branch. (I haven't tried a dry-run of that so I'm not sure how many conflicts there will be.) 
2. Use this combined preview to check for final bugs, and do any further work required to get Spanish pages operating appropriately.
3. Merge @fredgibbs branch back on to the live gh-pages one.

**Comment by acrymble** [comment]
I'm having trouble telling what's been changed in the text. I'm a bit concerned that this is a bit of an omnibus pull request rather than a design one. Can we separate design from text overhaul? Especially given the ongoing discussions about what the project is or should be?

**Comment by fredgibbs** [comment]
you're probably having trouble because not much has changed. in any case, i've tried to keep the design and copy changes separate in the commit history in the fork. the biggest copy change was the new about page (besides the markdown instructions mentioned above), but mostly that was putting the peer review section first, not trying to frame the project in a new way. @acrymble, you've already mentioned the "published by editorial board" statement which i will restore; and i will happily undo any other edits. in general, almost all text changes have been fixing typos or removing duplicate statements.

**Comment by fredgibbs** [comment]
thanks @mdlincoln! i agree this is the best approach. depending on the how essential future work from @amandavisconti is before launching the new page, it might be useful to pull in my fork (after syncing), and have future lessons page work go from there (this is assuming all lessons stay in the _lessons folder), so that we're not co-developing the lessons page and include files any longer than absolutely necessary.

**Comment by acrymble** [comment]
@fredgibbs ok, I'll put text comments here then, if that's easier. I didn't want to hold up the technical stuff with text-y stuff.

A few more comments (all very minior):

- [x] The English 'contribute' doesn't have a subsection for 'translate' as there is on the Spanish page. I think we should have that in both versions. Who knows if someone reading the English site might want to translate?

- [x] The contribute drop-down - I think I'd use 'author's guidelines', 'reviewer's guidelines', 'editor's guidelines' as the drop down options, as these are the actual titles of the pages. I also wonder if 'suggest a correction' or something like that might be better than 'feedback', but not wedded to that.

- [x] The link to 'submission process' on the 'contribute' page doesn't work.

- [x] The top of the 'Editor Guidelines' page looks different (less pretty) than the 'Reviewer's Guidelines' page.

- [x] On the individual lesson pages: should 'modified' be 'last modified'? And if it has never been modified, should that say something clearer like 'this lesson has not been modified since publication'? Related to that, do we want to make a note of how many times a lesson has been revised? And should 'Updates by' be a third category after 'Reviewers'?

- [x] Is there somewhere that we can put the 'version of record' for download within the individual page design header? Maybe also a DOI for that, if we go that road?

- [x] On the individual page, I don't see the author's name.

- [x] On the individual page, next/previous links need re-implementing (or hard coding) #321 

- [ ] ~~On the individual page: are we going to use peer reviewed/cc-by icons in header?~~ #308 

- [x] on the Lesson Index page, the buttons all seem to work fine, but no visual indicator of what categories each falls into, so difficult to understand what's happening. Eg, sort by difficulty puts them in an order, but no indication of where thresholds are crossed between difficult/medium, or even how many categories there are. Not sure how to fix that without cluttering.

- [x] on the Lesson Index page: the grey categories (sub-categories?) may need some more user testing. For example, we have Python but no R, but not clear why. How do we make sure this doesn't blossom out of control in future? (#193)

- [x] Project team page: how can we implement the new 'teams' model? #303 

- [x] Re new 'version of record' and 'modified version' model. I think a paragraph on the 'about' page should be sufficient to outline this for users and authors. Maybe: "Once a lesson has passed through peer review been published, a 'version of record' will be created which will be assigned a DOI and made downloadable via a PDF. This is the author's contributed work. In order to promote long-term sustainability, the editors may choose to update the lesson as needed in future. If this is the case, the live version of the lesson will differ from the 'version of record'. In order to make clear the distinction between the author's version of record and the editor's modified version, all modified lessons will begin with a statement: this lesson has been updated by XXX, who takes responsibility for the changes. The author's published version is available for download at YYY" (or something like that). #417 #410

**Comment by ianmilligan1** [comment]
@fredgibbs I've gone through the site and I think it looks great. Just to reiterate what others have said: it's beautiful, well laid out, and brings substantial improvements in both feel, look, and ability to interact with the lessons. Sincere kudos. 

Some minor thoughts:
- I like "feedback" better than "suggest a correction." The latter seems more daunting than the former.
- Agreed with "last modified." I think if the modified and published dates are the same, people will figure it out, but if it's trivial then removing the field might be ideal. 
- As Adam noted, the author name is missing on individual pages (i.e. [this one](http://fredgibbs.net/jekyll/lessons/editing-audio-with-audacity))
- I like the minimalist headers, I think license belongs in footer;
- The note that we're peer reviewed can just belong in the 'about' page, I don't think it belongs on individual lessons;
- I think versions of record should also go into the footer. My guess is that this will be a niche case, for some authors and maybe the occasional person who needs an older lesson;

I guess I just want to emphasize that I like the minimalist model. Let's not clutter up the header, and let's also make sure we keep with no pop ups, etc. 😄 

Great stuff!

**Comment by mdlincoln** [comment]
Did I miss a decision that the PDF-version-of-record update is going to come out as part of this design update? And not as an enhancement that we work on _after_ merging in these large design changes?

I'd prefer that they be in separate milestones, just to simplify merging, as well as give us more breathing room to think about how to engineer versions-of-record as well as decide & communicate our policy about them. We've already got enough work to do merging @fredgibbs and @amandavisconti changes.

**Comment by ianmilligan1** [comment]
Sounds good to me @mdlincoln!

**Comment by acrymble** [comment]
@mdlincoln no you didn't miss anything. Just thinking in terms of designing in things we know are coming rather than trying to fit in later.

@ianmilligan1 I agree, I really like the minimalism. Is this too obtrusive? (Sorry I didn't know your font @fredgibbs)

![screen shot 2017-05-02 at 18 11 48](https://cloud.githubusercontent.com/assets/646647/25630233/51771870-2f64-11e7-813f-e71392866050.png)

**Comment by mdlincoln** [comment]
Further clarification to the proposed merge flow re: #193 

@amandavisconti will submit her changes via pull request to @fredgibbs repository. Once merged there, we can all preview the combined changes at http://fredgibbs.net/jekyll/

**Comment by amandavisconti** [comment]
@mdlincoln @fredgibbs Just submitted a pull request for my finished #193 work.

**Comment by mdlincoln** [comment]
https://github.com/fredgibbs/jekyll/pull/2

**Comment by walshbr** [comment]
A bit late, but the design work revamps here have been very useful while putting together the dataset for the Twitter bot. The abstracts are a great introduction, and I really like the way the metadata is laid out here.

**Comment by arojascastro** [comment]
Apologies if this has been discussed already somewhere else, but please keep in mind that in the Spanish version we should display metadata for the original lesson (if possible with a link, which at the moment is not present) and metadata for the translations. Thanks.

**Comment by mdlincoln** [comment]
I believe @fredgibbs has now successfully merged @amandavisconti's lesson page changes into the overall redesign: http://fredgibbs.net/jekyll/

Can everyone take another look through to check for issues?

I'd also like to close any outstanding related tickets for [this redesign milestone](https://github.com/programminghistorian/jekyll/milestone/1)

**Comment by wcaleb** [comment]
This looks fantastic @fredgibbs and @amandavisconti! Great work!

After a brief discussion on one of our last calls re: the project title #405, I proposed [the following style guide](https://github.com/programminghistorian/jekyll/issues/405#issuecomment-298048344) that most of the team supported, which would keep "The Programming Historian" in our masthead. In the current redesign, though, it looks like that hasn't been implemented yet. (Not sure if @fredgibbs was ever looped in on this discussion, other than on the comment on issue ticket.)

**Comment by wcaleb** [comment]
Also, it looks like the "See change history" link in the footer of lessons just links to the repository's commit history, rather than to the commit history of the specific lesson (as on the current site).

**Comment by acrymble** [comment]
I converted my two comment threads into checklists. It may be that not everything gets addressed in this (eg, new features).

**Comment by fredgibbs** [comment]
i checked off everything that's been addressed or for which i've issued a new ticket (either for redesign or version of record milestone). but everything should be accounted for on this ticket, so i'm going to close it so that other conversation goes into more specific tickets.
