### ISSUE TITLE
Editorial Meeting Agenda - 9/28/17

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#596]
Date and time TBD. Feel free to add to the list below as issues become substantial and apparent.

- [ ] #595 - Annual Zenodo Dump - @drjwbaker will draft some copy for this for discussion.
- [ ] #536 - Deprecation Policy Discussion - @mdlincoln will draft the policy.
- [ ] #579 - Community Engagement on PH - wanted to discuss further with rest of board.
- [ ] #576 - Planning for Community Discussion on PH goals - wanted to discuss further with rest of board.
- [ ] #552 - Conversation about goals for PH - survey discussion follows up on this.
- [ ] #534 - Sustainability conversation - @alsalin is drafting

**Comment by acrymble** [comment]
has the date been set for this yet?

**Comment by walshbr** [comment]
Sorry @acrymble - thought I had set 11 days ago, but accidentally set to the current date at that time. Thursday, Sept. 28th has been the agreed upon date. I'll ping the group to remind in case people were watching this space.

**Comment by ianmilligan1** [comment]
Please accept my regrets again but baby Auden isn't well behaved on conference calls. I'll be back on full duties by late October.

**Comment by walshbr** [comment]
My quick notes from the talk - particular actionables listed at the top comment of the ticket. Feel free to comment if I mischaracterize anything.

#595 - Annual Zenodo Dump - general thoughts were that it was worth pursuing and drafting a policy for larger discussion with the group. @drjwbaker will draft a policy for further discussion. Relevant notes: Zenodo does not give DOI's for individual lessons. So this would be an archival approach for the project as a whole, not for individual lessons. @drjwbaker and @mdlincoln expressed concern that we be careful to make sure that people knew this in language on the site.

#579 - Community Engagement on PH - @drjwbaker raised concerns (even though he supports it in principle) that the wiki approach could be very time consuming. He suggested that such a model would need a community engagement person in charge of it, and it might take more bandwidth than we'd be able to give. But more generally, we should decide how we wanted to prioritize this in relation to #576, both of which were community engagement tasks and both of which will take time.

#576 - Planning for Community Discussion on PH goals - @drjwbaker  - suggested that we only put things in the survey, if we do one, that we are prepared to follow up on. And that we would need a clear strategy for administering it over a long period of time, in a way that encourages new communities to engage with it. Really commit to the idea, which we could then use as material for followup research projects. Good use of the survey might be to gauge community interest in particular ideas that had come up in the editorial conversations - like exploring links among lessons.

#552 - Conversation about goals for PH - @mdlincoln thought it would be useful to clarify what the actions that can come out of such a conversation. Seemed clear that engaging the community was one response. And engaging the community (through the survey) in the mission statement on the Programming Historian splash page is another option. Could be a good opportunity to gauge how we define what we do vs how the community defines what they do.

#536 - Deprecation Policy Discussion - @mdlincoln will do this sometime in the next couple weeks.

#534 - Sustainability conversation - @alsalin is still drafting some things, but we talked about this a bit in her absence. I'll drop more thoughts in that ticket, but we discussed the importance of prioritizing sustainability at various stages of the intake process - authoring, reviewing, editing. And how #536 and #534 can work to those ends.

And more generally, we discussed the timing of the doodle for the editorial meetings. I'll send the doodle for the following month out sooner, shortly after each month's call.

@drjwbaker also reiterated that he won't be taking any new lessons until after the new year, but he would appreciate following the editorial process along with someone closer to that time.
