### ISSUE TITLE
Editorial Meeting Agenda - 10/25/2017

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#617]
Date TBD - 5PM British, 12PM Eastern US, 9AM Pacific US last week of the month. 

Feel free to drop tickets here as they become substantial and apparent.

- [x] #612 Retirement Policy and Sustainability Strategy draft language
- [ ] #620 Suggested Workflow for updating translations
- [ ] #626 and #630 Editing via direct commit or PR
- [x] #619 Editorial Board diversity policy
- [ ] #595 Annual Zenodo Dump
- [ ] #430 DH 2018 presence

**Comment by drjwbaker** [comment]
Review https://github.com/programminghistorian/jekyll/issues/595#issuecomment-333138904

**Comment by acrymble** [comment]
#430 DH 2018 presence
#534 Sustainability Strategy
#619 Editorial Board diversity policy

**Comment by vgayolrs** [comment]
#620  Suggested Workflow for updating translations

**Comment by walshbr** [comment]
Date set for 10/25/17.

**Comment by drjwbaker** [comment]
Re conversation at #626, adding an agenda point on pushing minor edits.

**Comment by mdlincoln** [comment]
I just updated the link for sustainability & retirement policy to point to the active PR - all discussion should be based around that draft text.

**Comment by walshbr** [comment]
Actionables - 

#612 - English text can be considered set. @mdlincoln will ping Spanish team to begin translating. And we'll aim to regularly try to have proactive conversations about sustainability issues among ourselves as we try to act in accordance with the guidelines.
#620 #626 #630 - moving to all text changes being done by pull requests. @mdlincoln will experiment with closing our master branch to direct commits to enforce all changes by PR. @ianmilligan1 will draft documentation for how to do PR's. @drjwbaker suggests we revisit in a month after making the change to ensure we're happy with it.
#619 - agreed that it should be done and publicly stated. @acrymble will draft language.
#595 - @drjwbaker will start to implement. And have his role on the project reflect this.
#430 - people going to DH2018 will have a separate conversation about how we can be involved.

Also raised - relationship between Spanish team and the rest of the editorial board. Ie - are they expected (or, really, able to take on given their translation responsibilities) the editing of lessons more generally. Will open another ticket for that discussion.
