### ISSUE TITLE
Editorial Meeting Agenda - 11/28/2017

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#644]
11/28/2017 - 5PM British, 12PM Eastern US, 9AM Pacific US last week of the month.

Feel free to drop tickets here as they become substantial and apparent.

- [x] #595 Annual Zenodo deposit (I can't make the meet, but would appreciate a thumbs up / feedback on https://programminghistorian.org/about and https://github.com/programminghistorian/jekyll/issues/595 then I think we are pretty much ready to close)
- [ ] #612 Status of translations for retirement policy
- [x] #658 YAML check for author names (this is ready to be merged, I just need someone to sign off on the review - @mdlincoln)
- [x] #623 / #625 Javascript problems on the Spanish lessons index page (help needed!)
- [ ] #636 Any further action needed on clarifying Spanish editorial team responsibilities?
- [x] #620 - check in now that we've been doing PR's for all changes for a bit. Any needs? Difficulties? Continue for now?
- [ ] #579 #576 - anyone willing to take these on? If not, should we table the survey/outreach until we have a couple people come back from hiatus so we have more bandwidth?

**Comment by walshbr** [comment]
@amandavisconti will take a look at #623 and #625. Will comment on #579 and #576 on their respective tickets.
