### ISSUE TITLE
Editorial Meeting Agenda - 1/22/18

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#678]
Sorry for the delay in getting this out! Drop anything below that you would like.
1/22/2018 - 5PM British, 12PM Eastern US, 9AM Pacific US last week of the month.

- [x] Welcome new members
- [x] #651 Language Independence
- [x] #612 Lesson Retirement Policy language (status update on translation?)
- [x] India (James/Adam)
- [x] #681 Copy Editing
- [x]  #619 Editorial Board Diversity Discussion
- [x] Update Team's page with new member's bios (Antonio)
- [x] #576 and #579 Community engagement - made notes to revisit in the new year to see if there is interest in pursuing them.

**Comment by arojascastro** [comment]
- [ ] Update Team's page with new member's bios

(I'll try to revisit issue #651 this weekend, but I cannot promise a draft for Monday. I think the problem needs further documentation and reads, it needs some reserach... so any help is welcomed!)

**Comment by mdlincoln** [comment]
I may need to log out of this meeting a bit early, so I'd appreciate covering #651 and #612 early if possible :)

**Comment by drjwbaker** [comment]
@mdlincoln Well they are at the top.. :)

**Comment by acrymble** [comment]
I'd like to discuss #681 - copy editing

**Comment by jamotilla** [comment]
Hi, unfortunately i won´t be able to attend the call, at this time i´ll be teaching

**Comment by amandavisconti** [comment]
I'll need to miss the call to work toward a grant deadline. (@mdlincoln Haven't had a chance to look at #623 as you requested yet, but intend to—hopefully before the February call.)
