### ISSUE TITLE
Editorial Meeting Agenda - 2/19/18

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#708]
Working agenda for the call Monday, 2/19/2018 - 5PM British, 12PM Eastern US, 9AM Pacific US. Drop items in here for discussion as they come to mind.

- [ ] #378 Further Translations (do we have capacity to support French translation?)
- [ ] #499 blog post on scoping lessons (should we skip this, or do it?)
- [x] #714 ready to be merged
- [ ] #619 Retaining balance with Amanda leaving
- [ ] Sponsorship?
- [ ] #691 Windows & Jekyll bug
- [ ] #698 DOAJ XML (waiting for action by @acrymble ?)
- [ ] #686 - continue throwing things on there.

**Comment by acrymble** [comment]
#378 Further Translations (do we have capacity to support French translation?)
#499 blog post on scoping lessons (should we skip this, or do it?)

**Comment by drjwbaker** [comment]
#619 Retaining balance with Amanda leaving

**Comment by drjwbaker** [comment]
NoIssueNo: Sponsorship

**Comment by walshbr** [comment]
Actionables:

- [ ] #378 Further Translations - @acrymble will take a first run at some text that reflects the amount and areas of work involved with new translation projects so that others can comment.
- [x] #499 blog post on scoping lessons (should we skip this, or do it?) - @acrymble will open a PR to add the blog post to the site. 
- [x] #714 ready to be merged
- [ ] #619 Retaining balance with Amanda leaving - @drjwbaker will circulate an email to the group suggesting we think about bringing someone else onboard.
- [ ] Sponsorship? - @drjwbaker will continue working on language in advance of posting a ticket about the discussion.
- [ ] #691 Windows & Jekyll bug  - @mdlincoln will take a look at this.
- [ ] #698 DOAJ XML (waiting for action by @acrymble ?) - @acrymble will work on separating credentials from his personal account.
- [ ] #686

Misc -  

I'll take a look at the AR / Unity bug discussion. 
I'll circulate something about a scheduling discussion. 
Desire was expressed for a place to post all the different things that we've submitted to based on the PH so as not to accidentally overlap. Made a ticket at #721
