### ISSUE TITLE
Editorial Meeting Agenda - 3/29/18

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#729]
Working agenda for the call Monday, 3/29/2018 - 5PM British, 12PM Eastern US, 9AM Pacific US. Drop items in here for discussion as they come to mind.

- [x] Introductions
- [ ] #721 - standing call to update ticket with new research or submissions about the project
- [ ] Sabbaticals - how long are they? so that we have a sense of our capacity.
- [ ] #651 - Internationalization and localization
- [ ] #724 - Sponsorship
- [ ] #730 - Discussion on DH and Institutional Credit
- [ ] #698 - How to list ES publications on DOAJ
- [x] Making a presence at DH2018 (James) - related to #760 
- [x] #751 Nature of proposals we look for
- [ ] github training for editors (@acrymble)
- [ ] French editorial team.

**Comment by acrymble** [comment]
Can we have an item about sabatticals? I know we have a couple of people on sabbatical, but I don't think we know how long they need. I think it would be helpful if that could be expressed so we know what our capacity is.

**Comment by arojascastro** [comment]
Can we re-adress Internationzational and localization #651 ? I guess by March we will have some new inputs / ideas?

**Comment by acrymble** [comment]
#724 and #730

**Comment by drjwbaker** [comment]
On #730, we need to discuss if we want the ES dates & vol numbers - if we go that way - to be the same as EN date & vol numbers (my instinct is no as it is new work, but that could open complexities re the ISSN et al, which links to #698)

**Comment by arojascastro** [comment]
I think they are different works, printed translations usually get their own "metadata", but if it becomes troublesome... I guess our goal should be to make the whole conversion into PDF totally automatic.

**Comment by walshbr** [comment]
Just realized that with daylight savings time just began in America the times listed here might be a tad skewed.

**Comment by walshbr** [comment]
Just realized that since daylight savings time just began in America the times listed here might be a tad skewed. @acrymble can you confirm, as I'm not as familiar with the time changes in England and Germany? It looks like Germany will be on DST by March 29th but not England. 

By my math these would be the actual aligned timezones for March 29th - 6pm German, 4pm British, 12PM Eastern US, 9AM Pacific US. Does that sound correct? I was thinking that keeping the time stable for as many people as possible would mean asking the UK folks to move by an hour, but let me know if that's incorrect of if you have other suggestions. And sorry for the confusion!

**Comment by acrymble** [comment]
Our clocks change before the meeting. I can't say for anywhere else.

**Comment by walshbr** [comment]
Ah thanks - all should be fine then. And the meeting can stand at the normal time of 5PM British, 12PM Eastern US, 9AM Pacific US.

**Comment by JMParr** [comment]
Adding to our agenda our recent contact with a potential French language team.

**Comment by drjwbaker** [comment]
DH2018 hub issue: #765

**Comment by walshbr** [comment]
Actionables:

 #721 - I've updated the standing ticket on ongoing research with my own news, but please feel entitled to drop your own research updates there.
#766 - A new ticket was started to rough out a checklist for terms for sabbaticals.
 #651 - Internationalization and localization - make sure to check out the ticket and comment with further thoughts. @drjwbaker also volunteered to think about this more this year.
 #724 - Sponsorship - We'll include elements of this survey in the outreach component.
 #730 - Discussion on DH and Institutional Credit - we opened a ticket for adding volume and issue numbers. #767 
 #698 - How to list ES publications on DOAJ. -  @arojascastro will open a ticket addressing a technical/display issue that was causing confusion about this.
 Making a presence at DH2018 - #765 created for conversation about this.
#751 Nature of proposals we look for - make sure to check out the ticket and comment with further thoughts.
 French editorial team. - conversation continuing off-GitHub.

If I missed anything let me know? @acrymble I'm sorry that we didn't get to talk about github training for editors. If you wanted to open a ticket or send a note we could begin that conversation if you'd like.
