### ISSUE TITLE
Checklist for Sabbaticals

### ISSUE THREAD

**Issue by JMParr** [programminghistorian/jekyll#766]
Editors who are taking sabbatical should please ensure that they have done the following:

- [ ] Please make sure that you communicate with the rest of the team how long your sabbatical will last.

- [ ] Indicate whether your sabbatical will mean you will be completely away from the PH, or if you plan to participate in board meetings.

- [ ] You should indicate a date by which you expect to return to your editing duties. 

- [ ] Close out all open reviews and issues before you start your sabbatical.

- [ ] Set a reminder for yourself to check in with the rest of the editing team as your sabbatical comes to a close. 

- [ ] If you decide to leave the editorial board completely, please let the rest of the team know in a timely manner.

**Comment by mdlincoln** [comment]
once we settle on the generic list of things we want to do, I'll put this list template into the wiki. And then we should open an instance of these checklists, even just in our listserv (since we may not want to discuss these in public issues always)

**Comment by JMParr** [comment]
Ok!

**Comment by acrymble** [comment]
We can also note that we will never refuse a sabbatical and that all editors have a right to take them. This is really just about communicating availability to the project.

**Comment by walshbr** [comment]
Personally, codifying the terms and process like this probably would make me more likely to ask for one. Visibility of these sorts of things is important.

**Comment by acrymble** [comment]
A comment on the above suggestions. I think it's acceptable to ask someone to either close out issues / finish tasks, or find someone to pass them off to. What we don't want is tasks half done and have no one aware about what's happening to them.

Since @jerielizabeth and @vgayolrs are on sabbatical, it would be great to get their views.

**Comment by jerielizabeth** [comment]
Hi all! If this aids communication within the team, it makes sense to me. If I’ve been noticeably less present, I’ve recently changed notifications so I only get emails from GitHub when pinged directly (as in this case.) we’re a chatty bunch and my inbox was getting overwhelming :)

I’ve had a few lessons resurface while “away” and so I have kept doing that bit of editorial work. My sense is that it would be hard to switch editors on people (different expectations and all that) but deciding how to handle that should probably be in the checklist.

**Comment by acrymble** [comment]
Thanks everyone for your comments. I have added this to our Wiki: https://github.com/programminghistorian/jekyll/wiki/Checklist-for-Sabbaticals

Please add any amendments there.
