### ISSUE TITLE
Editorial Meeting Agenda - 4/23/18

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#777]
Time is 5PM British, 12PM Eastern US, 9AM Pacific US.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] any updates to standing call for submissions pending about ProgHist? #721
- [ ] github training for editors (@acrymble - holdover from last month's agenda)
- [ ] #378 French Translation (@JMParr to update on progress)
- [ ] #651 Language independence (@arojascastro)
- [x] ~~#686 Plans for 2018 (can we just close this?)~~
- [ ] #779 Tutorial Lengths (@acrymble)
- [ ] #751 What kind of Proposals do we want 
- [ ] #789 Quorum for important decisions?
- [ ] Replacement Skype call host for the next two sessions?

**Comment by drjwbaker** [comment]
Apologies, can't make this one.

**Comment by JMParr** [comment]
I think we can close the Plans for 2018.

**Comment by arojascastro** [comment]
I cannot make it either, sorry!

**Comment by walshbr** [comment]
Actionables!

- github training for editors - new editors should definitely have training. @mdlincoln will continue leading on this while assessing whether or not he needs more help on the technical team.
- #378 French Translation (@JMParr to update on progress). Next we will schedule a call between the Spanish team and the prospective French team. We will also devote the next monthly editorial call in May to a conversation with the French group about what a potential collaboration would look like. Also noted that the new group will likely need a lot of mentoring about the particular workflows we have set up. @acrymble is going to write up thoughts on these and drop them in #378 
-  #651 Language independence (@arojascastro). @acrymble will send an email to the group with a timeline for further comment before making a pull request.
-  #686 Plans for 2018 (can we just close this?) Is closed now.
-  #779 Tutorial Lengths (@acrymble). @acrymble will act on this.
-  #751 What kind of Proposals do we want. @acrymble again will include this in an email about policies with a note about timeline for giving input.
-  #789 Quorum for important decisions? @mdlincoln and @acrymble will comment in ticket on this.
-  Replacement Skype call host for the next two sessions? @amsichani volunteered to run the next two Skype calls as I am going to be traveling a lot. Thanks Anna-Maria!

**Comment by arojascastro** [comment]
As for #378, we have already scheduled a meeting on Thursday 3 May between the Spanish and the French team. So it's all right.

**Comment by walshbr** [comment]
Great - thanks for the update @arojascastro!

**Comment by drjwbaker** [comment]
@alsalin Were you there to offer an update on the response rate thus far for #576?

**Comment by walshbr** [comment]
Ah I should have mentioned that in the update/notes @drjwbaker. @alsalin can give more details, but the news she gave in the call was that we have 16 responses so far, all of which are from readers/users.
