### ISSUE TITLE
May Editorial Meeting Agenda - 31/05/2018

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#814]
Time is 5PM British, 12PM Eastern US, 9AM Pacific US.

Working agenda follows. Please add by commenting or editing this comment directly.

## Old business

- [x] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [x] #855 Language-independent landing page - POLICY issue until **1 June 2018** for giving input
- [x] #789 Quorum for important decisions? (Please see the [draft language](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance) linked to in that ticket - @mdlincoln) - POLICY issue until **10 June** to give input
- [x] #847 Make Technical Contributions Page (and Wiki) more visible - now a POLICY issue by @acrymble waiting for feedback on [this](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions) by no later than **10 June 2018** . Linked also to #836 in terms of translating it to ES & FR
- [x] #849 Reduce bus factor for service integrations. 
- [x] #576 Community survey update @alsalin 
- [ ] #724 Sponsorship of the Programming Historian 

## French version

- [x] #378 French Translation: technical & social expectations about the role of new editorial teams to be posted at Wiki - done [here ](https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy) 
- [x] @spapastamkou asks: 
- [x] #836 French Translation infrastructure pages : need to further communicate & implement them with the FR team - see also the the related [milestone](https://github.com/programminghistorian/jekyll/milestone/7).  Probably quick update on #826 , #867 (closed now), #864, #868
- whom do we (Marie + me) get in contact with from the team? Mainly to prepare the FR edition folder on ph-submission (and afterwards in jekyll). Would be useful to discuss on the steps to take 
- Time schedule for the preparation and launch of the FR edition
- Web archives: it could be possible to suggest the URL of the FR edition to the Bibliothèque nationale de France so that html captures be done by their robots for their web archives. (This can be seen as complementary to annual Zenodo deposits and the Internet Archive site captures)
- [x] #850 French [sticker] logo  / @spapastamkou asks: title of the Francophone edition
- [x] #871 Language sub-team communication channels 
- [x] #788 Additional ISSNs for ES (and FR now) - @drjwbaker also wants to comment on this [JB: this depends on if we agree on [https://github.com/programminghistorian/jekyll/issues/378#issuecomment-383892254](https://github.com/programminghistorian/jekyll/issues/378#issuecomment-383892254) That is, this is a technical choice that follows a structural one (reorganising our structure)]

**Comment by walshbr** [comment]
Thanks for organizing and covering this @amsichani!

**Comment by acrymble** [comment]
Can we talk about who has their github set up to receive email alerts? Particularly when tagged in posts? I get the sense that some people have turned this off, which is challenging when we're trying to close tickets that rely on participation.

**Comment by arojascastro** [comment]
Are the French friends taking part of this meeting?

**Comment by drjwbaker** [comment]
@acrymble I have everything on.

**Comment by jenniferisasi** [comment]
I believe I have all notifications on.

**Comment by alsalin** [comment]
I have everything on - which may be a problem because it's so much! Things might get lost in there.

**Comment by walshbr** [comment]
I've got all notifications on, though I selectively mute particular threads depending on the discussion (usually once I've already weighed in or if the content is pretty outside my wheelhouse - a typical example would be a ticket that is being conducted in Spanish, which I have a lot of difficulty reading). As I understand it, if you mute a thread but are mentioned in it you will be unmuted for it and then start getting notifications again.

**Comment by amsichani** [comment]
I have all notifications on.

**Comment by arojascastro** [comment]
I have them all on as well.

**Comment by arojascastro** [comment]
I think #812 was closed and it needs not further discussion - but I may be wrong.

**Comment by drjwbaker** [comment]
@arojascastro May be nice just to make everyone in the call aware that this happened. It is a nice technical solution that responds to author concerns about institutional credit (eg #730)

**Comment by walshbr** [comment]
Would be good to get our regular update of #721 in case anyone has news

**Comment by jenniferisasi** [comment]
Hi all! I'm sorry I won't be able to make it to the call tomorrow. I've tried my best to schedule my moving around several meetings and, unfortunately, I will be driving during this call. I will check on all the items/issues on the agenda after the meeting to see if there's anything new posted.

**Comment by spapastamkou** [comment]
Hi everybody. I prepared a small list with some points it would be useful to raise in this meeting. They are relevant to issues #378 #836 and #788:
- title of the Francophone edition
- information about previous efforts to make translations of the PH in French
- ISSN for FR edition: is it up to us to take contact with the BL? Or global demand?  
- Web archives: it could be possible to suggest the URL of the FR edition to the Bibliothèque nationale de France so that html captures be done by their robots for their web archives. (This can be seen as complementary to annual Zenodo deposits and the Internet Archive site captures) 
- To organize the set up of the FR edition, whom do we (Marie + me) get in contact with from the team? Mainly to prepare the FR edition folder on ph-submission (and afterwards in jekyll). Would be useful to discuss on the steps to take. 
-  Time schedule for the preparation and launch of the FR edition

**Comment by walshbr** [comment]
Sorry to miss!

**Comment by mdlincoln** [comment]
Because the list of possible discussion items has become so massive, I propose that we quickly get through the "policy" tickets at the very start of the meeting, as they're all now at the stage of being finished work, and are only open for finally comments on today's call.

**Comment by spapastamkou** [comment]
Okay with me - slight possibility of being a bit late

**Comment by alsalin** [comment]
To add - I'd like to give an update on the PH Community Survey #576 - i can always provide an overview here if we run out of time.

**Comment by acrymble** [comment]
@amsichani I don't think I have you as a contact on skype. You can find me at adam.crymble.

**Comment by amsichani** [comment]
OK for prioritising the policy tickets and I d add the FR integration process. Lets try to keep things on time. @acrymble no need , I think, I ll just call the Skype group.

**Comment by drjwbaker** [comment]
In the future can we make our calls no video by default? And can we all agree that Skype is terrible and we need to investigate using a different platform for calls if they are going to be important to how we make decisions?

**Comment by drjwbaker** [comment]
(and perhaps not use Skype)

**Comment by drjwbaker** [comment]
On..

> Web archives: it could be possible to suggest the URL of the FR edition to the Bibliothèque nationale de France so that html captures be done by their robots for their web archives. (This can be seen as complementary to annual Zenodo deposits and the Internet Archive site captures)

.. I think the BL Web Archive selective captures the EN work.

**Comment by acrymble** [comment]
I think the BL captures all of our site in their web archive. I got a tweet about that many years ago saying we'd been specially nominated.

**Comment by spapastamkou** [comment]
the EN edition is also on the Internet archive from 2012 on. The ES is
there as well, I checked yesterday.


Le jeu. 31 mai 2018 à 18:44, James Baker <notifications@github.com> a
écrit :
