### ISSUE TITLE
Onboarding FR editor checklist - Sofia 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#864]
This is a individual onboarding editor checklist for @spapastamkou, initially found [here 
](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Please do also have a look at the [specific FR team milestone ](https://github.com/programminghistorian/jekyll/milestone/7) and the [French Translation infrastructure pages ](https://github.com/programminghistorian/jekyll/issues/836).
## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@acrymble)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@acrymble)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x] Our Skype group so that you can participate in our monthly calls (@walshbr)
- [x] We will also write a blog post welcoming you publicly to the team.
- [x] partner you with an existing editor to 'shadow' the editing process so you can get a feel for it.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @walshbr (mandatory)
- [x] inform @acrymble of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

## The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by acrymble** [comment]
@spapastamkou I've added you to our Twitter team. But that only works if you use Tweetdeck. I think a number of our team do not, so we might have to find another solution to this problem.

**Comment by spapastamkou** [comment]
thank you. That's fine with me, I just accepted the invitation on tweetdeck
and everything seems ok.

Le ven. 25 mai 2018 à 08:40, Adam Crymble <notifications@github.com> a
écrit :

**Comment by acrymble** [comment]
Who is writing the blog post? @amsichani ?

**Comment by amsichani** [comment]
Sure thing! I was thinking maybe it 'd be good to write one blogpost for the FR task force (aka Sofia& Marie) but wait first for them both to complete their onboarding editor's checklists. Thoughts?

**Comment by spapastamkou** [comment]
We'll speed up with @mpuren so that you have all you need

**Comment by acrymble** [comment]
@spapastamkou can you let us know if you need help adding your picture and bio to the project team page? We'd like to get this up soon so we can announce you have joined us.

**Comment by spapastamkou** [comment]
I'll do my best to arrange that this evening, sorry for the delay.

**Comment by spapastamkou** [comment]
before I send my commits and open a pull request, I would like to be sure
whether the branch I work in has to be named after this ticket or be
gh-pages. Can you confirm please @mdlincoln ? Thanks in advance

**Comment by mdlincoln** [comment]
Create a new branch. See the instructions here: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#the-branch

**Comment by spapastamkou** [comment]
thank you

**Comment by acrymble** [comment]
We haven't finished this checklist yet, so reopening.

**Comment by spapastamkou** [comment]
@acrymble in order to be done with my part of tasks, in particular that of opening a new ticket: can I do that for discussing the idea of a workshop for the FR version in a forthcoming DH conf in France or I'd better place the discussion in #721 ?

**Comment by acrymble** [comment]
you can open a ticket for anything. It's just to make sure you've had experience doing it.

But yes, that sounds appropriate if you would like feedback from the team.

**Comment by acrymble** [comment]
@spapastamkou can you please finish this off so we can close this ticket?

**Comment by spapastamkou** [comment]
I just opened a ticket (#940), so I believe I am done and this one can be closed. Thank you.
