### ISSUE TITLE
Onboarding FR editor checklist - Marie

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#868]
This is a individual onboarding editor checklist for @mpuren,  initially found [here 
](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Please do also have a look at the [specific FR team milestone ](https://github.com/programminghistorian/jekyll/milestone/7) and the [French Translation infrastructure pages ](https://github.com/programminghistorian/jekyll/issues/836).
## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@acrymble)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@acrymble)
- [x] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [x] Our Skype group so that you can participate in our monthly calls (@walshbr)
- [x] We will also write a blog post welcoming you publicly to the team.
- [x] partner you with an existing editor to 'shadow' the editing process so you can get a feel for it.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @walshbr (mandatory)
- [x] inform @acrymble of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

## The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by acrymble** [comment]
Does Marie know about this list? I haven't got her email so I can't contact her about the google group.

**Comment by amsichani** [comment]
@acrymble email sent -

**Comment by acrymble** [comment]
@mpuren can you let us know if you need help adding your picture and bio to the project team page? We'd like to get this up soon so we can announce you have joined us.

**Comment by mpuren** [comment]
@acrymble I'm not sure of what I should do... So yes, a little help will be very useful!

**Comment by acrymble** [comment]
Of course @mpuren. It can be difficult the first time, but once you know how it is easy.

* First, you make a new ticket on Github and give it a relevant name and description (eg, Adding Myself to the Project Team page).

* Then you find an image of yourself, crop it to a square, convert it to black and white, save it as marie-puren.png (you can see an example here:
https://github.com/programminghistorian/jekyll/blob/gh-pages/avatars/Jennifer-Isasi.png)

* Then you have to create a new "Branch" on Github following the "Technical Contributions" instructions (https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions).

* Then you add your biographical details to https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml and upload your image to the avatars folder: https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars

* Finally, you make a pull request, again following the instructions on the "Technical Contributions" Wiki page.

That's it!

**Comment by mpuren** [comment]
@acrymble Thanks a lot! That's very clear, I think I can manage. I add my picture and a bio asap.

**Comment by acrymble** [comment]
@amsichani would you mind doing the blog post welcoming our new French members now that the profiles are up? I'm swamped at the minute :(

**Comment by amsichani** [comment]
I am planning to do so by next Wed, 4th July (viva is on its way) - collecting additional info from @mpuren and @spapastamkou at the moment.

**Comment by acrymble** [comment]
@mpuren the last actions on this are yours. Can you complete this checklist soon so we can close this ticket and move on to more exciting things?

**Comment by mpuren** [comment]
Sorry, I'm on it

**Comment by mpuren** [comment]
Surprisingly, I've completed my onboarding checklist. So I think I can close this ticket.
