### ISSUE TITLE
Onboarding FR editor checklist - Thibault 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#869]
This is a individual onboarding editor checklist for @PonteIneptique, initially found [here 
](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors). Please do also have a look at the [specific FR team milestone ](https://github.com/programminghistorian/jekyll/milestone/7) and the [French Translation infrastructure pages ](https://github.com/programminghistorian/jekyll/issues/836).
## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [ ] Our Google Group email so you can communicate with other editors (@acrymble)
- [ ] Our Google Analytics account for monitoring web traffic (@acrymble)
- [ ] Our Twitter team (@acrymble)
- [ ] Our Github Repository so you can upload materials to the site (@mdlincoln)
- [ ] Our Skype group so that you can participate in our monthly calls (@walshbr or @amsichani)
- [ ] We will also write a blog post welcoming you publicly to the team.
- [ ] partner you with an existing editor to 'shadow' the editing process so you can get a feel for it.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:
### communication

- [ ] set up a GitHub account and inform @mdlincoln of your username (mandatory)
- [ ] set up a twitter account (optional)
- [ ] set up a Skype account and inform @walshbr (mandatory)
- [ ] inform @acrymble of your Google-activated email (mandatory)
- [ ] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [ ] contribute to one open ticket on our github repository (mandatory)
- [ ] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [ ] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [ ] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [ ] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [ ] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

## The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by PonteIneptique** [comment]
I think there has been a mistake here :) I have vouched to support the project by integrating participation in the curriculum of my students, but I unfortunately can't find the time to be an editor.

But thanks for the invitation :)

**Comment by amsichani** [comment]
Thanks for the clarification @PonteIneptique ! We had a list of names for the FR team and I thought you are all going to be joining as editors. Given this, probably we need to rethink about project's role types in general.

**Comment by amsichani** [comment]
this issue is now closed until we further clarify FR-member's degree/ status of engagement with the project
