### ISSUE TITLE
July Editorial Call Agenda - 25/7/2018

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#919]
#868 Time is 5PM British, 12PM Eastern US, 9AM Pacific US. I'll be facilitating.

Working agenda follows. Please add by commenting or editing this comment directly.

#721 Current Research Projects or Submissions Pending about the Programming Historian.
#849 Reduce bus factor for service integrations.
#918 Recognition of Sponsorship/Donations
#864 #868 onboarding of French team
#836 & #940 French translation infrastructure pages  
#878 getting a budget line for the project (James)
#576 Community discussion findings (Anandi)
#905 NPOV policy (Adam)

**Comment by arojascastro** [comment]
I am on holidays in July 💃

**Comment by walshbr** [comment]
Actionables/Notes from Meeting
- [ ] #849 Reduce bus factor for service integrations. waiting on @mdlincoln 
- [ ] #918 Recognition of Sponsorship/Donations -  @drjwbaker is looking for others to help draft a proposal for this. @amsichani will assist.
- [X] #864 #868 onboarding of French team
- [ ] #836 & #940 French translation infrastructure pages - goal is to have main things translated by end of summer. They'll solidify choices and then post decisions about process to wiki.
- [ ] #878 getting a budget line for the project (James) @drjwbaker will update us soon on this. 
- [ ] #576 Community discussion findings (Anandi) @alsalin is going to look at data again in light of all the new submissions post-conferences. She'll then write up a blog post and make recommendations for tickets.
- [ ] #905 NPOV policy (Adam). Deadline for discussion before adopting or not posted in ticket.
