### ISSUE TITLE
August Editorial Agenda - 8/30/2018

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#949]
Time is 5PM British, 12PM Eastern US, 9AM Pacific US. I'll be facilitating. Date is 8/30/2018.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.

Funding Related Issues:
- [ ] https://github.com/programminghistorian/jekyll/issues/918#issuecomment-408109200 Types of Sponsorship we will not accept (**Policy**, deadline 7 September).
- [ ] #948 New positions: Treasurer + Sponsorship Coordinator.
- [ ] https://github.com/programminghistorian/jekyll/issues/915#issuecomment-409829679 Support Us wording (**Policy**, deadline 1 October) *For discussion at September meeting: please take a look by then*

---

- [ ] new call time in the future
- [ ] #836 - update on French Translation of infrastructure pages
- [ ] managing editor / skype coordinator handover (@alsalin @mariajoafana)
- [ ] #835 Spanish-to-English person (@acrymble) 
- [ ] #991 & #992 - shorten editorial guidelines and introduce a md template for authors (@acrymble)

Things we don't really need to discuss, but that are waiting for a specific individual to do something:
- [ ] #576 - community discussion survey - create tickets (@alsalin)
- [ ] #849 - reduce bus factor for services (@mdlincoln)
- [ ] #884 - Solicit academic review in Spanish (@vgayolrs)
- [ ] #901 - Worldcat entry in Spanish (@vgaylors)
- [ ] #961 - Move Sample Datasets for Creating Network Diagrams lesson (@mariajoafana)

**Comment by drjwbaker** [comment]
I'm on leave. @amsichani: if you are able to attend can you take #918 & #948 for me please.

**Comment by amsichani** [comment]
I am on leave too - sorry for this @drjwbaker

**Comment by drjwbaker** [comment]
No worries, you are allowed a break!

**Comment by acrymble** [comment]
If I'm not mistaken, with @mdlincoln moving to EST, I think we can condense our timezone spread by 3 timezones. That means that in future we might be able to move the time so that our European colleagues aren't having to do the call outside of business hours? (sorry, forgot about Mexico and Colombia, but I still think we can condense it)

**Comment by walshbr** [comment]
Excellent point @acrymble. I'll make a note on the agenda to discuss this.

**Comment by acrymble** [comment]
If @drjwbaker and @amsichani are away then are we able to do #918 or #948? @walshbr maybe we have to postpone those ones? Though it would be nice to get that up and running...

**Comment by drjwbaker** [comment]
From holiday, #918 has a 7 September policy deadline: you might want to discuss and decide if you'd like to extend this until after the September call.
On #948, perhaps you can discuss and raise potential actions/concerns/things to consider for us before we move to a policy suggestion.

**Comment by walshbr** [comment]
@drjwbaker's suggestion works for me. We can assess in the call if we need to postpone.

**Comment by mdlincoln** [comment]
It looks like I will indeed have a conflict for this month's meeting - sorry to miss it! But now that I know what my CMU calendar looks like, I should be able to make the September one 😄

**Comment by spapastamkou** [comment]
hi everyone, quite unexpectedly I can make myself available for the meeting so see you all later today

**Comment by mariajoafana** [comment]
I can be in the meeting as well, for about 30-40 minutes

**Comment by arojascastro** [comment]
Unfortunately, I cannot make it today. I cleared out all my issues except one pull request. See you in January.

**Comment by walshbr** [comment]
- [x]   #721 - @mariajoafana and @acrymble are going to look into sharing materials from the Bogotá workshop to help people applying for their own PH grants in the future.
- [x]   #918 (comment) Types of Sponsorship we will not accept (Policy, deadline 7 September) - @walshbr will post in thread.
- [x]   #948 New positions: Treasurer + Sponsorship Coordinator @walshbr will post in thread.
- [x]   #915 (comment) Support Us wording (Policy, deadline 1 October) For discussion at September meeting: please take a look by then. @walshbr will post in thread.
- [x]   new call time in the future - we're going to try the following time from now on: 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - French time. cc / @amsichani 
- [ ]   #836 - update on French Translation of infrastructure pages. The French team is hoping to have this mostly resolved by end of next week.
- [x]   managing editor / skype coordinator handover. All is in hand. @acrymble is going to open tickets to the effect of updating the ME position so that they handle all pull requests for new lessons.
- [x]   #835 Spanish-to-English person - @walshbr will send an email soliciting volunteers for a search committee.
- [x]   #991 & #992 - shorten editorial guidelines and introduce a md template for authors - @acrymble will go ahead.
- [ ]   #576 - community discussion survey - create ideas for tickets by 9/15 at the request of @alsalin
One off things that just need to be resolved - no real discussion.
- [ ]   #849 - reduce bus factor for services (@mdlincoln)
- [ ]   #884 - Solicit academic review in Spanish (@vgayolrs)
- [ ]   #901 - Worldcat entry in Spanish (@vgayolrs)
- [ ]   #961 - Move Sample Datasets for Creating Network Diagrams lesson (@mariajoafana)
