### ISSUE TITLE
Antonio Sabattical Checklist

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#985]
@arojascastro has informed us that he intends to go on Sabbatical from September 2018 until January 2019.

I thought it would help to have a checklist of outstanding tickets he needs to close or that someone else needs to take over:

TIckets - jekyll repo
- [x] #972 Update metadata block examples in Spanish (@arojascastro to close)
- [x] #965 Correct Typo in Spanish translation (@arojascastro to close)
- [x] #929 Pending changes in "Procesamiento básico de textos con R" (@arojascastro to close)
- [ ] #958 ~~inclusive language in PH es (@vgayolrs to close)~~
- [ ] #936 ~~Standardization of new proposals (@acrymble to take lead)~~

Tickets - submissions repo

- [x] 164 - Datos tabular con R - https://github.com/programminghistorian/ph-submissions/issues/164 (@arojascastro to close)

@arojascastro can you let us know what help you need?

**Comment by arojascastro** [comment]
Thank you! This is already very helpful. I'll close tickets 164, 965, 929, 972 for sure. I am not sure if I will close tickets 958 and 936 since they need team collaboration. I am pining @mariajoafana @vgayolrs @jamotilla @jenniferisasi so they are aware of them.

**Comment by acrymble** [comment]
I will continue to help with #936

**Comment by acrymble** [comment]
Thank you @arojascastro we will see you in January 2019!
